syntax = "proto3";

option java_package = "com.aqua.aqualight.data.devices.light.programs";
option java_multiple_files = true;

message LightProgramsPreferences {
  repeated LightProgram programs = 1;
}

message LightProgram {
  string id = 1;
  int64 device_id = 2;
  string name = 3;
  bool is_active = 4;

  LightCurveTiming timing = 5;
  LightChannelValues channels = 6;

  RepeatMode repeat_mode = 7;
  repeated int32 selected_days = 8;

  TransitionMode transition_mode = 11;

  int64 created_at = 12;
  int64 updated_at = 13;
}

message LightCurveTiming {
  TimePoint start = 1;
  TimePoint peak_start = 2;
  TimePoint peak_end = 3;
  TimePoint end = 4;
}

message TimePoint {
  int32 hour = 1;
  int32 minute = 2;
}

message LightChannelValues {
  int32 red = 1;
  int32 green = 2;
  int32 blue = 3;
  int32 white = 4;
}

enum RepeatMode {
  REPEAT_MODE_EVERY = 0;
  REPEAT_MODE_WEEK = 1;
  REPEAT_MODE_WEEKEND = 2;
  REPEAT_MODE_CUSTOM = 3;
}

enum TransitionMode {
  TRANSITION_MODE_LINEAR = 0;
  TRANSITION_MODE_SMOOTH = 1;
  TRANSITION_MODE_NATURAL = 2;
}