syntax = "proto3";
option java_package = "com.aqua.aqualight.data";
option java_multiple_files = true;

message UserPreferences {
  string idToken         = 1;
  string email           = 2;
  string username        = 3;
  string profilePhotoUrl = 4;
  bool   isLoggedIn      = 5;
  string fullName        = 6;
  string themeMode       = 7;
  string languageCode    = 8;
  bool   notificationsEnabled = 9;
  bool   autoUpdateEnabled     = 10;

  // 🆕 Adres bilgileri
  string firstName       = 11;
  string lastName        = 12;
  string city            = 13;
  string addressLine     = 14;
  string postCode        = 15;
  string phoneNumber     = 16;
  string country         = 17;
}