package com.aqua.aqualight.ui.tabs.aquarium.create.plants

object PlantCatalog {

    private fun plant(
        name: String,
        category: String
    ): AquariumPlant {
        return AquariumPlant(
            name = name,
            category = category
        )
    }

    val plants: List<AquariumPlant> = listOf(

        // --------------------------------------------------------
        // Epiphytes
        // --------------------------------------------------------
        plant("Anubias barteri", "Epiphytes"),
        plant("Anubias barteri var. nana", "Epiphytes"),
        plant("Anubias barteri var. nana 'Petite'", "Epiphytes"),
        plant("Anubias barteri var. nana 'Mini'", "Epiphytes"),
        plant("Anubias barteri var. nana 'Pangolino'", "Epiphytes"),
        plant("Anubias barteri var. caladiifolia", "Epiphytes"),
        plant("Anubias barteri var. coffeefolia", "Epiphytes"),
        plant("Anubias gracilis", "Epiphytes"),
        plant("Anubias hastifolia", "Epiphytes"),
        plant("Anubias heterophylla", "Epiphytes"),
        plant("Bucephalandra sp. 'Catarina'", "Epiphytes"),
        plant("Bucephalandra sp. 'Theia Green'", "Epiphytes"),
        plant("Bucephalandra sp. 'Biblis'", "Epiphytes"),
        plant("Bucephalandra sp. 'Brownie Ghost'", "Epiphytes"),
        plant("Bucephalandra sp. 'Brownie Blue'", "Epiphytes"),
        plant("Bucephalandra sp. 'Kedagang'", "Epiphytes"),
        plant("Bucephalandra sp. 'Mini Coin'", "Epiphytes"),
        plant("Bucephalandra sp. 'Needle Leaf'", "Epiphytes"),
        plant("Bucephalandra sp. 'Red Mini'", "Epiphytes"),
        plant("Bucephalandra sp. 'Wavy Green'", "Epiphytes"),
        plant("Microsorum pteropus", "Epiphytes"),
        plant("Microsorum pteropus 'Narrow'", "Epiphytes"),
        plant("Microsorum pteropus 'Trident'", "Epiphytes"),
        plant("Microsorum pteropus 'Windelov'", "Epiphytes"),
        plant("Microsorum pteropus 'Needle Leaf'", "Epiphytes"),
        plant("Bolbitis heudelotii", "Epiphytes"),
        plant("Bolbitis heteroclita 'Difformis'", "Epiphytes"),
        plant("Hygrophila pinnatifida", "Epiphytes"),

        // --------------------------------------------------------
        // Foreground
        // --------------------------------------------------------
        plant("Cryptocoryne parva", "Foreground"),
        plant("Cryptocoryne lucens", "Foreground"),
        plant("Cryptocoryne willisii", "Foreground"),
        plant("Staurogyne repens", "Foreground"),
        plant("Pogostemon helferi", "Foreground"),
        plant("Lobelia cardinalis 'Mini'", "Foreground"),
        plant("Alternanthera reineckii 'Mini'", "Foreground"),
        plant("Helanthium tenellum", "Foreground"),
        plant("Helanthium tenellum 'Green'", "Foreground"),
        plant("Lilaeopsis brasiliensis", "Foreground"),
        plant("Lilaeopsis novae-zelandiae", "Foreground"),
        plant("Marsilea hirsuta", "Foreground"),
        plant("Marsilea crenata", "Foreground"),
        plant("Marsilea minuta", "Foreground"),
        plant("Ranunculus inundatus", "Foreground"),
        plant("Eriocaulon cinereum", "Foreground"),
        plant("Sagittaria subulata", "Foreground"),
        plant("Blyxa japonica", "Foreground"),

        // --------------------------------------------------------
        // Ground Cover
        // --------------------------------------------------------
        plant("Hemianthus callitrichoides 'Cuba'", "Ground Cover"),
        plant("Micranthemum tweediei 'Monte Carlo'", "Ground Cover"),
        plant("Glossostigma elatinoides", "Ground Cover"),
        plant("Eleocharis acicularis", "Ground Cover"),
        plant("Eleocharis acicularis 'Mini'", "Ground Cover"),
        plant("Eleocharis parvula", "Ground Cover"),
        plant("Eleocharis pusilla", "Ground Cover"),
        plant("Utricularia graminifolia", "Ground Cover"),
        plant("Hydrocotyle tripartita 'Japan'", "Ground Cover"),
        plant("Marsilea quadrifolia", "Ground Cover"),
        plant("Marsilea crenata", "Ground Cover"),
        plant("Marsilea hirsuta", "Ground Cover"),
        plant("Lilaeopsis brasiliensis", "Ground Cover"),
        plant("Lilaeopsis mauritiana", "Ground Cover"),
        plant("Riccia fluitans", "Ground Cover"),

        // --------------------------------------------------------
        // Middle Ground
        // --------------------------------------------------------
        plant("Cryptocoryne wendtii 'Green'", "Middle Ground"),
        plant("Cryptocoryne wendtii 'Brown'", "Middle Ground"),
        plant("Cryptocoryne wendtii 'Tropica'", "Middle Ground"),
        plant("Cryptocoryne wendtii 'Mi Oya'", "Middle Ground"),
        plant("Cryptocoryne beckettii", "Middle Ground"),
        plant("Cryptocoryne undulata", "Middle Ground"),
        plant("Cryptocoryne lutea", "Middle Ground"),
        plant("Cryptocoryne albida", "Middle Ground"),
        plant("Cryptocoryne balansae", "Middle Ground"),
        plant("Cryptocoryne spiralis", "Middle Ground"),
        plant("Cryptocoryne pontederiifolia", "Middle Ground"),
        plant("Cryptocoryne crispatula", "Middle Ground"),
        plant("Lagenandra meeboldii 'Red'", "Middle Ground"),
        plant("Lagenandra meeboldii 'Green'", "Middle Ground"),
        plant("Hygrophila corymbosa 'Compact'", "Middle Ground"),
        plant("Hygrophila polysperma 'Rosanervig'", "Middle Ground"),
        plant("Pogostemon erectus", "Middle Ground"),
        plant("Rotala indica 'Bonsai'", "Middle Ground"),
        plant("Rotala rotundifolia 'Green'", "Middle Ground"),
        plant("Bacopa compacta", "Middle Ground"),
        plant("Bacopa caroliniana", "Middle Ground"),
        plant("Bacopa monnieri", "Middle Ground"),
        plant("Ludwigia palustris 'Super Red'", "Middle Ground"),
        plant("Ludwigia repens", "Middle Ground"),
        plant("Nymphoides hydrophylla 'Taiwan'", "Middle Ground"),
        plant("Hydrocotyle leucocephala", "Middle Ground"),
        plant("Hydrocotyle verticillata", "Middle Ground"),

        // --------------------------------------------------------
        // Background
        // --------------------------------------------------------
        plant("Vallisneria spiralis", "Background"),
        plant("Vallisneria americana", "Background"),
        plant("Vallisneria nana", "Background"),
        plant("Vallisneria gigantea", "Background"),
        plant("Egeria densa", "Background"),
        plant("Elodea canadensis", "Background"),
        plant("Limnophila sessiliflora", "Background"),
        plant("Limnophila aromatica", "Background"),
        plant("Limnophila hippuridoides", "Background"),
        plant("Cabomba caroliniana", "Background"),
        plant("Cabomba aquatica", "Background"),
        plant("Myriophyllum mattogrossense", "Background"),
        plant("Myriophyllum aquaticum", "Background"),
        plant("Myriophyllum tuberculatum", "Background"),
        plant("Rotala rotundifolia", "Background"),
        plant("Rotala rotundifolia 'H'ra'", "Background"),
        plant("Rotala rotundifolia 'Orange Juice'", "Background"),
        plant("Rotala wallichii", "Background"),
        plant("Rotala macrandra", "Background"),
        plant("Rotala macrandra 'Green'", "Background"),
        plant("Rotala macrandra 'Mini Butterfly'", "Background"),
        plant("Ludwigia arcuata", "Background"),
        plant("Ludwigia glandulosa", "Background"),
        plant("Ludwigia inclinata", "Background"),
        plant("Ludwigia inclinata var. verticillata 'Cuba'", "Background"),
        plant("Ludwigia inclinata var. verticillata 'Pantanal'", "Background"),
        plant("Hygrophila polysperma", "Background"),
        plant("Hygrophila corymbosa", "Background"),
        plant("Hygrophila difformis", "Background"),
        plant("Heteranthera zosterifolia", "Background"),
        plant("Pogostemon stellatus", "Background"),
        plant("Pogostemon stellatus 'Octopus'", "Background"),
        plant("Proserpinaca palustris", "Background"),
        plant("Alternanthera reineckii", "Background"),
        plant("Alternanthera reineckii 'Rosanervig'", "Background"),
        plant("Alternanthera reineckii 'Red Ruby'", "Background"),
        plant("Ammannia gracilis", "Background"),
        plant("Ammannia senegalensis", "Background"),
        plant("Bacopa australis", "Background"),
        plant("Bacopa caroliniana", "Background"),
        plant("Bacopa monnieri", "Background"),
        plant("Didiplis diandra", "Background"),
        plant("Mayaca fluviatilis", "Background"),
        plant("Eichhornia diversifolia", "Background"),
        plant("Aponogeton crispus", "Background"),
        plant("Aponogeton ulvaceus", "Background"),
        plant("Crinum calamistratum", "Background"),
        plant("Crinum natans", "Background"),
        plant("Echinodorus bleheri", "Background"),
        plant("Echinodorus grisebachii", "Background"),
        plant("Echinodorus 'Ozelot'", "Background"),
        plant("Echinodorus 'Red Diamond'", "Background"),
        plant("Echinodorus 'Reni'", "Background"),

        // --------------------------------------------------------
        // Mosses
        // --------------------------------------------------------
        plant("Taxiphyllum barbieri", "Mosses"),
        plant("Taxiphyllum sp. 'Flame Moss'", "Mosses"),
        plant("Taxiphyllum sp. 'Spiky Moss'", "Mosses"),
        plant("Taxiphyllum sp. 'Peacock Moss'", "Mosses"),
        plant("Vesicularia montagnei 'Christmas Moss'", "Mosses"),
        plant("Vesicularia ferriei 'Weeping Moss'", "Mosses"),
        plant("Vesicularia dubyana", "Mosses"),
        plant("Vesicularia sp. 'Mini Christmas Moss'", "Mosses"),
        plant("Fissidens fontanus", "Mosses"),
        plant("Fissidens nobilis", "Mosses"),
        plant("Riccardia chamedryfolia", "Mosses"),
        plant("Riccardia graeffei", "Mosses"),
        plant("Leptodictyum riparium", "Mosses"),
        plant("Amblystegium serpens", "Mosses"),
        plant("Monosolenium tenerum", "Mosses"),
        plant("Lomariopsis lineata", "Mosses"),
        plant("Cladophora aegagropila", "Mosses"),

        // --------------------------------------------------------
        // Floating Plants
        // --------------------------------------------------------
        plant("Salvinia natans", "Floating Plants"),
        plant("Salvinia minima", "Floating Plants"),
        plant("Salvinia auriculata", "Floating Plants"),
        plant("Phyllanthus fluitans", "Floating Plants"),
        plant("Limnobium laevigatum", "Floating Plants"),
        plant("Pistia stratiotes", "Floating Plants"),
        plant("Lemna minor", "Floating Plants"),
        plant("Spirodela polyrhiza", "Floating Plants"),
        plant("Azolla caroliniana", "Floating Plants"),
        plant("Azolla filiculoides", "Floating Plants"),
        plant("Riccia fluitans", "Floating Plants"),
        plant("Ceratopteris cornuta", "Floating Plants"),
        plant("Ceratopteris thalictroides", "Floating Plants"),
        plant("Hygroryza aristata", "Floating Plants"),
        plant("Hydrocharis morsus-ranae", "Floating Plants"),

        // --------------------------------------------------------
        // Rare Plants
        // --------------------------------------------------------
        plant("Eriocaulon sp. 'Vietnam'", "Rare Plants"),
        plant("Eriocaulon sp. 'Japan Needle Leaf'", "Rare Plants"),
        plant("Eriocaulon setaceum", "Rare Plants"),
        plant("Syngonanthus macrocaulon", "Rare Plants"),
        plant("Syngonanthus sp. 'Belem'", "Rare Plants"),
        plant("Tonina fluviatilis", "Rare Plants"),
        plant("Tonina sp. 'Belem'", "Rare Plants"),
        plant("Tonina sp. 'Manaus'", "Rare Plants"),
        plant("Ludwigia sp. 'White'", "Rare Plants"),
        plant("Ludwigia inclinata var. verticillata 'White'", "Rare Plants"),
        plant("Rotala ramosior 'Florida'", "Rare Plants"),
        plant("Rotala sp. 'Pearl'", "Rare Plants"),
        plant("Rotala sp. 'Blood Red'", "Rare Plants"),
        plant("Rotala sp. 'Vietnam H'ra'", "Rare Plants"),
        plant("Ammannia pedicellata 'Golden'", "Rare Plants"),
        plant("Ammannia praetermissa", "Rare Plants"),
        plant("Pogostemon yatabeanus", "Rare Plants"),
        plant("Pogostemon kimberley", "Rare Plants"),
        plant("Pogostemon deccanensis", "Rare Plants"),
        plant("Aponogeton madagascariensis", "Rare Plants"),
        plant("Aponogeton boivinianus", "Rare Plants"),
        plant("Barclaya longifolia", "Rare Plants"),
        plant("Barclaya longifolia 'Red'", "Rare Plants"),
        plant("Nymphaea lotus 'Red'", "Rare Plants"),
        plant("Nymphaea micrantha", "Rare Plants"),
        plant("Nymphaea stellata", "Rare Plants"),
        plant("Crinum thaianum", "Rare Plants"),
        plant("Lagenandra keralensis", "Rare Plants"),
        plant("Lagenandra thwaitesii", "Rare Plants"),
        plant("Cryptocoryne flamingo", "Rare Plants"),
        plant("Cryptocoryne nurii", "Rare Plants"),
        plant("Cryptocoryne cordata 'Rosanervig'", "Rare Plants"),
        plant("Bucephalandra sp. 'Black Pearl'", "Rare Plants"),
        plant("Bucephalandra sp. 'Dark Skeleton King'", "Rare Plants"),
        plant("Bucephalandra sp. 'Godzilla'", "Rare Plants"),
        plant("Bucephalandra sp. 'Silver Powder'", "Rare Plants")
    )
}