# Bellek ve kodlama
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# AndroidX geçişi
android.useAndroidX=true
android.enableJetifier=true   # Eski support lib yoksa bunu false yaparak hız kazanabilirsin

# Hız ayarları
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.incremental=true

# (Opsiyonel, hız için yerelde faydalı)
org.gradle.vfs.watch=true