# Bellek ve kodlama
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
# Eski support lib yoksa false yapabilirsin
android.enableJetifier=false

# Hız ayarları
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.incremental=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false