pluginManagement {
  repositories {
    google()
    maven { url "https://maven.google.com" } // explicit
    mavenCentral()
    gradlePluginPortal()
  }
  plugins {
    id 'com.android.application'         version '8.10.0'
    id 'org.jetbrains.kotlin.android'    version '1.9.25'
    id 'com.google.gms.google-services'  version '4.4.4'
    id 'com.google.firebase.crashlytics' version '3.0.6'
    id 'com.google.protobuf'             version '0.9.5'
  }
}

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    maven { url "https://maven.google.com" } // explicit
    mavenCentral()
    maven { url 'https://jitpack.io' }       // BlurView
  }
}

rootProject.name = "AquaLight"
include(":app")