pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'com.android.application' version '8.10.0'
        id 'org.jetbrains.kotlin.android' version '2.1.0'
        id 'com.google.gms.google-services' version '4.4.4'
        id 'com.google.protobuf' version '0.9.5'
        id 'androidx.navigation.safeargs.kotlin' version '2.9.5'
        id 'io.gitlab.arturbosch.detekt' version '1.23.8'
        id 'org.jetbrains.kotlinx.kover' version '0.9.9'
        id 'org.cyclonedx.bom' version '3.3.0'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = 'AquaLight'
include(':app')
