package com.aqua.aqualight.ui.tabs.aquarium.catalog.plant

import android.content.Context
import androidx.annotation.StringRes
import com.aqua.aqualight.R

object PlantCatalog {

    private fun plants(
        @StringRes categoryRes: Int,
        @StringRes vararg nameResources: Int
    ): List<AquariumPlantDefinition> = nameResources.map { nameRes ->
        AquariumPlantDefinition(
            nameRes = nameRes,
            categoryRes = categoryRes
        )
    }

    val definitions: List<AquariumPlantDefinition> = buildList {
        addAll(
            plants(
                R.string.catalog_plant_category_epiphytes_title,
                R.string.catalog_plant_anubias_barteri_name,
                R.string.catalog_plant_anubias_barteri_var_nana_name,
                R.string.catalog_plant_anubias_barteri_var_nana_petite_name,
                R.string.catalog_plant_anubias_barteri_var_nana_mini_name,
                R.string.catalog_plant_anubias_barteri_var_nana_pangolino_name,
                R.string.catalog_plant_anubias_barteri_var_caladiifolia_name,
                R.string.catalog_plant_anubias_barteri_var_coffeefolia_name,
                R.string.catalog_plant_anubias_gracilis_name,
                R.string.catalog_plant_anubias_hastifolia_name,
                R.string.catalog_plant_anubias_heterophylla_name,
                R.string.catalog_plant_bucephalandra_sp_catarina_name,
                R.string.catalog_plant_bucephalandra_sp_theia_green_name,
                R.string.catalog_plant_bucephalandra_sp_biblis_name,
                R.string.catalog_plant_bucephalandra_sp_brownie_ghost_name,
                R.string.catalog_plant_bucephalandra_sp_brownie_blue_name,
                R.string.catalog_plant_bucephalandra_sp_kedagang_name,
                R.string.catalog_plant_bucephalandra_sp_mini_coin_name,
                R.string.catalog_plant_bucephalandra_sp_needle_leaf_name,
                R.string.catalog_plant_bucephalandra_sp_red_mini_name,
                R.string.catalog_plant_bucephalandra_sp_wavy_green_name,
                R.string.catalog_plant_microsorum_pteropus_name,
                R.string.catalog_plant_microsorum_pteropus_narrow_name,
                R.string.catalog_plant_microsorum_pteropus_trident_name,
                R.string.catalog_plant_microsorum_pteropus_windelov_name,
                R.string.catalog_plant_microsorum_pteropus_needle_leaf_name,
                R.string.catalog_plant_bolbitis_heudelotii_name,
                R.string.catalog_plant_bolbitis_heteroclita_difformis_name,
                R.string.catalog_plant_hygrophila_pinnatifida_name
            )
        )
        addAll(
            plants(
                R.string.catalog_plant_category_foreground_title,
                R.string.catalog_plant_cryptocoryne_parva_name,
                R.string.catalog_plant_cryptocoryne_lucens_name,
                R.string.catalog_plant_cryptocoryne_willisii_name,
                R.string.catalog_plant_staurogyne_repens_name,
                R.string.catalog_plant_pogostemon_helferi_name,
                R.string.catalog_plant_lobelia_cardinalis_mini_name,
                R.string.catalog_plant_alternanthera_reineckii_mini_name,
                R.string.catalog_plant_helanthium_tenellum_name,
                R.string.catalog_plant_helanthium_tenellum_green_name,
                R.string.catalog_plant_lilaeopsis_brasiliensis_name,
                R.string.catalog_plant_lilaeopsis_novae_zelandiae_name,
                R.string.catalog_plant_marsilea_hirsuta_name,
                R.string.catalog_plant_marsilea_crenata_name,
                R.string.catalog_plant_marsilea_minuta_name,
                R.string.catalog_plant_ranunculus_inundatus_name,
                R.string.catalog_plant_eriocaulon_cinereum_name,
                R.string.catalog_plant_sagittaria_subulata_name,
                R.string.catalog_plant_blyxa_japonica_name
            )
        )
        addAll(
            plants(
                R.string.catalog_plant_category_ground_cover_title,
                R.string.catalog_plant_hemianthus_callitrichoides_cuba_name,
                R.string.catalog_plant_micranthemum_tweediei_monte_carlo_name,
                R.string.catalog_plant_glossostigma_elatinoides_name,
                R.string.catalog_plant_eleocharis_acicularis_name,
                R.string.catalog_plant_eleocharis_acicularis_mini_name,
                R.string.catalog_plant_eleocharis_parvula_name,
                R.string.catalog_plant_eleocharis_pusilla_name,
                R.string.catalog_plant_utricularia_graminifolia_name,
                R.string.catalog_plant_hydrocotyle_tripartita_japan_name,
                R.string.catalog_plant_marsilea_quadrifolia_name,
                R.string.catalog_plant_marsilea_crenata_name,
                R.string.catalog_plant_marsilea_hirsuta_name,
                R.string.catalog_plant_lilaeopsis_brasiliensis_name,
                R.string.catalog_plant_lilaeopsis_mauritiana_name,
                R.string.catalog_plant_riccia_fluitans_name
            )
        )
        addAll(
            plants(
                R.string.catalog_plant_category_middle_ground_title,
                R.string.catalog_plant_cryptocoryne_wendtii_green_name,
                R.string.catalog_plant_cryptocoryne_wendtii_brown_name,
                R.string.catalog_plant_cryptocoryne_wendtii_tropica_name,
                R.string.catalog_plant_cryptocoryne_wendtii_mi_oya_name,
                R.string.catalog_plant_cryptocoryne_beckettii_name,
                R.string.catalog_plant_cryptocoryne_undulata_name,
                R.string.catalog_plant_cryptocoryne_lutea_name,
                R.string.catalog_plant_cryptocoryne_albida_name,
                R.string.catalog_plant_cryptocoryne_balansae_name,
                R.string.catalog_plant_cryptocoryne_spiralis_name,
                R.string.catalog_plant_cryptocoryne_pontederiifolia_name,
                R.string.catalog_plant_cryptocoryne_crispatula_name,
                R.string.catalog_plant_lagenandra_meeboldii_red_name,
                R.string.catalog_plant_lagenandra_meeboldii_green_name,
                R.string.catalog_plant_hygrophila_corymbosa_compact_name,
                R.string.catalog_plant_hygrophila_polysperma_rosanervig_name,
                R.string.catalog_plant_pogostemon_erectus_name,
                R.string.catalog_plant_rotala_indica_bonsai_name,
                R.string.catalog_plant_rotala_rotundifolia_green_name,
                R.string.catalog_plant_bacopa_compacta_name,
                R.string.catalog_plant_bacopa_caroliniana_name,
                R.string.catalog_plant_bacopa_monnieri_name,
                R.string.catalog_plant_ludwigia_palustris_super_red_name,
                R.string.catalog_plant_ludwigia_repens_name,
                R.string.catalog_plant_nymphoides_hydrophylla_taiwan_name,
                R.string.catalog_plant_hydrocotyle_leucocephala_name,
                R.string.catalog_plant_hydrocotyle_verticillata_name
            )
        )
        addAll(
            plants(
                R.string.catalog_plant_category_background_title,
                R.string.catalog_plant_vallisneria_spiralis_name,
                R.string.catalog_plant_vallisneria_americana_name,
                R.string.catalog_plant_vallisneria_nana_name,
                R.string.catalog_plant_vallisneria_gigantea_name,
                R.string.catalog_plant_egeria_densa_name,
                R.string.catalog_plant_elodea_canadensis_name,
                R.string.catalog_plant_limnophila_sessiliflora_name,
                R.string.catalog_plant_limnophila_aromatica_name,
                R.string.catalog_plant_limnophila_hippuridoides_name,
                R.string.catalog_plant_cabomba_caroliniana_name,
                R.string.catalog_plant_cabomba_aquatica_name,
                R.string.catalog_plant_myriophyllum_mattogrossense_name,
                R.string.catalog_plant_myriophyllum_aquaticum_name,
                R.string.catalog_plant_myriophyllum_tuberculatum_name,
                R.string.catalog_plant_rotala_rotundifolia_name,
                R.string.catalog_plant_rotala_rotundifolia_h_ra_name,
                R.string.catalog_plant_rotala_rotundifolia_orange_juice_name,
                R.string.catalog_plant_rotala_wallichii_name,
                R.string.catalog_plant_rotala_macrandra_name,
                R.string.catalog_plant_rotala_macrandra_green_name,
                R.string.catalog_plant_rotala_macrandra_mini_butterfly_name,
                R.string.catalog_plant_ludwigia_arcuata_name,
                R.string.catalog_plant_ludwigia_glandulosa_name,
                R.string.catalog_plant_ludwigia_inclinata_name,
                R.string.catalog_plant_ludwigia_inclinata_var_verticillata_cuba_name,
                R.string.catalog_plant_ludwigia_inclinata_var_verticillata_pantanal_name,
                R.string.catalog_plant_hygrophila_polysperma_name,
                R.string.catalog_plant_hygrophila_corymbosa_name,
                R.string.catalog_plant_hygrophila_difformis_name,
                R.string.catalog_plant_heteranthera_zosterifolia_name,
                R.string.catalog_plant_pogostemon_stellatus_name,
                R.string.catalog_plant_pogostemon_stellatus_octopus_name,
                R.string.catalog_plant_proserpinaca_palustris_name,
                R.string.catalog_plant_alternanthera_reineckii_name,
                R.string.catalog_plant_alternanthera_reineckii_rosanervig_name,
                R.string.catalog_plant_alternanthera_reineckii_red_ruby_name,
                R.string.catalog_plant_ammannia_gracilis_name,
                R.string.catalog_plant_ammannia_senegalensis_name,
                R.string.catalog_plant_bacopa_australis_name,
                R.string.catalog_plant_bacopa_caroliniana_name,
                R.string.catalog_plant_bacopa_monnieri_name,
                R.string.catalog_plant_didiplis_diandra_name,
                R.string.catalog_plant_mayaca_fluviatilis_name,
                R.string.catalog_plant_eichhornia_diversifolia_name,
                R.string.catalog_plant_aponogeton_crispus_name,
                R.string.catalog_plant_aponogeton_ulvaceus_name,
                R.string.catalog_plant_crinum_calamistratum_name,
                R.string.catalog_plant_crinum_natans_name,
                R.string.catalog_plant_echinodorus_bleheri_name,
                R.string.catalog_plant_echinodorus_grisebachii_name,
                R.string.catalog_plant_echinodorus_ozelot_name,
                R.string.catalog_plant_echinodorus_red_diamond_name,
                R.string.catalog_plant_echinodorus_reni_name
            )
        )
        addAll(
            plants(
                R.string.catalog_plant_category_mosses_title,
                R.string.catalog_plant_taxiphyllum_barbieri_name,
                R.string.catalog_plant_taxiphyllum_sp_flame_moss_name,
                R.string.catalog_plant_taxiphyllum_sp_spiky_moss_name,
                R.string.catalog_plant_taxiphyllum_sp_peacock_moss_name,
                R.string.catalog_plant_vesicularia_montagnei_christmas_moss_name,
                R.string.catalog_plant_vesicularia_ferriei_weeping_moss_name,
                R.string.catalog_plant_vesicularia_dubyana_name,
                R.string.catalog_plant_vesicularia_sp_mini_christmas_moss_name,
                R.string.catalog_plant_fissidens_fontanus_name,
                R.string.catalog_plant_fissidens_nobilis_name,
                R.string.catalog_plant_riccardia_chamedryfolia_name,
                R.string.catalog_plant_riccardia_graeffei_name,
                R.string.catalog_plant_leptodictyum_riparium_name,
                R.string.catalog_plant_amblystegium_serpens_name,
                R.string.catalog_plant_monosolenium_tenerum_name,
                R.string.catalog_plant_lomariopsis_lineata_name,
                R.string.catalog_plant_cladophora_aegagropila_name
            )
        )
        addAll(
            plants(
                R.string.catalog_plant_category_floating_plants_title,
                R.string.catalog_plant_salvinia_natans_name,
                R.string.catalog_plant_salvinia_minima_name,
                R.string.catalog_plant_salvinia_auriculata_name,
                R.string.catalog_plant_phyllanthus_fluitans_name,
                R.string.catalog_plant_limnobium_laevigatum_name,
                R.string.catalog_plant_pistia_stratiotes_name,
                R.string.catalog_plant_lemna_minor_name,
                R.string.catalog_plant_spirodela_polyrhiza_name,
                R.string.catalog_plant_azolla_caroliniana_name,
                R.string.catalog_plant_azolla_filiculoides_name,
                R.string.catalog_plant_riccia_fluitans_name,
                R.string.catalog_plant_ceratopteris_cornuta_name,
                R.string.catalog_plant_ceratopteris_thalictroides_name,
                R.string.catalog_plant_hygroryza_aristata_name,
                R.string.catalog_plant_hydrocharis_morsus_ranae_name
            )
        )
        addAll(
            plants(
                R.string.catalog_plant_category_rare_plants_title,
                R.string.catalog_plant_eriocaulon_sp_vietnam_name,
                R.string.catalog_plant_eriocaulon_sp_japan_needle_leaf_name,
                R.string.catalog_plant_eriocaulon_setaceum_name,
                R.string.catalog_plant_syngonanthus_macrocaulon_name,
                R.string.catalog_plant_syngonanthus_sp_belem_name,
                R.string.catalog_plant_tonina_fluviatilis_name,
                R.string.catalog_plant_tonina_sp_belem_name,
                R.string.catalog_plant_tonina_sp_manaus_name,
                R.string.catalog_plant_ludwigia_sp_white_name,
                R.string.catalog_plant_ludwigia_inclinata_var_verticillata_white_name,
                R.string.catalog_plant_rotala_ramosior_florida_name,
                R.string.catalog_plant_rotala_sp_pearl_name,
                R.string.catalog_plant_rotala_sp_blood_red_name,
                R.string.catalog_plant_rotala_sp_vietnam_h_ra_name,
                R.string.catalog_plant_ammannia_pedicellata_golden_name,
                R.string.catalog_plant_ammannia_praetermissa_name,
                R.string.catalog_plant_pogostemon_yatabeanus_name,
                R.string.catalog_plant_pogostemon_kimberley_name,
                R.string.catalog_plant_pogostemon_deccanensis_name,
                R.string.catalog_plant_aponogeton_madagascariensis_name,
                R.string.catalog_plant_aponogeton_boivinianus_name,
                R.string.catalog_plant_barclaya_longifolia_name,
                R.string.catalog_plant_barclaya_longifolia_red_name,
                R.string.catalog_plant_nymphaea_lotus_red_name,
                R.string.catalog_plant_nymphaea_micrantha_name,
                R.string.catalog_plant_nymphaea_stellata_name,
                R.string.catalog_plant_crinum_thaianum_name,
                R.string.catalog_plant_lagenandra_keralensis_name,
                R.string.catalog_plant_lagenandra_thwaitesii_name,
                R.string.catalog_plant_cryptocoryne_flamingo_name,
                R.string.catalog_plant_cryptocoryne_nurii_name,
                R.string.catalog_plant_cryptocoryne_cordata_rosanervig_name,
                R.string.catalog_plant_bucephalandra_sp_black_pearl_name,
                R.string.catalog_plant_bucephalandra_sp_dark_skeleton_king_name,
                R.string.catalog_plant_bucephalandra_sp_godzilla_name,
                R.string.catalog_plant_bucephalandra_sp_silver_powder_name
            )
        )
    }

    fun resolve(context: Context): List<AquariumPlant> {
        return definitions.map { definition -> definition.resolve(context) }
    }
}
