package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

private const val AQUARIUM_PRODUCT_COUNT = 291
private const val AQUARIUM_ID_PADDING = 4
private const val AQUARIUM_ID_PREFIX = "aquarium_"

private enum class AquariumHardwareType(
    val keywordRes: List<Int>
) {
    TANK(listOf(R.string.catalog_keyword_tank, R.string.catalog_keyword_glass)),
    MAT(listOf(R.string.catalog_keyword_mat, R.string.catalog_keyword_pad)),
    THERMOMETER(listOf(R.string.catalog_keyword_thermometer, R.string.catalog_keyword_thermo, R.string.catalog_keyword_temperature)),
    LILY_PIPE_INFLOW(listOf(R.string.catalog_keyword_lily_pipe, R.string.catalog_keyword_inflow, R.string.catalog_keyword_inlet, R.string.catalog_keyword_intake, R.string.catalog_keyword_pipe)),
    LILY_PIPE_OUTFLOW(listOf(R.string.catalog_keyword_lily_pipe, R.string.catalog_keyword_outflow, R.string.catalog_keyword_outlet, R.string.catalog_keyword_return, R.string.catalog_keyword_pipe)),
    LILY_PIPE_SET(listOf(R.string.catalog_keyword_lily_pipe, R.string.catalog_keyword_inflow, R.string.catalog_keyword_outflow, R.string.catalog_keyword_inlet, R.string.catalog_keyword_outlet, R.string.catalog_keyword_pipe, R.string.catalog_keyword_set)),
    PIPE_ACCESSORY(listOf(R.string.catalog_keyword_pipe, R.string.catalog_keyword_accessory)),
    TANK_COVER(listOf(R.string.catalog_keyword_cover, R.string.catalog_keyword_lid, R.string.catalog_keyword_glass)),
    TANK_COVER_ACCESSORY(listOf(R.string.catalog_keyword_cover, R.string.catalog_keyword_lid, R.string.catalog_keyword_clip, R.string.catalog_keyword_accessory)),
    SCISSORS(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_scissors, R.string.catalog_keyword_tool)),
    TWEEZERS(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_tweezers, R.string.catalog_keyword_pinsettes, R.string.catalog_keyword_tool)),
    LEVELER(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_leveler, R.string.catalog_keyword_flattener, R.string.catalog_keyword_tool)),
    TOOL_SET(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_tool, R.string.catalog_keyword_set)),
    CLEANING_TOOL(listOf(R.string.catalog_keyword_cleaning, R.string.catalog_keyword_cleaner, R.string.catalog_keyword_scraper, R.string.catalog_keyword_tool)),
    PIPE_CLEANING_TOOL(listOf(R.string.catalog_keyword_pipe, R.string.catalog_keyword_cleaning, R.string.catalog_keyword_brush, R.string.catalog_keyword_tool)),
    WATER_TESTER(listOf(R.string.catalog_keyword_water, R.string.catalog_keyword_tester, R.string.catalog_keyword_tds, R.string.catalog_keyword_temperature))
}

private data class AquariumCatalogResource(
    val brandRes: Int,
    val nameRes: Int,
    val hardwareType: AquariumHardwareType,
    val extraKeywordRes: List<Int>
)

private val aquariumCatalogResources = listOf(
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0001_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0002_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0003_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0004_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0005_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0006_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0007_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0008_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0009_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0010_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0011_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0012_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0013_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0014_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0015_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0016_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0017_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0018_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0019_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0020_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0021_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0022_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0023_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0024_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0025_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0026_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0027_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0028_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0029_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0030_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0031_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0032_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0033_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0034_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0035_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0036_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0037_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0038_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0039_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0040_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0041_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0042_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0043_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0044_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0045_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0046_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0047_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0048_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0049_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0050_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0051_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0052_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0053_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0054_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0055_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0056_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0057_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0058_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0059_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0060_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0061_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0062_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0063_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0064_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0065_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0066_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0067_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0068_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0069_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0070_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0071_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0072_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0073_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0074_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0075_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0076_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0077_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0078_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0079_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0080_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0081_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0082_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0083_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0084_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0085_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0086_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0087_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0088_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0089_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0090_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0091_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0092_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0093_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0094_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0095_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0096_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0097_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0098_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0099_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_nano
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0100_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_nano
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0101_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0102_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0103_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0104_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0105_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0106_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0107_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0108_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0109_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0110_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0111_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0112_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0113_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0114_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0115_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0116_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0117_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0118_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0119_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0120_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0121_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0122_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0123_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0124_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0125_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0126_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0127_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0128_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0129_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0130_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0131_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0132_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0133_name,
        AquariumHardwareType.LEVELER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0134_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0135_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0136_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0137_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0138_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0139_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0140_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0141_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0142_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0143_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0144_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0145_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0146_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0147_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0148_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0149_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0150_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0151_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0152_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0153_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0154_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0155_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0156_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0157_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0158_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0159_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0160_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0161_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0162_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0163_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0164_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0165_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0166_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0167_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0168_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0169_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0170_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0171_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0172_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0173_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0174_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0175_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0176_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0177_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0178_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0179_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0180_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0181_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0182_name,
        AquariumHardwareType.TOOL_SET
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0183_name,
        AquariumHardwareType.TOOL_SET
    ),
    aquariumResource(
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0184_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        R.string.catalog_brand_oase,
        R.string.catalog_material_aquarium_0185_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_oase,
        R.string.catalog_material_aquarium_0186_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_oase,
        R.string.catalog_material_aquarium_0187_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0188_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0189_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0190_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0191_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0192_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0193_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0194_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0195_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0196_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0197_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0198_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0199_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0200_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0201_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0202_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0203_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0204_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0205_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0206_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0207_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0208_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0209_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0210_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0211_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0212_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0213_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0214_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0215_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0216_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0217_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0218_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0219_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0220_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0221_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0222_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0223_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0224_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0225_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0226_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0227_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0228_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0229_name,
        AquariumHardwareType.LEVELER
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0230_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0231_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0232_name,
        AquariumHardwareType.PIPE_CLEANING_TOOL
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0233_name,
        AquariumHardwareType.PIPE_CLEANING_TOOL
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0234_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0235_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0236_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0237_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0238_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0239_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0240_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0241_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0242_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0243_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0244_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0245_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0246_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0247_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0248_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0249_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0250_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0251_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0252_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0253_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0254_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0255_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0256_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0257_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0258_name,
        AquariumHardwareType.WATER_TESTER
    ),
    aquariumResource(
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0259_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0260_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0261_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0262_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0263_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0264_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0265_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0266_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0267_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0268_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0269_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0270_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0271_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0272_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0273_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0274_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0275_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0276_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0277_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0278_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0279_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0280_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0281_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0282_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0283_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0284_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0285_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0286_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0287_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0288_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        R.string.catalog_brand_tropica,
        R.string.catalog_material_aquarium_0289_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        R.string.catalog_brand_tropica,
        R.string.catalog_material_aquarium_0290_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        R.string.catalog_brand_tropica,
        R.string.catalog_material_aquarium_0291_name,
        AquariumHardwareType.SCISSORS
    )
)

object AquariumCatalog {

    val definitions: List<AquariumMaterialDefinition> =
        aquariumCatalogResources.mapIndexed { index, resource ->
            AquariumMaterialDefinition(
                id = aquariumProductId(index + 1),
                brandRes = resource.brandRes,
                nameRes = resource.nameRes,
                categoryKey = MaterialCategoryKey.AQUARIUM,
                categoryTitleRes = R.string.catalog_material_category_aquarium_title,
                keywordRes = (
                    listOf(R.string.catalog_keyword_aquarium) +
                        resource.hardwareType.keywordRes +
                        resource.extraKeywordRes
                    ).distinct()
            )
        }

    init {
        check(definitions.size == AQUARIUM_PRODUCT_COUNT)
        check(definitions.map(AquariumMaterialDefinition::id).distinct().size == definitions.size)
    }
}

private fun aquariumResource(
    brandRes: Int,
    nameRes: Int,
    hardwareType: AquariumHardwareType,
    vararg extraKeywordRes: Int
): AquariumCatalogResource = AquariumCatalogResource(
    brandRes = brandRes,
    nameRes = nameRes,
    hardwareType = hardwareType,
    extraKeywordRes = extraKeywordRes.toList()
)

private fun aquariumProductId(index: Int): String {
    require(index in 1..AQUARIUM_PRODUCT_COUNT)
    return AQUARIUM_ID_PREFIX + index.toString().padStart(AQUARIUM_ID_PADDING, '0')
}
