package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

private const val AQUARIUM_PRODUCT_COUNT = 291
private enum class AquariumHardwareType(
    val keywordRes: List<Int>
) {
    TANK(listOf(R.string.catalog_keyword_tank, R.string.catalog_keyword_glass)),
    MAT(listOf(R.string.catalog_keyword_mat, R.string.catalog_keyword_pad)),
    THERMOMETER(listOf(R.string.catalog_keyword_thermometer, R.string.catalog_keyword_thermo, R.string.catalog_keyword_temperature)),
    LILY_PIPE_INFLOW(listOf(R.string.catalog_keyword_lily_pipe, R.string.catalog_keyword_inflow, R.string.catalog_keyword_inlet, R.string.catalog_keyword_intake, R.string.catalog_keyword_pipe)),
    LILY_PIPE_OUTFLOW(listOf(R.string.catalog_keyword_lily_pipe, R.string.catalog_keyword_outflow, R.string.catalog_keyword_outlet, R.string.catalog_keyword_return, R.string.catalog_keyword_pipe)),
    LILY_PIPE_SET(listOf(R.string.catalog_keyword_lily_pipe, R.string.catalog_keyword_inflow, R.string.catalog_keyword_outflow, R.string.catalog_keyword_inlet, R.string.catalog_keyword_outlet, R.string.catalog_keyword_pipe, R.string.catalog_keyword_set)),
    PIPE_ACCESSORY(listOf(R.string.catalog_keyword_pipe, R.string.catalog_keyword_accessory)),
    TANK_COVER(listOf(R.string.catalog_keyword_cover, R.string.catalog_keyword_lid, R.string.catalog_keyword_glass)),
    TANK_COVER_ACCESSORY(listOf(R.string.catalog_keyword_cover, R.string.catalog_keyword_lid, R.string.catalog_keyword_clip, R.string.catalog_keyword_accessory)),
    SCISSORS(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_scissors, R.string.catalog_keyword_tool)),
    TWEEZERS(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_tweezers, R.string.catalog_keyword_pinsettes, R.string.catalog_keyword_tool)),
    LEVELER(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_leveler, R.string.catalog_keyword_flattener, R.string.catalog_keyword_tool)),
    TOOL_SET(listOf(R.string.catalog_keyword_aquascaping, R.string.catalog_keyword_tool, R.string.catalog_keyword_set)),
    CLEANING_TOOL(listOf(R.string.catalog_keyword_cleaning, R.string.catalog_keyword_cleaner, R.string.catalog_keyword_scraper, R.string.catalog_keyword_tool)),
    PIPE_CLEANING_TOOL(listOf(R.string.catalog_keyword_pipe, R.string.catalog_keyword_cleaning, R.string.catalog_keyword_brush, R.string.catalog_keyword_tool)),
    WATER_TESTER(listOf(R.string.catalog_keyword_water, R.string.catalog_keyword_tester, R.string.catalog_keyword_tds, R.string.catalog_keyword_temperature))
}

private data class AquariumCatalogResource(
    val id: String,
    val brandRes: Int,
    val nameRes: Int,
    val hardwareType: AquariumHardwareType,
    val extraKeywordRes: List<Int>
)

private val aquariumCatalogResources = listOf(
    aquariumResource(
        "aquarium_ada_cube_garden_w15",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0001_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w20",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0002_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w30",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0003_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w30_slim",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0004_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w36",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0005_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w45_shallow",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0006_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w45",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0007_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w60_shallow",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0008_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w60",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0009_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w60_tall",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0010_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w60_deep",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0011_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w90",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0012_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w120",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0013_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w150",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0014_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_w180",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0015_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_mist_w60",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0016_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_30_x_18",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0017_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_36_x_22",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0018_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_30_x_30",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0019_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_45_x_30",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0020_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_60_x_30",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0021_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_60_x_45",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0022_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_90_x_45",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0023_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_120_x_50",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0024_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_150_x_60",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0025_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_garden_mat_180_x_60",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0026_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_ada_na_thermometer_j_j_05wh",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0027_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_ada_na_thermometer_j_j_06wh",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0028_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_ada_na_thermometer_j_j_10wh",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0029_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_ada_na_thermometer_j_j_12wh",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0030_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_ada_na_thermometer_j_j_15wh",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0031_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_p_p_1_dia_10",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0032_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_p_p_2_dia_13",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0033_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_p_p_4_dia_13",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0034_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_p_p_6_dia_13",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0035_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_p_p_6_dia_17",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0036_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_new_lily_pipe_v_v_3_dia_13",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0037_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_ada_new_lily_pipe_v_v_5_dia_13",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0038_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_ada_new_lily_pipe_v_v_7_dia_17",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0039_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_ada_new_lily_pipe_v_v_7_dia_20",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0040_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_spin_spin_p_1",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0041_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_spin_spin_p_2",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0042_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_mini_mini_p_1",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0043_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_mini_mini_p_2",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0044_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_mini_mini_v_1",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0045_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_ada_lily_pipe_mini_mini_v_2",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0046_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_ada_pinsettes_series_s",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0047_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_ada_pinsettes_series_m",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0048_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_ada_pinsettes_series_l",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0049_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_ada_pinsettes_series_xl",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0050_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_ada_pro_pinsettes_grip_type_s",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0051_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_ada_pro_pinsettes_grip_type_m",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0052_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_ada_pro_pinsettes_grip_type_l",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0053_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_spring_straight",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0054_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_spring_curve",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0055_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_short_straight",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0056_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_short_curve",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0057_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_wave",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0058_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_s_straight",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0059_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_s_curve",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0060_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_m",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0061_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_l",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0062_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_pro_scissors_nude",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0063_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_hook_5_mm",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0064_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_hook_6_mm",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0065_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_hook_8_mm",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0066_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_hook_10_mm",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0067_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        "aquarium_ada_cube_garden_hook_12_mm",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0068_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w20_x_d20_x_h20",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0069_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w30_x_d30_x_h30",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0070_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w30_x_d18_x_h24",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0071_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w36_x_d22_x_h26",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0072_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w45_x_d27_x_h30",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0073_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w45_x_d30_x_h45",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0074_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w60_x_d30_x_h36_45",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0075_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w60_x_d45_x_h36",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0076_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w90_x_d45_x_h45_60",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0077_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w120_x_d50_x_h50",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0078_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w150_x_d60_x_h60",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0079_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_ada_clear_glass_cover_w180_x_d60_x_h60",
        R.string.catalog_brand_ada,
        R.string.catalog_material_aquarium_0080_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_45u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0081_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_60u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0082_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_75p",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0083_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_90p",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0084_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_90u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0085_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_120p",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0086_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_120m",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0087_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_120u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0088_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_150u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0089_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_180u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0090_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_16c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0091_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_20c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0092_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_25c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0093_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_30c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0094_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_40c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0095_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_45c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0096_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_50c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0097_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_60c",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0098_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_3n",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0099_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_nano
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_5n",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0100_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_nano
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_45l",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0101_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_60l",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0102_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_90b",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0103_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_90l",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0104_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_long
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_16s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0105_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_5s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0106_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_25s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0107_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_45s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0108_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_60s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0109_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_75s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0110_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_90s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0111_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_90ss",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0112_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_120s",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0113_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_120ss",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0114_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_60cs",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0115_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_16t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0116_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_20t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0117_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_3t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0118_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_5t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0119_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_25t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0120_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_30t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0121_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_45t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0122_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_rimless_glass_aquarium_60t",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0123_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_tall
    ),
    aquariumResource(
        "aquarium_uns_limited_edition_blue_rimless_glass_aquarium_5n",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0124_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_uns_limited_edition_blue_rimless_glass_aquarium_45u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0125_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_uns_limited_edition_blue_rimless_glass_aquarium_60u",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0126_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_uns_limited_edition_blue_rimless_glass_aquarium_90l",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0127_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_uns_straight_scissors",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0128_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_uns_stainless_spring_scissors",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0129_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_uns_straight_tweezer",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0130_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_uns_curved_tweezer",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0131_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_uns_pro_straight_tweezer",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0132_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_uns_flattener",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0133_name,
        AquariumHardwareType.LEVELER
    ),
    aquariumResource(
        "aquarium_uns_glass_lids",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0134_name,
        AquariumHardwareType.TANK_COVER
    ),
    aquariumResource(
        "aquarium_uns_clear_clips",
        R.string.catalog_aquarium_brand_uns,
        R.string.catalog_material_aquarium_0135_name,
        AquariumHardwareType.TANK_COVER_ACCESSORY
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_60h",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0136_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_60p_16_gal",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0137_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_100p",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0138_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_90p_44_gal",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0139_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_90p_55_gal",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0140_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_120p_72_2_gal",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0141_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_45p",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0142_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_75h",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0143_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_60p_23_gal",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0144_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_120p_78_4_gal",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0145_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_rimless_low_iron_aquarium_tank_150p",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0146_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_standard_tank_180",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0147_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_landen_cube_rimless_aquarium_20c",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0148_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_landen_cube_rimless_aquarium_30c",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0149_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_landen_cube_rimless_aquarium_40c",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0150_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_landen_cube_rimless_aquarium_36c",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0151_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_landen_cube_rimless_aquarium_50c",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0152_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_landen_cube_rimless_aquarium_60c",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0153_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_landen_shallow_rimless_aquarium_45s",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0154_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_landen_shallow_rimless_aquarium_60s",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0155_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_landen_shallow_rimless_aquarium_75s",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0156_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_landen_shallow_rimless_aquarium_90s",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0157_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_landen_304_stainless_steel_lily_pipes_with_clamps_6_mm",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0158_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_landen_304_stainless_steel_lily_pipes_with_clamps_12_mm",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0159_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_landen_304_stainless_steel_lily_pipes_with_clamps_16_mm",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0160_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_6_mm_white_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0161_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_6_mm_clear_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0162_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_8_mm_white_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0163_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_8_mm_clear_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0164_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_10_mm_white_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0165_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_10_mm_clear_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0166_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_12_mm_white_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0167_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_landen_aquarium_thermometer_for_rimless_tank_12_mm_clear_background",
        R.string.catalog_aquarium_brand_landen,
        R.string.catalog_material_aquarium_0168_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_dennerle_nano_cube_10_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0169_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_cube_20_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0170_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_cube_30_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0171_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_cube_60_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0172_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_25_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0173_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_35_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0174_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_60_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0175_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_white_glass_25_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0176_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_white_glass_35_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0177_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_white_glass_55_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0178_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_white_glass_60_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0179_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_tank_white_glass_70_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0180_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_nano_cube_white_glass_30_l",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0181_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dennerle_scapers_tools_set",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0182_name,
        AquariumHardwareType.TOOL_SET
    ),
    aquariumResource(
        "aquarium_dennerle_aquarium_care_set",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0183_name,
        AquariumHardwareType.TOOL_SET
    ),
    aquariumResource(
        "aquarium_dennerle_nano_gravel_cleaner",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_aquarium_0184_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        "aquarium_oase_scaperline_aquarium_60",
        R.string.catalog_brand_oase,
        R.string.catalog_material_aquarium_0185_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_oase_scaperline_aquarium_90",
        R.string.catalog_brand_oase,
        R.string.catalog_material_aquarium_0186_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_oase_scaperline_aquarium_100",
        R.string.catalog_brand_oase,
        R.string.catalog_material_aquarium_0187_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_eheim_cleartank_73",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0188_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_eheim_cleartank_175",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0189_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_eheim_cleartank_200",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0190_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_eheim_cleartank_300",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_aquarium_0191_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_27",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0192_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_42",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0193_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_64",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0194_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_91",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0195_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_cube
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_28",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0196_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_38",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0197_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_80",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0198_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_standard
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_17_shallow",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0199_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_blau_cubic_aquascaping_44_shallow",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0200_name,
        AquariumHardwareType.TANK,
        R.string.catalog_keyword_shallow
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_experience_62",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0201_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_experience_92",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0202_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_experience_122",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0203_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_experience_152",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0204_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_super_aquascaping_92",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0205_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_super_aquascaping_122",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0206_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_experience_shallow_62",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0207_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_experience_shallow_92",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0208_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_gran_cubic_experience_shallow_122",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0209_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_blau_glass_jet_outflow_10_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0210_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_jet_outflow_13_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0211_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_ball_outflow_13_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0212_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_ball_outflow_17_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0213_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_trumpet_outflow_13_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0214_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_trumpet_outflow_17_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0215_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_nano_inflow_10_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0216_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_nano_inflow_13_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0217_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_inflow_13_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0218_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_blau_glass_inflow_17_mm",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0219_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_blau_nano_stainless_inflow_and_outflow_set",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0220_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_blau_straight_scissors",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0221_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_blau_curved_scissors",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0222_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_blau_spring_nano_scissors",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0223_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_blau_curved_spring_nano_scissors",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0224_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_blau_angled_nano_scissors",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0225_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_blau_double_curved_scissors",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0226_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_blau_straight_tweezers",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0227_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_blau_curved_tweezers",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0228_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_blau_sand_flattener_steel",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0229_name,
        AquariumHardwareType.LEVELER
    ),
    aquariumResource(
        "aquarium_blau_stainless_scraper",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0230_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        "aquarium_blau_algae_scraper",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0231_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        "aquarium_blau_flexible_inox_brush_short",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0232_name,
        AquariumHardwareType.PIPE_CLEANING_TOOL
    ),
    aquariumResource(
        "aquarium_blau_flexible_inox_brush_long",
        R.string.catalog_aquarium_brand_blau_aquaristic,
        R.string.catalog_material_aquarium_0233_name,
        AquariumHardwareType.PIPE_CLEANING_TOOL
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_15_x_15_x_25_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0234_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_15_x_15_x_30_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0235_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_20_x_20_x_9_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0236_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_20_x_20_x_20_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0237_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_30_x_18_x_12_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0238_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_20_x_20_x_35_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0239_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_20_x_20_x_30_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0240_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_dooa_neo_glass_air_30_x_30_x_45_cm",
        R.string.catalog_aquarium_brand_dooa,
        R.string.catalog_material_aquarium_0241_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_chihiros_metal_inflow_outflow_set_metal_jet_pipe_set_s",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0242_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_chihiros_metal_inflow_outflow_set_metal_jet_pipe_set_m",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0243_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_chihiros_metal_inflow_outflow_set_metal_jet_pipe_set_ml",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0244_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_chihiros_metal_inflow_outflow_pro_metal_jet_pipe_pro_m_pro",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0245_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_chihiros_metal_inflow_outflow_pro_metal_jet_pipe_pro_l_pro",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0246_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_chihiros_u_type_glass_inflow_glass_jet_pipe",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0247_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_chihiros_lily_type_glass_outflow_glass_jet_pipe",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0248_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_chihiros_poppy_type_glass_outflow_glass_jet_pipe",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0249_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_chihiros_metal_pipe_clamp",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0250_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        "aquarium_chihiros_water_plants_scissors_straight_21_cm",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0251_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_chihiros_water_plants_scissors_curved_21_cm",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0252_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_chihiros_water_plants_scissors_wavy_21_cm",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0253_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_chihiros_45cm_straight_and_curved_tweezer_45_cm_straight",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0254_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_chihiros_45cm_straight_and_curved_tweezer_45_cm_curved",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0255_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_chihiros_straight_tweezers_pro",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0256_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_chihiros_straight_tweezers_max",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0257_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_chihiros_digital_tds_pen_temperature_tester_pen",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_aquarium_0258_name,
        AquariumHardwareType.WATER_TESTER
    ),
    aquariumResource(
        "aquarium_aquario_neo_flow_premium",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0259_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_aquario_neo_flow_normal",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0260_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_aquario_neo_holder",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0261_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        "aquarium_aquario_neo_inlet",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0262_name,
        AquariumHardwareType.LILY_PIPE_INFLOW
    ),
    aquariumResource(
        "aquarium_aquario_neo_outlet",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0263_name,
        AquariumHardwareType.LILY_PIPE_OUTFLOW
    ),
    aquariumResource(
        "aquarium_aquario_neo_flexible_pipe",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0264_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        "aquarium_aquario_neo_clip",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_aquarium_0265_name,
        AquariumHardwareType.PIPE_ACCESSORY
    ),
    aquariumResource(
        "aquarium_aquael_opti_tank_60",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0266_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_aquael_opti_tank_80",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0267_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_aquael_opti_tank_100",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0268_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_aquael_opti_tank_rounded_20",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0269_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_aquael_opti_tank_rounded_30",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0270_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_aquael_opti_tank_rounded_70",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0271_name,
        AquariumHardwareType.TANK
    ),
    aquariumResource(
        "aquarium_aquael_aquarium_mat_41_x_25_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0272_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_aquael_aquarium_mat_60_x_30_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0273_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_aquael_aquarium_mat_80_x_35_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0274_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_aquael_aquarium_mat_100_x_40_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0275_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_aquael_aquarium_mat_120_x_40_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0276_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_aquael_aquarium_mat_150_x_50_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0277_name,
        AquariumHardwareType.MAT
    ),
    aquariumResource(
        "aquarium_aquael_t9_thermometer",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0278_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_aquael_glass_thermometer_15_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0279_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_aquael_glass_thermometer_6_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0280_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_aquael_hanging_thermometer_no_6",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0281_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_aquael_hanging_thermometer_no_10",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0282_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_aquael_thermometer_link",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0283_name,
        AquariumHardwareType.THERMOMETER
    ),
    aquariumResource(
        "aquarium_aquael_straight_tweezers_27_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0284_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_aquael_curved_tweezers_27_cm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0285_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_aquael_scissors",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0286_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_aquael_glass_pipes_set_for_external_filters_12_16mm",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0287_name,
        AquariumHardwareType.LILY_PIPE_SET
    ),
    aquariumResource(
        "aquarium_aquael_gravel_cleaner",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_aquarium_0288_name,
        AquariumHardwareType.CLEANING_TOOL
    ),
    aquariumResource(
        "aquarium_tropica_scissors",
        R.string.catalog_brand_tropica,
        R.string.catalog_material_aquarium_0289_name,
        AquariumHardwareType.SCISSORS
    ),
    aquariumResource(
        "aquarium_tropica_tweezers",
        R.string.catalog_brand_tropica,
        R.string.catalog_material_aquarium_0290_name,
        AquariumHardwareType.TWEEZERS
    ),
    aquariumResource(
        "aquarium_tropica_spring_scissors",
        R.string.catalog_brand_tropica,
        R.string.catalog_material_aquarium_0291_name,
        AquariumHardwareType.SCISSORS
    )
)

object AquariumCatalog {

    val definitions: List<AquariumMaterialDefinition> =
        aquariumCatalogResources.mapIndexed { index, resource ->
            AquariumMaterialDefinition(
                id = resource.id,
                brandRes = resource.brandRes,
                nameRes = resource.nameRes,
                categoryKey = MaterialCategoryKey.AQUARIUM,
                categoryTitleRes = R.string.catalog_material_category_aquarium_title,
                keywordRes = (
                    listOf(R.string.catalog_keyword_aquarium) +
                        resource.hardwareType.keywordRes +
                        resource.extraKeywordRes
                    ).distinct()
            )
        }

    init {
        check(definitions.size == AQUARIUM_PRODUCT_COUNT)
        check(definitions.map(AquariumMaterialDefinition::id).distinct().size == definitions.size)
        check(definitions.all { definition -> definition.id.startsWith("aquarium_") })
    }
}

private fun aquariumResource(
    id: String,
    brandRes: Int,
    nameRes: Int,
    hardwareType: AquariumHardwareType,
    vararg extraKeywordRes: Int
): AquariumCatalogResource = AquariumCatalogResource(
    id = id,
    brandRes = brandRes,
    nameRes = nameRes,
    hardwareType = hardwareType,
    extraKeywordRes = extraKeywordRes.toList()
)
