package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

private const val CO2_PRODUCT_COUNT = 135

private enum class Co2HardwareType(
    val keywordRes: List<Int>
) {
    REGULATOR(
        listOf(
            R.string.catalog_keyword_regulator,
            R.string.catalog_keyword_co2_regulator,
            R.string.catalog_keyword_pressure_regulator,
            R.string.catalog_keyword_pressure_reducer
        )
    ),
    SYSTEM(
        listOf(
            R.string.catalog_keyword_system,
            R.string.catalog_keyword_set,
            R.string.catalog_keyword_co2_system,
            R.string.catalog_keyword_co2_set
        )
    ),
    BIO_SYSTEM(
        listOf(
            R.string.catalog_keyword_system,
            R.string.catalog_keyword_set,
            R.string.catalog_keyword_co2_system,
            R.string.catalog_keyword_co2_set,
            R.string.catalog_keyword_bio,
            R.string.catalog_keyword_bio_co2,
            R.string.catalog_keyword_fermentation
        )
    ),
    GENERATOR_SYSTEM(
        listOf(
            R.string.catalog_keyword_generator,
            R.string.catalog_keyword_system,
            R.string.catalog_keyword_set,
            R.string.catalog_keyword_kit,
            R.string.catalog_keyword_co2_system,
            R.string.catalog_keyword_co2_set
        )
    )
}

private data class Co2CatalogResource(
    val id: String,
    val brandRes: Int,
    val nameRes: Int,
    val hardwareType: Co2HardwareType,
    val extraKeywordRes: List<Int>
)

private val co2CatalogResources = listOf(
    co2Resource(
        "co2_chihiros_regulator_pro_limited_edition",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_co2_0001_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_chihiros_regulator_mate",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_co2_0002_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_chihiros_mini_regulator_kit",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_co2_0003_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_kit
    ),
    co2Resource(
        "co2_chihiros_regulator_with_needle_valve",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_co2_0004_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_needle_valve
    ),
    co2Resource(
        "co2_jbl_proflora_starter_bio_set",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0005_name,
        Co2HardwareType.BIO_SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_basic_bio_set",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0006_name,
        Co2HardwareType.BIO_SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_advanced_bio_set",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0007_name,
        Co2HardwareType.BIO_SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_basic_set_m",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0008_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_basic_set_u",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0009_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_basic_set_v",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0010_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_advanced_set_m",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0011_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_advanced_set_u",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0012_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_advanced_set_v",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0013_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_professional_set_m",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0014_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_professional_set_u",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0015_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_professional_set_v",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0016_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_regulator_basic",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0017_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_jbl_proflora_regulator_advanced",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0018_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_jbl_proflora_regulator_professional",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0019_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_dennerle_carbo_soda_m200",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0020_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_start_m200",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0021_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_start_e200",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0022_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_start_e200_special_edition",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0023_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_start_flex200",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0024_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_start_flex200_special_edition",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0025_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_power_m400",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0026_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_power_e400",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0027_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_power_e400_special_edition",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0028_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_power_flex400",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0029_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_night_m400",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0030_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_night_flex400",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0031_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_dennerle_pressure_reducer_start",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0032_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_dennerle_pressure_reducer_power",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0033_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_dennerle_carbo_bio_start_60",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0034_name,
        Co2HardwareType.BIO_SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_bio_start_80",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0035_name,
        Co2HardwareType.BIO_SYSTEM
    ),
    co2Resource(
        "co2_dennerle_carbo_bio_style_120",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_co2_0036_name,
        Co2HardwareType.BIO_SYSTEM
    ),
    co2Resource(
        "co2_eheim_co2set200",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0037_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_eheim_co2set400",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0038_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_eheim_co2set600",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0039_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_eheim_co2set400_incl_night_shut_off",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0040_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_night_shutoff
    ),
    co2Resource(
        "co2_eheim_co2set600_incl_night_shut_off",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0041_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_night_shutoff
    ),
    co2Resource(
        "co2_eheim_co2set400_without_bottle",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0042_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_bottle
    ),
    co2Resource(
        "co2_eheim_co2set600_without_bottle",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0043_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_bottle
    ),
    co2Resource(
        "co2_eheim_co2set400_without_bottle_incl_night_shut_off",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0044_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_night_shutoff,
        R.string.catalog_keyword_bottle
    ),
    co2Resource(
        "co2_eheim_co2set600_without_bottle_incl_night_shut_off",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0045_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_night_shutoff,
        R.string.catalog_keyword_bottle
    ),
    co2Resource(
        "co2_eheim_pressure_reducer",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_co2_0046_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_co2art_pro_se_series_aquarium_dual_stage_regulator_with_integrated_solenoid",
        R.string.catalog_co2_brand_co2art,
        R.string.catalog_material_co2_0047_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_solenoid_valve,
        R.string.catalog_keyword_dual_stage
    ),
    co2Resource(
        "co2_co2art_pro_elite_series_v2_aquarium_dual_stage_regulator",
        R.string.catalog_co2_brand_co2art,
        R.string.catalog_material_co2_0048_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_dual_stage
    ),
    co2Resource(
        "co2_co2art_pro_se_series_complete_aquarium_system_with_in_tank_flux_diffuser",
        R.string.catalog_co2_brand_co2art,
        R.string.catalog_material_co2_0049_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_diffuser
    ),
    co2Resource(
        "co2_co2art_pro_se_series_complete_aquarium_system_with_new_inline_diffuser",
        R.string.catalog_co2_brand_co2art,
        R.string.catalog_material_co2_0050_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_inline,
        R.string.catalog_keyword_diffuser
    ),
    co2Resource(
        "co2_co2art_new_pro_elite_series_v2_complete_aquarium_system_with_in_tank_flux_diffuser",
        R.string.catalog_co2_brand_co2art,
        R.string.catalog_material_co2_0051_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_diffuser
    ),
    co2Resource(
        "co2_co2art_new_pro_elite_series_v2_complete_aquarium_system_with_new_inline_diffuser",
        R.string.catalog_co2_brand_co2art,
        R.string.catalog_material_co2_0052_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_inline,
        R.string.catalog_keyword_diffuser
    ),
    co2Resource(
        "co2_green_aqua_system_s_max_60l",
        R.string.catalog_brand_green_aqua,
        R.string.catalog_material_co2_0053_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_green_aqua_system_m_max_120l",
        R.string.catalog_brand_green_aqua,
        R.string.catalog_material_co2_0054_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_green_aqua_system_l_max_240l",
        R.string.catalog_brand_green_aqua,
        R.string.catalog_material_co2_0055_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_green_aqua_system_with_reactor_13mm_12_16mm",
        R.string.catalog_brand_green_aqua,
        R.string.catalog_material_co2_0056_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_reactor
    ),
    co2Resource(
        "co2_green_aqua_system_with_reactor_17mm_16_22mm",
        R.string.catalog_brand_green_aqua,
        R.string.catalog_material_co2_0057_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_reactor
    ),
    co2Resource(
        "co2_tropica_system_nano",
        R.string.catalog_brand_tropica,
        R.string.catalog_material_co2_0058_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_tropica_system_bio",
        R.string.catalog_brand_tropica,
        R.string.catalog_material_co2_0059_name,
        Co2HardwareType.BIO_SYSTEM
    ),
    co2Resource(
        "co2_tropica_system_nano_regulator",
        R.string.catalog_brand_tropica,
        R.string.catalog_material_co2_0060_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aquario_neo_system",
        R.string.catalog_brand_aquario,
        R.string.catalog_material_co2_0061_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_fluval_bio_pro_low_pressure_system_up_to_33_us_gal_125_l",
        R.string.catalog_co2_brand_fluval,
        R.string.catalog_material_co2_0062_name,
        Co2HardwareType.BIO_SYSTEM,
        R.string.catalog_keyword_low_pressure
    ),
    co2Resource(
        "co2_fluval_bio_pro_low_pressure_system_up_to_66_us_gal_250_l",
        R.string.catalog_co2_brand_fluval,
        R.string.catalog_material_co2_0063_name,
        Co2HardwareType.BIO_SYSTEM,
        R.string.catalog_keyword_low_pressure
    ),
    co2Resource(
        "co2_fluval_bio_pro_low_pressure_system_up_to_132_us_gal_500_l",
        R.string.catalog_co2_brand_fluval,
        R.string.catalog_material_co2_0064_name,
        Co2HardwareType.BIO_SYSTEM,
        R.string.catalog_keyword_low_pressure
    ),
    co2Resource(
        "co2_fluval_pressurized_kit_45_g_up_to_30_us_gal_115_l",
        R.string.catalog_co2_brand_fluval,
        R.string.catalog_material_co2_0065_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_pressurized,
        R.string.catalog_keyword_kit
    ),
    co2Resource(
        "co2_fzone_studio_desktop_aquarium_system_with_45g_disposable_cartridge",
        R.string.catalog_co2_brand_fzone,
        R.string.catalog_material_co2_0066_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_cartridge,
        R.string.catalog_keyword_disposable
    ),
    co2Resource(
        "co2_fzone_studio_aquarium_system_mini_regulator_kit",
        R.string.catalog_co2_brand_fzone,
        R.string.catalog_material_co2_0067_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_kit
    ),
    co2Resource(
        "co2_fzone_studio_desktop_aquarium_complete_kit_with_solenoid_80g_cartridge",
        R.string.catalog_co2_brand_fzone,
        R.string.catalog_material_co2_0068_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_solenoid_valve,
        R.string.catalog_keyword_cartridge,
        R.string.catalog_keyword_kit
    ),
    co2Resource(
        "co2_fzone_aquatic_studio_pro_series_regulator_fz_2020pro",
        R.string.catalog_co2_brand_fzone,
        R.string.catalog_material_co2_0069_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_fzone_aquatic_studio_single_stage_regulator_cga320_w21_8_fz_0100",
        R.string.catalog_co2_brand_fzone,
        R.string.catalog_material_co2_0070_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_single_stage
    ),
    co2Resource(
        "co2_fzone_aquatic_studio_mini_dual_stage_regulator_fz_1011",
        R.string.catalog_co2_brand_fzone,
        R.string.catalog_material_co2_0071_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_dual_stage
    ),
    co2Resource(
        "co2_ada_advanced_system_forest",
        R.string.catalog_brand_ada,
        R.string.catalog_material_co2_0072_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ada_system_74_ya_ver_2",
        R.string.catalog_brand_ada,
        R.string.catalog_material_co2_0073_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ada_system_74_sa",
        R.string.catalog_brand_ada,
        R.string.catalog_material_co2_0074_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ada_system_74_da",
        R.string.catalog_brand_ada,
        R.string.catalog_material_co2_0075_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ada_attache_regulator",
        R.string.catalog_brand_ada,
        R.string.catalog_material_co2_0076_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_ada_speed_regulator",
        R.string.catalog_brand_ada,
        R.string.catalog_material_co2_0077_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_sera_flore_fertilization_system",
        R.string.catalog_co2_brand_sera,
        R.string.catalog_material_co2_0078_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_fertilization
    ),
    co2Resource(
        "co2_sera_flore_pressure_reducer",
        R.string.catalog_co2_brand_sera,
        R.string.catalog_material_co2_0079_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_sera_start",
        R.string.catalog_co2_brand_sera,
        R.string.catalog_material_co2_0080_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_up_aqua_a_171_omnibus_regulator",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0081_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_up_aqua_a_126_regulator_double_gauge",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0082_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_gauge
    ),
    co2Resource(
        "co2_up_aqua_a_164_regulator_working_pressure_adjustable",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0083_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_up_aqua_a_168_omnibus_regulator",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0084_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_up_aqua_a_153_regulator_two_gauge",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0085_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_gauge
    ),
    co2Resource(
        "co2_up_aqua_a_165_regulator_working_pressure_adjustable",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0086_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_up_aqua_a_152_regulator_one_gauge",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0087_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_gauge
    ),
    co2Resource(
        "co2_up_aqua_a_100_regulator_double_gauge",
        R.string.catalog_co2_brand_up_aqua,
        R.string.catalog_material_co2_0088_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_gauge
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_basic_m1",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0089_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_basic_e2",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0090_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_basic_m2",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0091_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_e",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0092_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m1",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0093_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m2",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0094_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m3",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0095_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m1_plus",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0096_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_doppelkammer_druckminderer_profi_m",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0097_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_doppelkammer_druckminderer_profi_m_plus",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0098_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m1_bz",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0099_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_mv_bz",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0100_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m2rv_mv",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0101_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m2rv_mv_led",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0102_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m3rv_mv",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0103_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_m3rv_mv_led",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0104_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_mv",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0105_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_druckminderer_profi_mvr",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0106_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_noa_doppelkammer_druckminderer_profi_mm_plus",
        R.string.catalog_co2_brand_aqua_noa,
        R.string.catalog_material_co2_0107_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_aqua_medic_regular_mini",
        R.string.catalog_co2_brand_aqua_medic,
        R.string.catalog_material_co2_0108_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_oxyturbo_major_2_pressure_regulator_with_solenoid_and_needle_valve",
        R.string.catalog_co2_brand_oxyturbo,
        R.string.catalog_material_co2_0109_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_needle_valve,
        R.string.catalog_keyword_solenoid_valve
    ),
    co2Resource(
        "co2_oxyturbo_major_2_pressure_regulator_with_needle_valve",
        R.string.catalog_co2_brand_oxyturbo,
        R.string.catalog_material_co2_0110_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_needle_valve
    ),
    co2Resource(
        "co2_ista_set_1_lt_professional",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0111_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ista_tup_1lt_advanced",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0112_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_cylinder
    ),
    co2Resource(
        "co2_ista_tup_1lt_basic_set",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0113_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_cylinder
    ),
    co2Resource(
        "co2_ista_tup_1l_plus_regulator_plus_diffusor_plus_damla_sayaci",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0114_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_diffuser,
        R.string.catalog_keyword_cylinder,
        R.string.catalog_keyword_bubble_counter
    ),
    co2Resource(
        "co2_ista_tup_1lt_plus_digital_control_plus_diffusor_plus_indicator",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0115_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_diffuser,
        R.string.catalog_keyword_cylinder,
        R.string.catalog_keyword_digital_control
    ),
    co2Resource(
        "co2_ista_karbondioksit_set_0_50lt_advance",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0116_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ista_karbondioksit_set_0_50lt_basic",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0117_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ista_karbondioksit_basic_set_95gr",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0118_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ista_karbondioksit_easy_set_95gr",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0119_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ista_karbondioksit_set_45gr",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0120_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ista_set_16gr",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0121_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_ista_regulator",
        R.string.catalog_brand_ista,
        R.string.catalog_material_co2_0122_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_mufan_w21_8_regulatoru",
        R.string.catalog_co2_brand_mufan,
        R.string.catalog_material_co2_0123_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_mufan_w21_8_selenoid_valfli_regulatoru",
        R.string.catalog_co2_brand_mufan,
        R.string.catalog_material_co2_0124_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_solenoid_valve
    ),
    co2Resource(
        "co2_mufan_damla_sayacli_cift_gostergeli_regulatoru",
        R.string.catalog_co2_brand_mufan,
        R.string.catalog_material_co2_0125_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_gauge
    ),
    co2Resource(
        "co2_creaqua_diox_profesyonel_selenoid_valfli_damla_sayacli_regulatoru",
        R.string.catalog_co2_brand_creaqua,
        R.string.catalog_material_co2_0126_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_solenoid_valve
    ),
    co2Resource(
        "co2_zrdr_selenoid_valfli_profesyonel_regulatoru",
        R.string.catalog_co2_brand_zrdr,
        R.string.catalog_material_co2_0127_name,
        Co2HardwareType.REGULATOR,
        R.string.catalog_keyword_solenoid_valve
    ),
    co2Resource(
        "co2_chihiros_regulator_pro",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_co2_0128_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_chihiros_regulator",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_co2_0129_name,
        Co2HardwareType.REGULATOR
    ),
    co2Resource(
        "co2_chihiros_generator_kit_2_5l",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_co2_0130_name,
        Co2HardwareType.GENERATOR_SYSTEM,
        R.string.catalog_keyword_kit
    ),
    co2Resource(
        "co2_jbl_proflora_m501_500gr_tup_seti",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0131_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_cylinder
    ),
    co2Resource(
        "co2_jbl_proflora_m502_500gr_tup_seti",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0132_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_cylinder
    ),
    co2Resource(
        "co2_jbl_proflora_m503_500gr_tup_seti",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0133_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_cylinder
    ),
    co2Resource(
        "co2_jbl_proflora_m1003_set",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0134_name,
        Co2HardwareType.SYSTEM
    ),
    co2Resource(
        "co2_jbl_proflora_m2003_2000gr_tup_seti",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_co2_0135_name,
        Co2HardwareType.SYSTEM,
        R.string.catalog_keyword_cylinder
    )
)

object Co2Catalog {

    val definitions: List<AquariumMaterialDefinition> =
        co2CatalogResources.map { resource ->
            AquariumMaterialDefinition(
                id = resource.id,
                brandRes = resource.brandRes,
                nameRes = resource.nameRes,
                categoryKey = MaterialCategoryKey.CO2,
                categoryTitleRes = R.string.catalog_material_category_co2_title,
                keywordRes = (
                    listOf(
                        R.string.catalog_keyword_co2,
                        R.string.catalog_keyword_carbon_dioxide
                    ) +
                        resource.hardwareType.keywordRes +
                        resource.extraKeywordRes
                    ).distinct()
            )
        }

    init {
        check(definitions.size == CO2_PRODUCT_COUNT)
        check(definitions.map(AquariumMaterialDefinition::id).distinct().size == definitions.size)
        check(definitions.all { definition -> definition.id.startsWith("co2_") })
    }
}

private fun co2Resource(
    id: String,
    brandRes: Int,
    nameRes: Int,
    hardwareType: Co2HardwareType,
    vararg extraKeywordRes: Int
): Co2CatalogResource = Co2CatalogResource(
    id = id,
    brandRes = brandRes,
    nameRes = nameRes,
    hardwareType = hardwareType,
    extraKeywordRes = extraKeywordRes.toList()
)
