package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

private const val COOLER_PRODUCT_COUNT = 185
private const val COOLER_BRAND_COUNT = 44

private enum class CoolerHardwareType(
    val keywordRes: List<Int>
) {
    FAN(
        listOf(
            R.string.catalog_keyword_fan,
            R.string.catalog_cooler_keyword_cooling_fan
        )
    ),
    THERMOSTATIC_FAN(
        listOf(
            R.string.catalog_keyword_fan,
            R.string.catalog_cooler_keyword_cooling_fan,
            R.string.catalog_cooler_keyword_thermostat,
            R.string.catalog_cooler_keyword_digital
        )
    ),
    SMART_FAN(
        listOf(
            R.string.catalog_keyword_fan,
            R.string.catalog_cooler_keyword_cooling_fan,
            R.string.catalog_cooler_keyword_smart,
            R.string.catalog_cooler_keyword_bluetooth
        )
    ),
    CHILLER(
        listOf(
            R.string.catalog_cooler_keyword_chiller,
            R.string.catalog_cooler_keyword_water_chiller
        )
    ),
    HEATING_CHILLER(
        listOf(
            R.string.catalog_cooler_keyword_chiller,
            R.string.catalog_cooler_keyword_water_chiller,
            R.string.catalog_cooler_keyword_heating
        )
    ),
    THERMOELECTRIC_CHILLER(
        listOf(
            R.string.catalog_cooler_keyword_chiller,
            R.string.catalog_cooler_keyword_water_chiller,
            R.string.catalog_cooler_keyword_thermoelectric
        )
    ),
    INLINE_CHILLER(
        listOf(
            R.string.catalog_cooler_keyword_chiller,
            R.string.catalog_cooler_keyword_water_chiller,
            R.string.catalog_cooler_keyword_inline
        )
    ),
    DROP_IN_CHILLER(
        listOf(
            R.string.catalog_cooler_keyword_chiller,
            R.string.catalog_cooler_keyword_water_chiller,
            R.string.catalog_cooler_keyword_drop_in
        )
    )
}

private data class CoolerCatalogResource(
    val id: String,
    val brandRes: Int,
    val nameRes: Int,
    val hardwareType: CoolerHardwareType,
    val extraKeywordRes: List<Int>
)

private val coolerCatalogResources = listOf(
    coolerResource(
        "cooler_aqua_medic_arctic_breeze_2_pac",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0001_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_aqua_medic_arctic_breeze_4_pac",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0002_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_aqua_medic_arctic_breeze_6_pac",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0003_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_aqua_medic_titan_200",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0004_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aqua_medic_titan_600",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0005_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aqua_medic_titan_1600",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0006_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aqua_medic_titan_2200",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0007_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aqua_medic_titan_duo_300",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0008_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_aqua_medic_titan_duo_700",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0009_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_aqua_medic_titan_duo_1800",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0010_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_aqua_medic_titan_duo_2400",
        R.string.catalog_cooler_brand_aqua_medic,
        R.string.catalog_material_cooler_0011_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_aquael_nano_cool_mini_cooler_nano_cool",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_cooler_0012_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_mini
    ),
    coolerResource(
        "cooler_aquaeurousa_max_chill_1_10_hp",
        R.string.catalog_cooler_brand_aquaeurousa,
        R.string.catalog_material_cooler_0013_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquaeurousa_max_chill_1_4_hp",
        R.string.catalog_cooler_brand_aquaeurousa,
        R.string.catalog_material_cooler_0014_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquaeurousa_max_chill_1_2_hp",
        R.string.catalog_cooler_brand_aquaeurousa,
        R.string.catalog_material_cooler_0015_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquaeurousa_max_chill_1_hp",
        R.string.catalog_cooler_brand_aquaeurousa,
        R.string.catalog_material_cooler_0016_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquanature_arctic_chiller_aac_160",
        R.string.catalog_cooler_brand_aquanature,
        R.string.catalog_material_cooler_0017_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquanature_arctic_chiller_aac_300",
        R.string.catalog_cooler_brand_aquanature,
        R.string.catalog_material_cooler_0018_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquanature_arctic_chiller_aac_500",
        R.string.catalog_cooler_brand_aquanature,
        R.string.catalog_material_cooler_0019_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquanature_arctic_chiller_aac_1000",
        R.string.catalog_cooler_brand_aquanature,
        R.string.catalog_material_cooler_0020_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquania_termostatli_akvaryum_sogutucu_fan_sistemi_4_lu_set",
        R.string.catalog_cooler_brand_aquania,
        R.string.catalog_material_cooler_0021_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_thermostat
    ),
    coolerResource(
        "cooler_aquaperfekt_ap_power_fan_1",
        R.string.catalog_cooler_brand_aquaperfekt,
        R.string.catalog_material_cooler_0022_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_aquaperfekt_ap_power_fan_2",
        R.string.catalog_cooler_brand_aquaperfekt,
        R.string.catalog_material_cooler_0023_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_aquaperfekt_ap_power_fan_4",
        R.string.catalog_cooler_brand_aquaperfekt,
        R.string.catalog_material_cooler_0024_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_aquaperfekt_ap_power_fan_6",
        R.string.catalog_cooler_brand_aquaperfekt,
        R.string.catalog_material_cooler_0025_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_aquatic_nature_aqua_chill_100",
        R.string.catalog_cooler_brand_aquatic_nature,
        R.string.catalog_material_cooler_0026_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquatic_nature_aqua_chill_200",
        R.string.catalog_cooler_brand_aquatic_nature,
        R.string.catalog_material_cooler_0027_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_aquatic_nature_aqua_chill_400",
        R.string.catalog_cooler_brand_aquatic_nature,
        R.string.catalog_material_cooler_0028_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_armaturk_1_li_akvaryum_sogutucu_fan",
        R.string.catalog_cooler_brand_armaturk,
        R.string.catalog_material_cooler_0029_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_armaturk_2_li_akvaryum_sogutucu_fan",
        R.string.catalog_cooler_brand_armaturk,
        R.string.catalog_material_cooler_0030_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_armaturk_3_lu_akvaryum_sogutucu_fan",
        R.string.catalog_cooler_brand_armaturk,
        R.string.catalog_material_cooler_0031_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_armaturk_4_lu_akvaryum_sogutucu_fan",
        R.string.catalog_cooler_brand_armaturk,
        R.string.catalog_material_cooler_0032_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_atakan_petshop_termostatli_akvaryum_sogutucu_fan_1_li_set",
        R.string.catalog_cooler_brand_atakan_petshop,
        R.string.catalog_material_cooler_0033_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_atakan_petshop_termostatli_akvaryum_sogutucu_fan_2_li_set",
        R.string.catalog_cooler_brand_atakan_petshop,
        R.string.catalog_material_cooler_0034_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_atakan_petshop_termostatli_akvaryum_sogutucu_fan_5_li_set",
        R.string.catalog_cooler_brand_atakan_petshop,
        R.string.catalog_material_cooler_0035_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_atakan_petshop_termostatli_akvaryum_sogutucu_fan_6_li_set",
        R.string.catalog_cooler_brand_atakan_petshop,
        R.string.catalog_material_cooler_0036_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_belltech_japan_windforce_wf_1200",
        R.string.catalog_cooler_brand_belltech_japan,
        R.string.catalog_material_cooler_0037_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_betta_marketim_sogutucu_fan_uclu_termostatsiz_100_150_l",
        R.string.catalog_cooler_brand_betta_marketim,
        R.string.catalog_material_cooler_0038_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_thermostat
    ),
    coolerResource(
        "cooler_betta_marketim_sogutucu_fan_dortlu_termostatsiz_150_200_l",
        R.string.catalog_cooler_brand_betta_marketim,
        R.string.catalog_material_cooler_0039_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_thermostat
    ),
    coolerResource(
        "cooler_betta_marketim_sogutucu_fan_besli_termostatsiz_200_250_l",
        R.string.catalog_cooler_brand_betta_marketim,
        R.string.catalog_material_cooler_0040_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_thermostat
    ),
    coolerResource(
        "cooler_betta_marketim_sogutucu_fan_altili_termostatsiz_250_300_l",
        R.string.catalog_cooler_brand_betta_marketim,
        R.string.catalog_material_cooler_0041_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_thermostat
    ),
    coolerResource(
        "cooler_blau_aquaristic_aquaventilator_2",
        R.string.catalog_cooler_brand_blau_aquaristic,
        R.string.catalog_material_cooler_0042_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_blau_aquaristic_aquaventilator_4",
        R.string.catalog_cooler_brand_blau_aquaristic,
        R.string.catalog_material_cooler_0043_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_blau_aquaristic_aquaventilator_6",
        R.string.catalog_cooler_brand_blau_aquaristic,
        R.string.catalog_material_cooler_0044_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_blau_aquaristic_nano_ventilator_plus_black",
        R.string.catalog_cooler_brand_blau_aquaristic,
        R.string.catalog_material_cooler_0045_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_blau_aquaristic_nano_ventilator_plus_white",
        R.string.catalog_cooler_brand_blau_aquaristic,
        R.string.catalog_material_cooler_0046_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_blue_marine_chiller_100",
        R.string.catalog_cooler_brand_blue_marine,
        R.string.catalog_material_cooler_0047_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_blue_marine_chiller_200",
        R.string.catalog_cooler_brand_blue_marine,
        R.string.catalog_material_cooler_0048_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_blue_marine_chiller_400",
        R.string.catalog_cooler_brand_blue_marine,
        R.string.catalog_material_cooler_0049_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_blue_marine_chiller_800",
        R.string.catalog_cooler_brand_blue_marine,
        R.string.catalog_material_cooler_0050_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_blue_marine_chiller_1200",
        R.string.catalog_cooler_brand_blue_marine,
        R.string.catalog_material_cooler_0051_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_blue_marine_chiller_2000",
        R.string.catalog_cooler_brand_blue_marine,
        R.string.catalog_material_cooler_0052_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_boyu_fs_55_cooling_fan",
        R.string.catalog_cooler_brand_boyu,
        R.string.catalog_material_cooler_0053_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_boyu_fs_120_cooling_fan",
        R.string.catalog_cooler_brand_boyu,
        R.string.catalog_material_cooler_0054_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_boyu_fs_120a_cooling_fan",
        R.string.catalog_cooler_brand_boyu,
        R.string.catalog_material_cooler_0055_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_boyu_fs_602_cooling_fan",
        R.string.catalog_cooler_brand_boyu,
        R.string.catalog_material_cooler_0056_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_boyu_fs_603_cooling_fan",
        R.string.catalog_cooler_brand_boyu,
        R.string.catalog_material_cooler_0057_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_boyu_fs_604_cooling_fan",
        R.string.catalog_cooler_brand_boyu,
        R.string.catalog_material_cooler_0058_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_boyu_fs_606_cooling_fan",
        R.string.catalog_cooler_brand_boyu,
        R.string.catalog_material_cooler_0059_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_chihiros_cooling_fan_bluetooth_edition_bluetooth_kontrollu_sogutma_fani",
        R.string.catalog_brand_chihiros,
        R.string.catalog_material_cooler_0060_name,
        CoolerHardwareType.SMART_FAN
    ),
    coolerResource(
        "cooler_collar_afan",
        R.string.catalog_cooler_brand_collar,
        R.string.catalog_material_cooler_0061_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_collar_afan_pro",
        R.string.catalog_cooler_brand_collar,
        R.string.catalog_material_cooler_0062_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_d_d_the_aquarium_solution_dc300_aquarium_chiller",
        R.string.catalog_cooler_brand_d_d_the_aquarium_solution,
        R.string.catalog_material_cooler_0063_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_d_d_the_aquarium_solution_dc750_aquarium_chiller",
        R.string.catalog_cooler_brand_d_d_the_aquarium_solution,
        R.string.catalog_material_cooler_0064_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_d_d_the_aquarium_solution_dc2200_aquarium_chiller",
        R.string.catalog_cooler_brand_d_d_the_aquarium_solution,
        R.string.catalog_material_cooler_0065_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_d_d_the_aquarium_solution_dc4000_aquarium_chiller",
        R.string.catalog_cooler_brand_d_d_the_aquarium_solution,
        R.string.catalog_material_cooler_0066_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_dymax_windy_w_4",
        R.string.catalog_cooler_brand_dymax,
        R.string.catalog_material_cooler_0067_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_dymax_windy_w_7",
        R.string.catalog_cooler_brand_dymax,
        R.string.catalog_material_cooler_0068_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_dymax_vortex_w_5",
        R.string.catalog_cooler_brand_dymax,
        R.string.catalog_material_cooler_0069_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_dymax_vortex_w_8",
        R.string.catalog_cooler_brand_dymax,
        R.string.catalog_material_cooler_0070_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_eheim_climacontrol_plus_s",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_cooler_0071_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_eheim_climacontrol_plus_m",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_cooler_0072_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_eheim_climacontrol_plus_l",
        R.string.catalog_brand_eheim,
        R.string.catalog_material_cooler_0073_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_2_black",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0074_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_2_white",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0075_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_3_black",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0076_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_3_white",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0077_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_4_black",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0078_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_4_white",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0079_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_5_black",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0080_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_5_white",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0081_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_6_black",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0082_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ghl_propellerbreeze_3_6_white",
        R.string.catalog_cooler_brand_ghl,
        R.string.catalog_material_cooler_0083_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_grotech_cool_breeze_2",
        R.string.catalog_cooler_brand_grotech,
        R.string.catalog_material_cooler_0084_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_grotech_cool_breeze_4",
        R.string.catalog_cooler_brand_grotech,
        R.string.catalog_material_cooler_0085_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_grotech_cool_breeze_6",
        R.string.catalog_cooler_brand_grotech,
        R.string.catalog_material_cooler_0086_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_grotech_cool_breeze_8",
        R.string.catalog_cooler_brand_grotech,
        R.string.catalog_material_cooler_0087_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_had_tekli_sogutucu_fan_50_l_otomatik_termostatli_dijital",
        R.string.catalog_cooler_brand_had,
        R.string.catalog_material_cooler_0088_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_had_ikili_sogutucu_fan_100_l_otomatik_termostatli_dijital",
        R.string.catalog_cooler_brand_had,
        R.string.catalog_material_cooler_0089_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_had_uclu_sogutucu_fan_150_l_otomatik_termostatli_dijital",
        R.string.catalog_cooler_brand_had,
        R.string.catalog_material_cooler_0090_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_had_dortlu_sogutucu_fan_200_l_otomatik_termostatli_dijital",
        R.string.catalog_cooler_brand_had,
        R.string.catalog_material_cooler_0091_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_had_besli_sogutucu_fan_250_l_otomatik_termostatli_dijital",
        R.string.catalog_cooler_brand_had,
        R.string.catalog_material_cooler_0092_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_had_altili_sogutucu_fan_300_l_otomatik_termostatli_dijital",
        R.string.catalog_cooler_brand_had,
        R.string.catalog_material_cooler_0093_name,
        CoolerHardwareType.THERMOSTATIC_FAN
    ),
    coolerResource(
        "cooler_hailea_hk_150a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0094_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hk_300a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0095_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hk_500a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0096_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hk_1000a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0097_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hc_100a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0098_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hc_150a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0099_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hc_300a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0100_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hc_500a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0101_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hc_1000a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0102_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hc_2200bh",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0103_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hs_66a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0104_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_hailea_hs_90a",
        R.string.catalog_cooler_brand_hailea,
        R.string.catalog_material_cooler_0105_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_haquoss_wind_1_fan",
        R.string.catalog_cooler_brand_haquoss,
        R.string.catalog_material_cooler_0106_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_haquoss_typhoon_2_fans",
        R.string.catalog_cooler_brand_haquoss,
        R.string.catalog_material_cooler_0107_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_haquoss_tornado_4_fans",
        R.string.catalog_cooler_brand_haquoss,
        R.string.catalog_material_cooler_0108_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_hobby_aqua_cooler_v2",
        R.string.catalog_cooler_brand_hobby,
        R.string.catalog_material_cooler_0109_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_hobby_aqua_cooler_v4",
        R.string.catalog_cooler_brand_hobby,
        R.string.catalog_material_cooler_0110_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_hobby_aqua_cooler_v6",
        R.string.catalog_cooler_brand_hobby,
        R.string.catalog_material_cooler_0111_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_hygger_hg051_1fan",
        R.string.catalog_cooler_brand_hygger,
        R.string.catalog_material_cooler_0112_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_hygger_hg051_2fan",
        R.string.catalog_cooler_brand_hygger,
        R.string.catalog_material_cooler_0113_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_hygger_hg051_3fan",
        R.string.catalog_cooler_brand_hygger,
        R.string.catalog_material_cooler_0114_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_hygger_hg140_aquarium_cooling_fan",
        R.string.catalog_cooler_brand_hygger,
        R.string.catalog_material_cooler_0115_name,
        CoolerHardwareType.SMART_FAN
    ),
    coolerResource(
        "cooler_ista_energy_saving_arrayed_cooling_fan_single_i_c816",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0116_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ista_energy_saving_arrayed_cooling_fan_twin_i_c817",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0117_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ista_energy_saving_arrayed_cooling_fan_triple_i_c818",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0118_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ista_energy_saving_arrayed_cooling_fan_four_i_c819",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0119_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ista_energy_saving_arrayed_cooling_fan_five_i_c831",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0120_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ista_energy_saving_arrayed_cooling_fan_six_i_c832",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0121_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ista_hanging_type_cooling_fan_i_104",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0122_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_ista_mini_usb_cooling_fan",
        R.string.catalog_brand_ista,
        R.string.catalog_material_cooler_0123_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_usb,
        R.string.catalog_cooler_keyword_mini
    ),
    coolerResource(
        "cooler_jbj_nano_arctica_1_15_hp",
        R.string.catalog_cooler_brand_jbj,
        R.string.catalog_material_cooler_0124_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_jbj_arctica_1_10_hp",
        R.string.catalog_cooler_brand_jbj,
        R.string.catalog_material_cooler_0125_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_jbj_arctica_1_5_hp",
        R.string.catalog_cooler_brand_jbj,
        R.string.catalog_material_cooler_0126_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_jbj_arctica_1_4_hp",
        R.string.catalog_cooler_brand_jbj,
        R.string.catalog_material_cooler_0127_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_jbj_arctica_1_3_hp",
        R.string.catalog_cooler_brand_jbj,
        R.string.catalog_material_cooler_0128_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_jbj_commercial_arctica_1_2_hp",
        R.string.catalog_cooler_brand_jbj,
        R.string.catalog_material_cooler_0129_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_jbl_protemp_cooler_x200_gen_2",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_cooler_0130_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_jbl_protemp_cooler_x300_gen_2",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_cooler_0131_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_nova_tec_coolworks_iceprobe_water_chiller",
        R.string.catalog_cooler_brand_nova_tec_coolworks,
        R.string.catalog_material_cooler_0132_name,
        CoolerHardwareType.THERMOELECTRIC_CHILLER
    ),
    coolerResource(
        "cooler_reef_octopus_octo_3_inch_usb_smart_fan",
        R.string.catalog_cooler_brand_reef_octopus,
        R.string.catalog_material_cooler_0133_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_usb,
        R.string.catalog_cooler_keyword_smart
    ),
    coolerResource(
        "cooler_reef_octopus_octo_4_inch_usb_smart_fan",
        R.string.catalog_cooler_brand_reef_octopus,
        R.string.catalog_material_cooler_0134_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_usb,
        R.string.catalog_cooler_keyword_smart
    ),
    coolerResource(
        "cooler_resun_mini_200_chiller",
        R.string.catalog_cooler_brand_resun,
        R.string.catalog_material_cooler_0135_name,
        CoolerHardwareType.CHILLER,
        R.string.catalog_cooler_keyword_mini
    ),
    coolerResource(
        "cooler_resun_cl_280_chiller",
        R.string.catalog_cooler_brand_resun,
        R.string.catalog_material_cooler_0136_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_resun_cl_450_chiller",
        R.string.catalog_cooler_brand_resun,
        R.string.catalog_material_cooler_0137_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_resun_cl_650_chiller",
        R.string.catalog_cooler_brand_resun,
        R.string.catalog_material_cooler_0138_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_rs_sf331_akvaryum_sogutucu_fan_tekli",
        R.string.catalog_cooler_brand_rs,
        R.string.catalog_material_cooler_0139_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_rs_sf332_akvaryum_sogutucu_fan_tekli",
        R.string.catalog_cooler_brand_rs,
        R.string.catalog_material_cooler_0140_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_sea_side_aquatics_aquarium_cooling_fan_2_fan",
        R.string.catalog_cooler_brand_sea_side_aquatics,
        R.string.catalog_material_cooler_0141_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_sea_side_aquatics_aquarium_cooling_fan_4_fan",
        R.string.catalog_cooler_brand_sea_side_aquatics,
        R.string.catalog_material_cooler_0142_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_sea_side_aquatics_aquarium_cooling_fan_6_fan",
        R.string.catalog_cooler_brand_sea_side_aquatics,
        R.string.catalog_material_cooler_0143_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_sunsun_jf_001_cooling_fan",
        R.string.catalog_brand_sunsun,
        R.string.catalog_material_cooler_0144_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_sunsun_jf_002_cooling_fan",
        R.string.catalog_brand_sunsun,
        R.string.catalog_material_cooler_0145_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_teco_tk150",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0146_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk500",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0147_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk500h",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0148_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_teco_tk1000",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0149_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk1000h",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0150_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_teco_tk2000",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0151_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk2000h",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0152_name,
        CoolerHardwareType.HEATING_CHILLER
    ),
    coolerResource(
        "cooler_teco_tk2000l",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0153_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk3000",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0154_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk6000",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0155_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk9000",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0156_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk5k",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0157_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk8k",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0158_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_tk15k",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0159_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_teco_di_500",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0160_name,
        CoolerHardwareType.DROP_IN_CHILLER
    ),
    coolerResource(
        "cooler_teco_di_1000",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0161_name,
        CoolerHardwareType.DROP_IN_CHILLER
    ),
    coolerResource(
        "cooler_teco_di_2000",
        R.string.catalog_cooler_brand_teco,
        R.string.catalog_material_cooler_0162_name,
        CoolerHardwareType.DROP_IN_CHILLER
    ),
    coolerResource(
        "cooler_theiling_polar_250",
        R.string.catalog_cooler_brand_theiling,
        R.string.catalog_material_cooler_0163_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_theiling_polar_500",
        R.string.catalog_cooler_brand_theiling,
        R.string.catalog_material_cooler_0164_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_tmc_aquarium_cooling_fan_1_fan",
        R.string.catalog_cooler_brand_tmc,
        R.string.catalog_material_cooler_0165_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_tmc_aquarium_cooling_fan_2_fan",
        R.string.catalog_cooler_brand_tmc,
        R.string.catalog_material_cooler_0166_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_tmc_aquarium_cooling_fan_3_fan",
        R.string.catalog_cooler_brand_tmc,
        R.string.catalog_material_cooler_0167_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_tmc_aquarium_cooling_fan_5_fan",
        R.string.catalog_cooler_brand_tmc,
        R.string.catalog_material_cooler_0168_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_tradewind_1_4_hp_inline_aquarium_chiller",
        R.string.catalog_cooler_brand_tradewind,
        R.string.catalog_material_cooler_0169_name,
        CoolerHardwareType.INLINE_CHILLER
    ),
    coolerResource(
        "cooler_tradewind_1_4_hp_drop_in_aquarium_chiller",
        R.string.catalog_cooler_brand_tradewind,
        R.string.catalog_material_cooler_0170_name,
        CoolerHardwareType.DROP_IN_CHILLER
    ),
    coolerResource(
        "cooler_tradewind_1_3_hp_inline_aquarium_chiller",
        R.string.catalog_cooler_brand_tradewind,
        R.string.catalog_material_cooler_0171_name,
        CoolerHardwareType.INLINE_CHILLER
    ),
    coolerResource(
        "cooler_tradewind_1_3_hp_drop_in_aquarium_chiller",
        R.string.catalog_cooler_brand_tradewind,
        R.string.catalog_material_cooler_0172_name,
        CoolerHardwareType.DROP_IN_CHILLER
    ),
    coolerResource(
        "cooler_tradewind_compact_1_2_hp_inline_aquarium_chiller",
        R.string.catalog_cooler_brand_tradewind,
        R.string.catalog_material_cooler_0173_name,
        CoolerHardwareType.INLINE_CHILLER
    ),
    coolerResource(
        "cooler_tradewind_compact_1_2_hp_drop_in_aquarium_chiller",
        R.string.catalog_cooler_brand_tradewind,
        R.string.catalog_material_cooler_0174_name,
        CoolerHardwareType.DROP_IN_CHILLER
    ),
    coolerResource(
        "cooler_tunze_aquawind_7028_500",
        R.string.catalog_cooler_brand_tunze,
        R.string.catalog_material_cooler_0175_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_up_aqua_d_336_usb_mini_cooling_fan",
        R.string.catalog_cooler_brand_up_aqua,
        R.string.catalog_material_cooler_0176_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_usb,
        R.string.catalog_cooler_keyword_mini
    ),
    coolerResource(
        "cooler_up_aqua_g_050_b_cooling_fan",
        R.string.catalog_cooler_brand_up_aqua,
        R.string.catalog_material_cooler_0177_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_up_aqua_g_051_2_fan_cooling_fan",
        R.string.catalog_cooler_brand_up_aqua,
        R.string.catalog_material_cooler_0178_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_up_aqua_g_051_4_fan_cooling_fan",
        R.string.catalog_cooler_brand_up_aqua,
        R.string.catalog_material_cooler_0179_name,
        CoolerHardwareType.FAN
    ),
    coolerResource(
        "cooler_up_aqua_ca_cf_003_mini_cooling_fan_black",
        R.string.catalog_cooler_brand_up_aqua,
        R.string.catalog_material_cooler_0180_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_mini
    ),
    coolerResource(
        "cooler_up_aqua_ca_cf_003_mini_cooling_fan_white",
        R.string.catalog_cooler_brand_up_aqua,
        R.string.catalog_material_cooler_0181_name,
        CoolerHardwareType.FAN,
        R.string.catalog_cooler_keyword_mini
    ),
    coolerResource(
        "cooler_vevor_aquarium_chiller_52_gallon_1_10_hp",
        R.string.catalog_cooler_brand_vevor,
        R.string.catalog_material_cooler_0182_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_vevor_aquarium_chiller_110_gallon_1_3_hp",
        R.string.catalog_cooler_brand_vevor,
        R.string.catalog_material_cooler_0183_name,
        CoolerHardwareType.CHILLER
    ),
    coolerResource(
        "cooler_zensui_zr_mini",
        R.string.catalog_cooler_brand_zensui,
        R.string.catalog_material_cooler_0184_name,
        CoolerHardwareType.CHILLER,
        R.string.catalog_cooler_keyword_mini
    ),
    coolerResource(
        "cooler_zoo_med_aqua_cool_aquarium_cooling_fan",
        R.string.catalog_cooler_brand_zoo_med,
        R.string.catalog_material_cooler_0185_name,
        CoolerHardwareType.FAN
    )
)

object CoolerCatalog {

    val definitions: List<AquariumMaterialDefinition> =
        coolerCatalogResources.map { resource ->
            AquariumMaterialDefinition(
                id = resource.id,
                brandRes = resource.brandRes,
                nameRes = resource.nameRes,
                categoryKey = MaterialCategoryKey.COOLER,
                categoryTitleRes = R.string.catalog_material_category_cooler_title,
                keywordRes = (
                    listOf(
                        R.string.catalog_keyword_cooler,
                        R.string.catalog_cooler_keyword_aquarium_cooler,
                        R.string.catalog_keyword_temperature
                    ) +
                        resource.hardwareType.keywordRes +
                        resource.extraKeywordRes
                    ).distinct()
            )
        }

    init {
        check(definitions.size == COOLER_PRODUCT_COUNT)
        check(definitions.map(AquariumMaterialDefinition::id).distinct().size == definitions.size)
        check(definitions.all { definition -> definition.id.startsWith("cooler_") })
        check(coolerCatalogResources.map(CoolerCatalogResource::brandRes).distinct().size == COOLER_BRAND_COUNT)
    }
}

private fun coolerResource(
    id: String,
    brandRes: Int,
    nameRes: Int,
    hardwareType: CoolerHardwareType,
    vararg extraKeywordRes: Int
): CoolerCatalogResource = CoolerCatalogResource(
    id = id,
    brandRes = brandRes,
    nameRes = nameRes,
    hardwareType = hardwareType,
    extraKeywordRes = extraKeywordRes.toList()
)
