package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

private const val DOSING_PRODUCT_COUNT = 109
private const val DOSING_BRAND_COUNT = 35

private enum class DosingHardwareType(
    val keywordRes: List<Int>
) {
    PUMP(emptyList()),
    SYSTEM(
        listOf(
            R.string.catalog_dosing_keyword_dosing_system,
            R.string.catalog_dosing_keyword_dosing_station
        )
    ),
    EXTENSION(
        listOf(
            R.string.catalog_dosing_keyword_extension,
            R.string.catalog_dosing_keyword_slave,
            R.string.catalog_dosing_keyword_add_on
        )
    ),
    PERISTALTIC(
        listOf(
            R.string.catalog_dosing_keyword_peristaltic,
            R.string.catalog_dosing_keyword_peristaltic_pump
        )
    ),
    CONTINUOUS_DUTY(
        listOf(
            R.string.catalog_dosing_keyword_peristaltic,
            R.string.catalog_dosing_keyword_peristaltic_pump,
            R.string.catalog_dosing_keyword_continuous_duty
        )
    ),
    STEPPER(
        listOf(
            R.string.catalog_dosing_keyword_stepper
        )
    )
}

private data class DosingCatalogResource(
    val id: String,
    val brandRes: Int,
    val nameRes: Int,
    val hardwareType: DosingHardwareType,
    val extraKeywordRes: List<Int>
)

private val dosingCatalogResources = listOf(
    dosingResource(
        "dosing_aqua_medic_reefdoser_evo_1",
        R.string.catalog_dosing_brand_aqua_medic,
        R.string.catalog_material_dosing_0001_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0001
    ),
    dosingResource(
        "dosing_aqua_medic_reefdoser_evo_4",
        R.string.catalog_dosing_brand_aqua_medic,
        R.string.catalog_material_dosing_0002_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0002
    ),
    dosingResource(
        "dosing_aqua_medic_reefdoser_evo_5",
        R.string.catalog_dosing_brand_aqua_medic,
        R.string.catalog_material_dosing_0003_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0003
    ),
    dosingResource(
        "dosing_aqua_nova_nmdp_4",
        R.string.catalog_dosing_brand_aqua_nova,
        R.string.catalog_material_dosing_0004_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0004
    ),
    dosingResource(
        "dosing_aqua_nova_nmdp_5",
        R.string.catalog_dosing_brand_aqua_nova,
        R.string.catalog_material_dosing_0005_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0005
    ),
    dosingResource(
        "dosing_aqua_nova_nxdp_4",
        R.string.catalog_dosing_brand_aqua_nova,
        R.string.catalog_material_dosing_0006_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0006
    ),
    dosingResource(
        "dosing_aqua_nova_nxdp_6",
        R.string.catalog_dosing_brand_aqua_nova,
        R.string.catalog_material_dosing_0007_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0007
    ),
    dosingResource(
        "dosing_aqua_trend_samudra_doserx_5_channel",
        R.string.catalog_dosing_brand_aqua_trend,
        R.string.catalog_material_dosing_0008_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0008,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_aqua_trend_samudra_doserxs_3_channel",
        R.string.catalog_dosing_brand_aqua_trend,
        R.string.catalog_material_dosing_0009_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0009,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_aquatronica_acq450_dosing_pump_3_head",
        R.string.catalog_dosing_brand_aquatronica,
        R.string.catalog_material_dosing_0010_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0010,
        R.string.catalog_dosing_keyword_multi_head
    ),
    dosingResource(
        "dosing_aquavitro_sentia_doser_primary",
        R.string.catalog_dosing_brand_aquavitro,
        R.string.catalog_material_dosing_0011_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0011
    ),
    dosingResource(
        "dosing_aquavitro_sentia_doser_secondary",
        R.string.catalog_dosing_brand_aquavitro,
        R.string.catalog_material_dosing_0012_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0012
    ),
    dosingResource(
        "dosing_ati_auto_dosing_pump_dp_6",
        R.string.catalog_dosing_brand_ati,
        R.string.catalog_material_dosing_0013_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0013
    ),
    dosingResource(
        "dosing_autoaqua_smart_doser_2_asd_200",
        R.string.catalog_dosing_brand_autoaqua,
        R.string.catalog_material_dosing_0014_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0014,
        R.string.catalog_dosing_keyword_smart
    ),
    dosingResource(
        "dosing_autoaqua_smart_doser_4_asd_400",
        R.string.catalog_dosing_brand_autoaqua,
        R.string.catalog_material_dosing_0015_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0015,
        R.string.catalog_dosing_keyword_smart
    ),
    dosingResource(
        "dosing_blau_aquaristic_multi_dosing_pump",
        R.string.catalog_dosing_brand_blau_aquaristic,
        R.string.catalog_material_dosing_0016_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0016
    ),
    dosingResource(
        "dosing_blau_aquaristic_extension_multi_dosing_pump",
        R.string.catalog_dosing_brand_blau_aquaristic,
        R.string.catalog_material_dosing_0017_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0017
    ),
    dosingResource(
        "dosing_blau_aquaristic_single_dosing_pump",
        R.string.catalog_dosing_brand_blau_aquaristic,
        R.string.catalog_material_dosing_0018_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0018
    ),
    dosingResource(
        "dosing_blue_marine_dosing_pump_4_channel",
        R.string.catalog_dosing_brand_blue_marine,
        R.string.catalog_material_dosing_0019_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0019,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_bubble_magus_bm_t01_dosing_pump",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0020_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0020
    ),
    dosingResource(
        "dosing_bubble_magus_bm_t02_add_on_dosing_pump",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0021_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0021
    ),
    dosingResource(
        "dosing_bubble_magus_bm_t11_dosing_pump",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0022_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0022
    ),
    dosingResource(
        "dosing_bubble_magus_bm_t12_add_on_dosing_pump",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0023_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0023
    ),
    dosingResource(
        "dosing_bubble_magus_ts1_single_dosing_pump_master",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0024_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0024,
        R.string.catalog_dosing_keyword_master
    ),
    dosingResource(
        "dosing_bubble_magus_ts2_single_dosing_pump_add_on",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0025_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0025
    ),
    dosingResource(
        "dosing_bubble_magus_ts4_single_dosing_pump",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0026_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0026
    ),
    dosingResource(
        "dosing_bubble_magus_ts5_single_dosing_pump",
        R.string.catalog_dosing_brand_bubble_magus,
        R.string.catalog_material_dosing_0027_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0027
    ),
    dosingResource(
        "dosing_bulk_reef_supply_brs_brs_2_part_doser_1_1_ml_min",
        R.string.catalog_dosing_brand_bulk_reef_supply_brs,
        R.string.catalog_material_dosing_0028_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0028
    ),
    dosingResource(
        "dosing_bulk_reef_supply_brs_drews_doser_v2_0",
        R.string.catalog_dosing_brand_bulk_reef_supply_brs,
        R.string.catalog_material_dosing_0029_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0029
    ),
    dosingResource(
        "dosing_chihiros_dosing_pump_system_4_pump_heads",
        R.string.catalog_dosing_brand_chihiros,
        R.string.catalog_material_dosing_0030_name,
        DosingHardwareType.SYSTEM,
        R.string.catalog_dosing_search_alias_0030,
        R.string.catalog_dosing_keyword_multi_head
    ),
    dosingResource(
        "dosing_chihiros_dosing_pump_mate_system_2_pump_heads",
        R.string.catalog_dosing_brand_chihiros,
        R.string.catalog_material_dosing_0031_name,
        DosingHardwareType.SYSTEM,
        R.string.catalog_dosing_search_alias_0031,
        R.string.catalog_dosing_keyword_multi_head
    ),
    dosingResource(
        "dosing_coral_box_wf_01_wi_fi_dosing_pump",
        R.string.catalog_dosing_brand_coral_box,
        R.string.catalog_material_dosing_0032_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0032,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_coral_box_wf_04_wi_fi_dosing_pump",
        R.string.catalog_dosing_brand_coral_box,
        R.string.catalog_material_dosing_0033_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0033,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_d_d_h2ocean_p1_dosing_pump",
        R.string.catalog_dosing_brand_d_d_h2ocean,
        R.string.catalog_material_dosing_0034_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0034
    ),
    dosingResource(
        "dosing_d_d_h2ocean_p1_pro_dosing_pump",
        R.string.catalog_dosing_brand_d_d_h2ocean,
        R.string.catalog_material_dosing_0035_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0035
    ),
    dosingResource(
        "dosing_d_d_h2ocean_p1_stp_connect_peristaltic_pump",
        R.string.catalog_dosing_brand_d_d_h2ocean,
        R.string.catalog_material_dosing_0036_name,
        DosingHardwareType.PERISTALTIC,
        R.string.catalog_dosing_search_alias_0036
    ),
    dosingResource(
        "dosing_d_d_h2ocean_p4_connect_dosing_pump",
        R.string.catalog_dosing_brand_d_d_h2ocean,
        R.string.catalog_material_dosing_0037_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0037
    ),
    dosingResource(
        "dosing_d_d_h2ocean_p4_pro_connect_dosing_pump",
        R.string.catalog_dosing_brand_d_d_h2ocean,
        R.string.catalog_material_dosing_0038_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0038
    ),
    dosingResource(
        "dosing_deltec_dosing_pump_2_channel",
        R.string.catalog_dosing_brand_deltec,
        R.string.catalog_material_dosing_0039_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0039,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_deltec_dosing_pump_3_channel",
        R.string.catalog_dosing_brand_deltec,
        R.string.catalog_material_dosing_0040_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0040,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_deltec_dosing_pump_4_channel",
        R.string.catalog_dosing_brand_deltec,
        R.string.catalog_material_dosing_0041_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0041,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_deltec_dosing_pump_3_s_slave_module",
        R.string.catalog_dosing_brand_deltec,
        R.string.catalog_material_dosing_0042_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0042
    ),
    dosingResource(
        "dosing_deltec_dosing_pump_4_s_slave_module",
        R.string.catalog_dosing_brand_deltec,
        R.string.catalog_material_dosing_0043_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0043
    ),
    dosingResource(
        "dosing_dupla_marin_dosing_pump_p4_smart",
        R.string.catalog_dosing_brand_dupla_marin,
        R.string.catalog_material_dosing_0044_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0044,
        R.string.catalog_dosing_keyword_smart
    ),
    dosingResource(
        "dosing_easyreefs_easyfeeder_master",
        R.string.catalog_dosing_brand_easyreefs,
        R.string.catalog_material_dosing_0045_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0045,
        R.string.catalog_dosing_keyword_master
    ),
    dosingResource(
        "dosing_easyreefs_easyfeeder_slave",
        R.string.catalog_dosing_brand_easyreefs,
        R.string.catalog_material_dosing_0046_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0046
    ),
    dosingResource(
        "dosing_ecotech_marine_versa_vx_1_peristaltic_dosing_pump",
        R.string.catalog_dosing_brand_ecotech_marine,
        R.string.catalog_material_dosing_0047_name,
        DosingHardwareType.PERISTALTIC,
        R.string.catalog_dosing_search_alias_0047
    ),
    dosingResource(
        "dosing_ecotech_marine_versa_vxf_1_four_pack_dosing_pumps",
        R.string.catalog_dosing_brand_ecotech_marine,
        R.string.catalog_material_dosing_0048_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0048
    ),
    dosingResource(
        "dosing_ekoral_ek_doser_4_channel",
        R.string.catalog_dosing_brand_ekoral,
        R.string.catalog_material_dosing_0049_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0049,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_focustronic_dosetronic_pro",
        R.string.catalog_dosing_brand_focustronic,
        R.string.catalog_material_dosing_0050_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0050
    ),
    dosingResource(
        "dosing_focustronic_dosetronic_dc",
        R.string.catalog_dosing_brand_focustronic,
        R.string.catalog_material_dosing_0051_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0051
    ),
    dosingResource(
        "dosing_ghl_doser_2_2_sa",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0052_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0052
    ),
    dosingResource(
        "dosing_ghl_doser_2_2_ext",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0053_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0053
    ),
    dosingResource(
        "dosing_ghl_doser_2_2_maxi_sa",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0054_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0054
    ),
    dosingResource(
        "dosing_ghl_doser_2_2_maxi_ext",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0055_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0055
    ),
    dosingResource(
        "dosing_ghl_doser_3_sa",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0056_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0056
    ),
    dosingResource(
        "dosing_ghl_doser_3_ext",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0057_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0057
    ),
    dosingResource(
        "dosing_ghl_doser_3_maxi_sa",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0058_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0058
    ),
    dosingResource(
        "dosing_ghl_doser_3_maxi_ext",
        R.string.catalog_dosing_brand_ghl,
        R.string.catalog_material_dosing_0059_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0059
    ),
    dosingResource(
        "dosing_grotech_ep_3_mcs_3_channel_dosing_pump_extension",
        R.string.catalog_dosing_brand_grotech,
        R.string.catalog_material_dosing_0060_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0060,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_grotech_ep_5_mcs_5_channel_dosing_pump_extension",
        R.string.catalog_dosing_brand_grotech,
        R.string.catalog_material_dosing_0061_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0061,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_grotech_ep_iv_4_channel_dosing_pump_extension",
        R.string.catalog_dosing_brand_grotech,
        R.string.catalog_material_dosing_0062_name,
        DosingHardwareType.EXTENSION,
        R.string.catalog_dosing_search_alias_0062,
        R.string.catalog_dosing_keyword_multi_channel
    ),
    dosingResource(
        "dosing_hsbao_ds_4_dosing_pump",
        R.string.catalog_dosing_brand_hsbao,
        R.string.catalog_material_dosing_0063_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0063
    ),
    dosingResource(
        "dosing_hydros_control_x10_integrated_4_pump_dosing_system",
        R.string.catalog_dosing_brand_hydros,
        R.string.catalog_material_dosing_0064_name,
        DosingHardwareType.SYSTEM,
        R.string.catalog_dosing_search_alias_0064,
        R.string.catalog_dosing_keyword_integrated
    ),
    dosingResource(
        "dosing_hydros_blenny_4_pump_dosing_system",
        R.string.catalog_dosing_brand_hydros,
        R.string.catalog_material_dosing_0065_name,
        DosingHardwareType.SYSTEM,
        R.string.catalog_dosing_search_alias_0065
    ),
    dosingResource(
        "dosing_hydros_minnow_2_pump_dosing_system",
        R.string.catalog_dosing_brand_hydros,
        R.string.catalog_material_dosing_0066_name,
        DosingHardwareType.SYSTEM,
        R.string.catalog_dosing_search_alias_0066
    ),
    dosingResource(
        "dosing_hydros_sole_continuous_duty_dosing_pump",
        R.string.catalog_dosing_brand_hydros,
        R.string.catalog_material_dosing_0067_name,
        DosingHardwareType.CONTINUOUS_DUTY,
        R.string.catalog_dosing_search_alias_0067
    ),
    dosingResource(
        "dosing_hydros_hydros_2_ml_min_dosing_pump",
        R.string.catalog_dosing_brand_hydros,
        R.string.catalog_material_dosing_0068_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0068
    ),
    dosingResource(
        "dosing_hydros_hydros_dosing_pump_drive_port",
        R.string.catalog_dosing_brand_hydros,
        R.string.catalog_material_dosing_0069_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0069,
        R.string.catalog_dosing_keyword_drive_port
    ),
    dosingResource(
        "dosing_jebao_jecod_dp_2",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0070_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0070
    ),
    dosingResource(
        "dosing_jebao_jecod_dp_3",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0071_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0071
    ),
    dosingResource(
        "dosing_jebao_jecod_dp_3s",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0072_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0072
    ),
    dosingResource(
        "dosing_jebao_jecod_dp_4",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0073_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0073
    ),
    dosingResource(
        "dosing_jebao_jecod_dp_4s",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0074_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0074
    ),
    dosingResource(
        "dosing_jebao_jecod_dp_5",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0075_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0075
    ),
    dosingResource(
        "dosing_jebao_jecod_dp_6_superior",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0076_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0076
    ),
    dosingResource(
        "dosing_jebao_jecod_doser_2_4_wi_fi",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0077_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0077,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_jebao_jecod_doser_3_1",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0078_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0078
    ),
    dosingResource(
        "dosing_jebao_jecod_doser_3_4",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0079_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0079
    ),
    dosingResource(
        "dosing_jebao_jecod_md_4_4",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0080_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0080
    ),
    dosingResource(
        "dosing_jebao_jecod_doser_5_4",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0081_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0081
    ),
    dosingResource(
        "dosing_jebao_jecod_doser_5_6",
        R.string.catalog_dosing_brand_jebao_jecod,
        R.string.catalog_material_dosing_0082_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0082
    ),
    dosingResource(
        "dosing_kamoer_f1_liquid_dosing_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0083_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0083,
        R.string.catalog_keyword_liquid
    ),
    dosingResource(
        "dosing_kamoer_f4_pro_wi_fi_dosing_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0084_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0084,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_kamoer_fx_stp_wi_fi_continuous_duty_dosing_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0085_name,
        DosingHardwareType.CONTINUOUS_DUTY,
        R.string.catalog_dosing_search_alias_0085,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_kamoer_fx_stp2_wi_fi_peristaltic_dosing_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0086_name,
        DosingHardwareType.PERISTALTIC,
        R.string.catalog_dosing_search_alias_0086,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_kamoer_fx_stp3_bluetooth_and_wi_fi_peristaltic_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0087_name,
        DosingHardwareType.PERISTALTIC,
        R.string.catalog_dosing_search_alias_0087,
        R.string.catalog_dosing_keyword_wifi,
        R.string.catalog_dosing_keyword_bluetooth
    ),
    dosingResource(
        "dosing_kamoer_x1_pro_2_dosing_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0088_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0088
    ),
    dosingResource(
        "dosing_kamoer_x1_pro_t2_wi_fi_stepper_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0089_name,
        DosingHardwareType.STEPPER,
        R.string.catalog_dosing_search_alias_0089,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_kamoer_x4_pro_wi_fi_dosing_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0090_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0090,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_kamoer_x5s_wi_fi_dosing_pump",
        R.string.catalog_dosing_brand_kamoer,
        R.string.catalog_material_dosing_0091_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0091,
        R.string.catalog_dosing_keyword_wifi
    ),
    dosingResource(
        "dosing_milwaukee_instruments_mp810_peristaltic_dosing_pump",
        R.string.catalog_dosing_brand_milwaukee_instruments,
        R.string.catalog_material_dosing_0092_name,
        DosingHardwareType.PERISTALTIC,
        R.string.catalog_dosing_search_alias_0092
    ),
    dosingResource(
        "dosing_milwaukee_instruments_mp815_dosing_pump",
        R.string.catalog_dosing_brand_milwaukee_instruments,
        R.string.catalog_material_dosing_0093_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0093
    ),
    dosingResource(
        "dosing_neptune_systems_dos_quietdrive_dosing_pump",
        R.string.catalog_dosing_brand_neptune_systems,
        R.string.catalog_material_dosing_0094_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0094
    ),
    dosingResource(
        "dosing_pacific_sun_kore_7th_dosing_station_starter_edition",
        R.string.catalog_dosing_brand_pacific_sun,
        R.string.catalog_material_dosing_0095_name,
        DosingHardwareType.SYSTEM,
        R.string.catalog_dosing_search_alias_0095,
        R.string.catalog_dosing_keyword_starter_edition
    ),
    dosingResource(
        "dosing_red_sea_reefdose_2",
        R.string.catalog_dosing_brand_red_sea,
        R.string.catalog_material_dosing_0096_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0096
    ),
    dosingResource(
        "dosing_red_sea_reefdose_4",
        R.string.catalog_dosing_brand_red_sea,
        R.string.catalog_material_dosing_0097_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0097
    ),
    dosingResource(
        "dosing_reef_breeders_a1_precision_wireless_doser",
        R.string.catalog_dosing_brand_reef_breeders,
        R.string.catalog_material_dosing_0098_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0098,
        R.string.catalog_dosing_keyword_wireless
    ),
    dosingResource(
        "dosing_reef_breeders_quattro_precision_wireless_doser",
        R.string.catalog_dosing_brand_reef_breeders,
        R.string.catalog_material_dosing_0099_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0099,
        R.string.catalog_dosing_keyword_wireless
    ),
    dosingResource(
        "dosing_reef_factory_dosing_pump",
        R.string.catalog_dosing_brand_reef_factory,
        R.string.catalog_material_dosing_0100_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0100
    ),
    dosingResource(
        "dosing_reef_factory_dosing_pump_x3",
        R.string.catalog_dosing_brand_reef_factory,
        R.string.catalog_material_dosing_0101_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0101
    ),
    dosingResource(
        "dosing_reef_factory_dosing_pump_x4",
        R.string.catalog_dosing_brand_reef_factory,
        R.string.catalog_material_dosing_0102_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0102
    ),
    dosingResource(
        "dosing_reef_factory_dosing_pump_pro_x1",
        R.string.catalog_dosing_brand_reef_factory,
        R.string.catalog_material_dosing_0103_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0103
    ),
    dosingResource(
        "dosing_reef_factory_dosing_pump_pro_x4",
        R.string.catalog_dosing_brand_reef_factory,
        R.string.catalog_material_dosing_0104_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0104
    ),
    dosingResource(
        "dosing_reef_factory_dosing_pump_ato",
        R.string.catalog_dosing_brand_reef_factory,
        R.string.catalog_material_dosing_0105_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0105
    ),
    dosingResource(
        "dosing_reef_factory_dosing_pump_cr",
        R.string.catalog_dosing_brand_reef_factory,
        R.string.catalog_material_dosing_0106_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0106
    ),
    dosingResource(
        "dosing_simplicity_aquatics_4_head_dosing_pump_sim4501",
        R.string.catalog_dosing_brand_simplicity_aquatics,
        R.string.catalog_material_dosing_0107_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0107,
        R.string.catalog_dosing_keyword_multi_head
    ),
    dosingResource(
        "dosing_spectrapure_g7_litermeter_stand_alone_dosing_pump",
        R.string.catalog_dosing_brand_spectrapure,
        R.string.catalog_material_dosing_0108_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0108
    ),
    dosingResource(
        "dosing_tmc_reef_reef_accudose",
        R.string.catalog_dosing_brand_tmc_reef,
        R.string.catalog_material_dosing_0109_name,
        DosingHardwareType.PUMP,
        R.string.catalog_dosing_search_alias_0109
    )
)

object DosingCatalog {

    val definitions: List<AquariumMaterialDefinition> =
        dosingCatalogResources.map { resource ->
            AquariumMaterialDefinition(
                id = resource.id,
                brandRes = resource.brandRes,
                nameRes = resource.nameRes,
                categoryKey = MaterialCategoryKey.DOSING,
                categoryTitleRes = R.string.catalog_material_category_dosing_title,
                keywordRes = (
                    listOf(
                        R.string.catalog_keyword_dosing,
                        R.string.catalog_dosing_keyword_dosing_pump,
                        R.string.catalog_dosing_keyword_doser,
                        R.string.catalog_keyword_pump,
                        R.string.catalog_dosing_keyword_aquarium_doser,
                        R.string.catalog_dosing_keyword_dosing_en,
                        R.string.catalog_dosing_keyword_pump_en,
                        R.string.catalog_dosing_keyword_dosing_pump_en,
                        R.string.catalog_dosing_keyword_doser_en
                    ) +
                        resource.hardwareType.keywordRes +
                        resource.extraKeywordRes
                    ).distinct()
            )
        }

    init {
        check(definitions.size == DOSING_PRODUCT_COUNT)
        check(definitions.map(AquariumMaterialDefinition::id).distinct().size == definitions.size)
        check(definitions.map(AquariumMaterialDefinition::nameRes).distinct().size == definitions.size)
        check(definitions.map(AquariumMaterialDefinition::brandRes).distinct().size == DOSING_BRAND_COUNT)
        check(definitions.all { definition -> definition.id.startsWith("dosing_") })
    }
}

private fun dosingResource(
    id: String,
    brandRes: Int,
    nameRes: Int,
    hardwareType: DosingHardwareType,
    vararg extraKeywordRes: Int
): DosingCatalogResource = DosingCatalogResource(
    id = id,
    brandRes = brandRes,
    nameRes = nameRes,
    hardwareType = hardwareType,
    extraKeywordRes = extraKeywordRes.toList()
)
