package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R
import com.aqua.aqualight.application.aquarium.AquariumGravelProductIds
import com.aqua.aqualight.application.aquarium.AquariumSubstrateMetadataCatalog
import com.aqua.aqualight.application.aquarium.AquariumSubstrateProductMetadata

private const val GRAVEL_PRODUCT_COUNT = 181

private data class GravelCatalogResource(
    val id: String,
    val brandRes: Int,
    val nameRes: Int,
    val extraKeywordRes: List<Int>
)

private val gravelKeywords = listOf(
    R.string.catalog_keyword_gravel,
    R.string.catalog_keyword_sand,
    R.string.catalog_keyword_stone,
    R.string.catalog_keyword_substrate
)

private val gravelCatalogResources = listOf(
    gravelResource(
        "gravel_ada_aqua_gravel_s_2_kg",
        R.string.catalog_brand_ada,
        R.string.catalog_material_gravel_0001_name,
        R.string.catalog_keyword_aqua_gravel
    ),
    gravelResource(
        "gravel_ada_aqua_gravel_s_8_kg",
        R.string.catalog_brand_ada,
        R.string.catalog_material_gravel_0002_name,
        R.string.catalog_keyword_aqua_gravel
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_bairaman_0_1_0_6_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0003_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_bairaman_0_1_0_6_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0004_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_bairaman_0_1_0_6_mm_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0005_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_kongo_3_8_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0006_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_kongo_3_8_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0007_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_kongo_3_8_mm_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0008_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_kongo_10_30_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0009_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_kongo_10_30_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0010_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_kongo_10_30_mm_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0011_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_mekong_0_1_1_4_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0012_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_mekong_0_1_1_4_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0013_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_okavango_4_8_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0014_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_okavango_4_8_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0015_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_okavango_4_8_mm_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0016_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_okavango_8_12_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0017_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_okavango_8_12_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0018_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_okavango_8_12_mm_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0019_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_rio_branco_0_1_2_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0020_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_rio_branco_0_1_2_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0021_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_rio_xingu_2_22_mm_500_g",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0022_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_rio_xingu_2_22_mm_2_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0023_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_dennerle_natural_gravel_rio_xingu_2_22_mm_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0024_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_dennerle_aquarium_gravel_diamond_black_1_2_mm_5_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0025_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_dennerle_aquarium_gravel_diamond_black_1_2_mm_10_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0026_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_dennerle_aquarium_gravel_dark_brown_1_2_mm_10_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0027_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_dark
    ),
    gravelResource(
        "gravel_dennerle_aquarium_gravel_natural_white_1_2_mm_10_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0028_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_dennerle_aquarium_gravel_light_brown_1_2_mm_10_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0029_name
    ),
    gravelResource(
        "gravel_dennerle_aquarium_gravel_slate_gray_1_2_mm_10_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0030_name
    ),
    gravelResource(
        "gravel_dennerle_nano_shrimp_gravel_sulawesi_black_0_7_1_2_mm_2_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0031_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_nano
    ),
    gravelResource(
        "gravel_dennerle_nano_shrimp_gravel_arkansas_grey_0_7_1_2_mm_2_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0032_name,
        R.string.catalog_keyword_nano
    ),
    gravelResource(
        "gravel_dennerle_nano_shrimp_gravel_borneo_brown_0_7_1_2_mm_2_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0033_name,
        R.string.catalog_keyword_nano
    ),
    gravelResource(
        "gravel_dennerle_nano_shrimp_gravel_sunda_white_0_7_1_2_mm_2_kg",
        R.string.catalog_brand_dennerle,
        R.string.catalog_material_gravel_0034_name,
        R.string.catalog_keyword_nano,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_wio_adder_gravel_s_5_10_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0035_name
    ),
    gravelResource(
        "gravel_wio_adder_gravel_mix_5_30_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0036_name
    ),
    gravelResource(
        "gravel_wio_adder_gravel_mix_5_30_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0037_name
    ),
    gravelResource(
        "gravel_wio_belladonna_gravel_s_5_15_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0038_name
    ),
    gravelResource(
        "gravel_wio_belladonna_gravel_mix_5_30_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0039_name
    ),
    gravelResource(
        "gravel_wio_belladonna_gravel_mix_5_30_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0040_name
    ),
    gravelResource(
        "gravel_wio_bumblebee_gravel_s_3_10_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0041_name
    ),
    gravelResource(
        "gravel_wio_bumblebee_gravel_mix_3_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0042_name
    ),
    gravelResource(
        "gravel_wio_bumblebee_gravel_mix_3_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0043_name
    ),
    gravelResource(
        "gravel_wio_elderly_gravel_s_3_10_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0044_name
    ),
    gravelResource(
        "gravel_wio_elderly_gravel_mix_3_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0045_name
    ),
    gravelResource(
        "gravel_wio_elderly_gravel_mix_3_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0046_name
    ),
    gravelResource(
        "gravel_wio_inferno_gravel_s_15_25_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0047_name
    ),
    gravelResource(
        "gravel_wio_inferno_gravel_mix_15_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0048_name
    ),
    gravelResource(
        "gravel_wio_inferno_gravel_mix_15_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0049_name
    ),
    gravelResource(
        "gravel_wio_midnight_gravel_s_10_20_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0050_name
    ),
    gravelResource(
        "gravel_wio_midnight_gravel_mix_10_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0051_name
    ),
    gravelResource(
        "gravel_wio_midnight_gravel_mix_10_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0052_name
    ),
    gravelResource(
        "gravel_wio_mist_gravel_s_10_20_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0053_name
    ),
    gravelResource(
        "gravel_wio_mist_gravel_mix_10_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0054_name
    ),
    gravelResource(
        "gravel_wio_mist_gravel_mix_10_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0055_name
    ),
    gravelResource(
        "gravel_wio_ryuoh_gravel_s_10_20_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0056_name
    ),
    gravelResource(
        "gravel_wio_ryuoh_gravel_mix_10_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0057_name
    ),
    gravelResource(
        "gravel_wio_ryuoh_gravel_mix_10_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0058_name
    ),
    gravelResource(
        "gravel_wio_shadow_gravel_s_1_20_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0059_name
    ),
    gravelResource(
        "gravel_wio_shadow_gravel_mix_1_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0060_name
    ),
    gravelResource(
        "gravel_wio_shadow_gravel_mix_1_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0061_name
    ),
    gravelResource(
        "gravel_wio_stream_gravel_s_8_20_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0062_name
    ),
    gravelResource(
        "gravel_wio_stream_gravel_mix_8_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0063_name
    ),
    gravelResource(
        "gravel_wio_stream_gravel_mix_8_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0064_name
    ),
    gravelResource(
        "gravel_wio_venom_gravel_s_8_20_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0065_name
    ),
    gravelResource(
        "gravel_wio_venom_gravel_mix_8_40_mm_2_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0066_name
    ),
    gravelResource(
        "gravel_wio_venom_gravel_mix_8_40_mm_5_kg",
        R.string.catalog_gravel_brand_wio,
        R.string.catalog_material_gravel_0067_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_snow_0_1_0_6_mm_5_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0068_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_snow_0_1_0_6_mm_10_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0069_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_white_0_2_0_6_mm_5_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0070_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_jbl_sansibar_white_0_2_0_6_mm_10_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0071_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_jbl_sansibar_red_0_2_0_6_mm_5_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0072_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_red_0_2_0_6_mm_10_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0073_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_orange_0_2_0_6_mm_5_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0074_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_orange_0_2_0_6_mm_10_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0075_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_dark_0_2_0_6_mm_5_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0076_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_dark
    ),
    gravelResource(
        "gravel_jbl_sansibar_dark_0_2_0_6_mm_10_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0077_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_dark
    ),
    gravelResource(
        "gravel_jbl_sansibar_grey_0_2_0_6_mm_5_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0078_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_grey_0_2_0_6_mm_10_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0079_name
    ),
    gravelResource(
        "gravel_jbl_sansibar_river_approx_0_8_mm_5_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0080_name,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_jbl_sansibar_river_approx_0_8_mm_10_kg",
        R.string.catalog_brand_jbl,
        R.string.catalog_material_gravel_0081_name,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_anthracite_fine_1_2_mm_3_l_4_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0082_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_anthracite_fine_1_2_mm_6_l_8_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0083_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_brown_fine_0_2_mm_3_l_4_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0084_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_brown_fine_0_2_mm_6_l_8_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0085_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_ocher_fine_0_2_mm_3_l_4_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0086_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_ocher_fine_0_2_mm_6_l_8_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0087_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_white_fine_0_2_mm_3_l_4_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0088_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_white_fine_0_2_mm_6_l_8_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0089_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_anthracite_coarse_1_3_mm_3_l_5_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0090_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_anthracite_coarse_1_3_mm_6_l_10_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0091_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_beige_coarse_2_6_mm_3_l_5_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0092_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_beige_coarse_2_6_mm_6_l_10_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0093_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_black_coarse_2_3_mm_3_l_5_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0094_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_black_coarse_2_3_mm_6_l_10_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0095_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_mix_coarse_2_8_mm_3_l_4_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0096_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_mix_coarse_2_8_mm_6_l_8_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0097_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_white_coarse_1_3_mm_3_l_5_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0098_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_white_coarse_1_3_mm_6_l_10_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0099_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_lava_substrate_2_8_mm_3_l_4_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0100_name
    ),
    gravelResource(
        "gravel_sera_aquarium_gravel_lava_substrate_2_8_mm_6_l_8_kg",
        R.string.catalog_gravel_brand_sera,
        R.string.catalog_material_gravel_0101_name
    ),
    gravelResource(
        "gravel_seachem_flourite_3_5_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0102_name
    ),
    gravelResource(
        "gravel_seachem_flourite_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0103_name
    ),
    gravelResource(
        "gravel_seachem_flourite_black_3_5_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0104_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_seachem_flourite_black_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0105_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_seachem_flourite_dark_3_5_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0106_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_dark
    ),
    gravelResource(
        "gravel_seachem_flourite_dark_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0107_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_dark
    ),
    gravelResource(
        "gravel_seachem_flourite_red_3_5_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0108_name
    ),
    gravelResource(
        "gravel_seachem_flourite_red_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0109_name
    ),
    gravelResource(
        "gravel_seachem_flourite_sand_3_5_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0110_name
    ),
    gravelResource(
        "gravel_seachem_flourite_sand_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0111_name
    ),
    gravelResource(
        "gravel_seachem_flourite_black_sand_3_5_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0112_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_seachem_flourite_black_sand_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0113_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_seachem_onyx_sand_3_5_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0114_name
    ),
    gravelResource(
        "gravel_seachem_onyx_sand_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0115_name
    ),
    gravelResource(
        "gravel_seachem_onyx_7_kg",
        R.string.catalog_gravel_brand_seachem,
        R.string.catalog_material_gravel_0116_name
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_gemstone_creek_3_5_mm_5_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0117_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_gemstone_creek_3_5_mm_20_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0118_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_gemstone_creek_3_5_mm_40_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0119_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_peace_river_1_2_mm_5_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0120_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_peace_river_1_2_mm_10_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0121_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_peace_river_1_2_mm_20_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0122_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_peace_river_1_2_mm_40_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0123_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_midnight_river_1_4_mm_5_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0124_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_midnight_river_1_4_mm_10_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0125_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_midnight_river_1_4_mm_20_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0126_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_midnight_river_1_4_mm_40_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0127_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_raven_river_pebble_6_14_mm_5_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0128_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_raven_river_pebble_6_14_mm_10_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0129_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_raven_river_pebble_6_14_mm_20_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0130_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_raven_river_pebble_6_14_mm_40_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0131_name,
        R.string.catalog_keyword_natural,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_shadow_creek_sand_1_3_mm_5_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0132_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_shadow_creek_sand_1_3_mm_10_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0133_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_shadow_creek_sand_1_3_mm_20_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0134_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_caribsea_super_naturals_shadow_creek_sand_1_3_mm_40_lb",
        R.string.catalog_gravel_brand_caribsea,
        R.string.catalog_material_gravel_0135_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_aquael_natural_multi_colour_gravel_1_4_2_mm_2_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0136_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_aquael_natural_multi_colour_gravel_1_4_2_mm_10_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0137_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_aquael_natural_multi_colour_gravel_3_5_mm_2_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0138_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_aquael_natural_multi_colour_gravel_3_5_mm_10_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0139_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_aquael_natural_multi_colour_gravel_5_10_mm_2_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0140_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_aquael_natural_multi_colour_gravel_5_10_mm_10_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0141_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_aquael_basalt_gravel_2_4_mm_2_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0142_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_basalt
    ),
    gravelResource(
        "gravel_aquael_basalt_gravel_2_4_mm_10_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0143_name,
        R.string.catalog_keyword_black,
        R.string.catalog_keyword_basalt
    ),
    gravelResource(
        "gravel_aquael_dolomite_gravel_2_4_mm_2_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0144_name
    ),
    gravelResource(
        "gravel_aquael_dolomite_gravel_2_4_mm_10_kg",
        R.string.catalog_brand_aquael,
        R.string.catalog_material_gravel_0145_name
    ),
    gravelResource(
        "gravel_reeflowers_natural_aquasand_0_5_1_mm_7_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0146_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_reeflowers_natural_aquasand_0_5_1_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0147_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_reeflowers_iceland_black_sand_1_2_mm_7_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0148_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_reeflowers_iceland_black_sand_1_2_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0149_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_reeflowers_iceland_black_sand_3_5_mm_7_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0150_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_reeflowers_iceland_black_sand_3_5_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0151_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_reeflowers_pearl_white_sand_0_5_1_mm_7_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0152_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_reeflowers_pearl_white_sand_0_5_1_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0153_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_reeflowers_pearl_white_sand_1_1_5_mm_7_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0154_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_reeflowers_pearl_white_sand_1_1_5_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0155_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_reeflowers_natural_tara_gravel_1_2_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0156_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_reeflowers_natural_tara_gravel_2_4_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0157_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_reeflowers_natural_sahara_sand_0_5_1_mm_25_kg",
        R.string.catalog_gravel_brand_reeflowers,
        R.string.catalog_material_gravel_0158_name,
        R.string.catalog_keyword_natural
    ),
    gravelResource(
        "gravel_crystalpro_black_sand_1_3_mm_6_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0159_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_crystalpro_black_sand_1_3_mm_12_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0160_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_crystalpro_black_sand_1_3_mm_25_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0161_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_crystalpro_white_sand_1_1_5_mm_6_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0162_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_crystalpro_white_sand_1_1_5_mm_12_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0163_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_crystalpro_white_sand_1_1_5_mm_25_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0164_name,
        R.string.catalog_keyword_white
    ),
    gravelResource(
        "gravel_crystalpro_silica_sand_0_5_2_mm_6_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0165_name
    ),
    gravelResource(
        "gravel_crystalpro_silica_sand_0_5_2_mm_12_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0166_name
    ),
    gravelResource(
        "gravel_crystalpro_river_sand_3_5_mm_6_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0167_name,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_crystalpro_river_sand_3_5_mm_12_kg",
        R.string.catalog_gravel_brand_crystalpro,
        R.string.catalog_material_gravel_0168_name,
        R.string.catalog_keyword_river
    ),
    gravelResource(
        "gravel_amtra_polychrome_gravel_3_4_mm_2_kg",
        R.string.catalog_gravel_brand_amtra,
        R.string.catalog_material_gravel_0169_name
    ),
    gravelResource(
        "gravel_amtra_polychrome_gravel_3_4_mm_5_kg",
        R.string.catalog_gravel_brand_amtra,
        R.string.catalog_material_gravel_0170_name
    ),
    gravelResource(
        "gravel_amtra_polychrome_gravel_3_4_mm_10_kg",
        R.string.catalog_gravel_brand_amtra,
        R.string.catalog_material_gravel_0171_name
    ),
    gravelResource(
        "gravel_amtra_gravel_noa_4_8_mm_1_kg",
        R.string.catalog_gravel_brand_amtra,
        R.string.catalog_material_gravel_0172_name
    ),
    gravelResource(
        "gravel_amtra_gravel_noa_4_8_mm_2_kg",
        R.string.catalog_gravel_brand_amtra,
        R.string.catalog_material_gravel_0173_name
    ),
    gravelResource(
        "gravel_amtra_gravel_noa_4_8_mm_5_kg",
        R.string.catalog_gravel_brand_amtra,
        R.string.catalog_material_gravel_0174_name
    ),
    gravelResource(
        "gravel_amtra_gravel_noa_4_8_mm_10_kg",
        R.string.catalog_gravel_brand_amtra,
        R.string.catalog_material_gravel_0175_name
    ),
    gravelResource(
        "gravel_prodac_mixed_color_quartz_2_3_mm_1_kg",
        R.string.catalog_gravel_brand_prodac,
        R.string.catalog_material_gravel_0176_name
    ),
    gravelResource(
        "gravel_prodac_mixed_color_quartz_2_3_mm_2_5_kg",
        R.string.catalog_gravel_brand_prodac,
        R.string.catalog_material_gravel_0177_name
    ),
    gravelResource(
        "gravel_prodac_quartz_black_2_3_mm_1_kg",
        R.string.catalog_gravel_brand_prodac,
        R.string.catalog_material_gravel_0178_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_prodac_quartz_black_2_3_mm_2_5_kg",
        R.string.catalog_gravel_brand_prodac,
        R.string.catalog_material_gravel_0179_name,
        R.string.catalog_keyword_black
    ),
    gravelResource(
        "gravel_prodac_polycrome_2_3_mm_2_5_kg",
        R.string.catalog_gravel_brand_prodac,
        R.string.catalog_material_gravel_0180_name
    ),
    gravelResource(
        "gravel_prodac_polycrome_2_3_mm_25_kg",
        R.string.catalog_gravel_brand_prodac,
        R.string.catalog_material_gravel_0181_name
    )
)

object GravelCatalog {

    val definitions: List<AquariumMaterialDefinition> =
        gravelCatalogResources.map { resource ->
            gravel(resource)
        }

    init {
        check(definitions.size == GRAVEL_PRODUCT_COUNT)
        check(definitions.map(AquariumMaterialDefinition::id).distinct().size == definitions.size)
        check(definitions.map(AquariumMaterialDefinition::id) == AquariumGravelProductIds.ALL)
        check(definitions.all { definition -> definition.id.startsWith("gravel_") })
        check(definitions.none { definition -> Regex("^gravel_\\d{4}$").matches(definition.id) })
    }
}

private fun gravelResource(
    id: String,
    brandRes: Int,
    nameRes: Int,
    vararg extraKeywordRes: Int
): GravelCatalogResource = GravelCatalogResource(
    id = id,
    brandRes = brandRes,
    nameRes = nameRes,
    extraKeywordRes = extraKeywordRes.toList()
)

private fun gravel(
    resource: GravelCatalogResource
): AquariumMaterialDefinition = AquariumMaterialDefinition(
    id = resource.id,
    brandRes = resource.brandRes,
    nameRes = resource.nameRes,
    categoryKey = MaterialCategoryKey.GRAVEL,
    categoryTitleRes = R.string.catalog_material_category_gravel_title,
    keywordRes = (gravelKeywords + resource.extraKeywordRes).distinct(),
    substrateMetadata = metadata(resource.id)
)

private fun metadata(productId: String): AquariumSubstrateProductMetadata = requireNotNull(
    AquariumSubstrateMetadataCatalog.metadata(productId, MaterialCategoryKey.GRAVEL)
)
