package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard06: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_chihiros_c_ii_rgb",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0301_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_magnetic_light",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0302_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_magnetic_light_2",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0303_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_nova_1",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0304_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_saltwater",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0305_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_saltwater
    ),
    lightDefinition(
        "light_chihiros_nature",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0306_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_universal_rgb_nano_20",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0307_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_chihiros_universal_rgb_nano_30",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0308_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_chihiros_universal_wrgb",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0309_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_301",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0310_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_451",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0311_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_601",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0312_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_801",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0313_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_901",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0314_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_1201",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0315_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_301",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0316_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_401",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0317_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_501",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0318_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_601",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0319_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_801",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0320_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_901",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0321_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_ii_1201",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0322_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_a_series",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0323_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_b20",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0324_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_b30",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0325_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_b45",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0326_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_b60",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0327_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_b80",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0328_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_b90",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0329_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_b120",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0330_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_c_ii",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0331_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_c_series",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0332_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_z_series",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0333_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_z_light_tiny",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0334_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_chihiros_wrgb_vivid_3_shades_with_mirror",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0335_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_rgb_vivid_ii_rgb_vivid_2_mate_shades_with_mirror_black",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0336_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0336
    ),
    lightDefinition(
        "light_chihiros_rgb_vivid_ii_rgb_vivid_2_mate_shades_with_mirror_silver",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0337_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0337
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_shades_with_mirror_30_cm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0338_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0338
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_shades_with_mirror_40_cm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0339_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0339
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_shades_with_mirror_45_cm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0340_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0340
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_shades_with_mirror_60_cm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0341_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0341
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_wrgb_ii_slim_shades_with_mirror_30_cm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0342_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0342
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_wrgb_ii_slim_shades_with_mirror_45_cm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0343_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0343
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_wrgb_ii_slim_shades_with_mirror_60_cm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0344_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0344
    ),
    lightDefinition(
        "light_chihiros_b_series_shades_with_mirror_b20",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0345_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_search_alias_0345
    ),
    lightDefinition(
        "light_chihiros_b_series_shades_with_mirror_b30",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0346_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_search_alias_0346
    ),
    lightDefinition(
        "light_chihiros_b_series_shades_with_mirror_b60",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0347_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_search_alias_0347
    ),
    lightDefinition(
        "light_chihiros_b_series_shades_with_mirror_b80",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0348_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_search_alias_0348
    ),
    lightDefinition(
        "light_chihiros_b_series_shades_with_mirror_b90",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0349_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_search_alias_0349
    ),
    lightDefinition(
        "light_chihiros_b_series_shades_with_mirror_b120",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0350_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_search_alias_0350
    ),
    lightDefinition(
        "light_chihiros_c_ii_rgb_mirror_shade",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0351_name,
        LightHardwareType.SHADE,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_hanging_rope_kit",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0352_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_slim_hanging_rope_kit",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0353_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_hanging_rope_kit",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0354_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_rgb_vivid_ii_hanging_rope_kit",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0355_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_rgb_vivid_ii_mini_hanging_rope_kit",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0356_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_a_ii_hanging_rope_kit",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0357_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_hanging_rope_kit",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0358_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_chihiros_a_ii_max_acrylic_stand",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0359_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_acrylic_stand",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0360_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_wrgb
    )
)
