package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard09: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_finnex_hlc_series_24",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0481_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0481
    ),
    lightDefinition(
        "light_finnex_hlc_series_30",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0482_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0482
    ),
    lightDefinition(
        "light_finnex_hlc_series_36",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0483_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0483
    ),
    lightDefinition(
        "light_finnex_hlc_series_48",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0484_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0484
    ),
    lightDefinition(
        "light_finnex_crv_series_20",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0485_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0485
    ),
    lightDefinition(
        "light_finnex_crv_series_24",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0486_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0486
    ),
    lightDefinition(
        "light_finnex_crv_series_30",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0487_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0487
    ),
    lightDefinition(
        "light_finnex_crv_series_36",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0488_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0488
    ),
    lightDefinition(
        "light_finnex_crv_series_48",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0489_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0489
    ),
    lightDefinition(
        "light_finnex_planted_plus_3_0_24",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0490_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0490
    ),
    lightDefinition(
        "light_finnex_planted_plus_3_0_36",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0491_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0491
    ),
    lightDefinition(
        "light_finnex_planted_plus_3_0_48",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0492_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0492
    ),
    lightDefinition(
        "light_finnex_vivid_plus_3_0_12",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0493_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0493
    ),
    lightDefinition(
        "light_finnex_vivid_plus_3_0_18",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0494_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0494
    ),
    lightDefinition(
        "light_finnex_vivid_plus_3_0_24",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0495_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0495
    ),
    lightDefinition(
        "light_finnex_vivid_plus_3_0_30",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0496_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0496
    ),
    lightDefinition(
        "light_finnex_vivid_plus_3_0_36",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0497_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0497
    ),
    lightDefinition(
        "light_finnex_vivid_plus_3_0_48",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0498_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0498
    )
    lightDefinition(
        "light_fluval_plant_4_0_nano_led_20w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0499_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_fluval_plant_4_0_led_22w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0500_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_fluval_plant_4_0_led_32w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0501_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_fluval_plant_4_0_led_46w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0502_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_fluval_plant_4_0_led_59w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0503_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_fluval_plant_pro_60_38w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0504_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0504
    ),
    lightDefinition(
        "light_fluval_plant_pro_90_60w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0505_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0505
    ),
    lightDefinition(
        "light_fluval_plant_pro_120_90w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0506_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0506
    ),
    lightDefinition(
        "light_fluval_plant_pro_150_120w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0507_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0507
    ),
    lightDefinition(
        "light_fluval_reef_4_0_nano_led_25w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0508_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_fluval_reef_4_0_led_22w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0509_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_fluval_reef_4_0_led_32w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0510_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_fluval_reef_4_0_led_46w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0511_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_fluval_reef_4_0_led_59w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0512_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_12w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0513_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_16w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0514_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_18w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0515_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_21w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0516_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_25w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0517_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_27w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0518_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_30w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0519_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_33w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0520_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_fluval_aquasky_3_0_led_35w",
        R.string.catalog_light_brand_fluval,
        R.string.catalog_material_light_0521_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
    lightDefinition(
        "light_giesemann_teszla_evo",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0522_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_minox_tropic",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0523_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_vervve_pro",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0524_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_aurora_v12_pro",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0525_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_aurora_v8",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0526_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_pulzar_g3_marine",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0527_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_giesemann_pulzar_g3_tropic",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0528_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_stellar_led",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0529_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_stellaris_pro",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0530_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_viva",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0531_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_matrixx_ii_dimmtec",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0532_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_giesemann_stellar_mounting_system",
        R.string.catalog_light_brand_giesemann,
        R.string.catalog_material_light_0533_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_hygger_hg978_led_fish_tank_light_12_18",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0534_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0534
    ),
    lightDefinition(
        "light_hygger_hg978_led_fish_tank_light_18_24",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0535_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0535
    ),
    lightDefinition(
        "light_hygger_hg978_led_fish_tank_light_24_30",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0536_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0536
    ),
    lightDefinition(
        "light_hygger_hg978_led_fish_tank_light_30_36",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0537_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0537
    ),
    lightDefinition(
        "light_hygger_hg978_led_fish_tank_light_36_42",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0538_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0538
    ),
    lightDefinition(
        "light_hygger_hg978_led_fish_tank_light_48_54",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0539_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0539
    ),
    lightDefinition(
        "light_hygger_hg957_planted_aquarium_light_12_18",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0540_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0540
    )
)
