package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard08: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_daytime_matrix_acrylic_adapter",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0421_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_daytime_pendix_attachment_adapter_set",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0422_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dennerle_trocal_led_40_cm_18w",
        R.string.catalog_light_brand_dennerle,
        R.string.catalog_material_light_0423_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0423
    ),
    lightDefinition(
        "light_dennerle_trocal_led_70_cm_36w",
        R.string.catalog_light_brand_dennerle,
        R.string.catalog_material_light_0424_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0424
    ),
    lightDefinition(
        "light_dennerle_trocal_led_110_cm_60w",
        R.string.catalog_light_brand_dennerle,
        R.string.catalog_material_light_0425_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0425
    ),
    lightDefinition(
        "light_dennerle_trocal_led_140_cm_78w",
        R.string.catalog_light_brand_dennerle,
        R.string.catalog_material_light_0426_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0426
    ),
    lightDefinition(
        "light_dennerle_trocal_flat",
        R.string.catalog_light_brand_dennerle,
        R.string.catalog_material_light_0427_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_dennerle_nano_style_led",
        R.string.catalog_light_brand_dennerle,
        R.string.catalog_material_light_0428_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_dennerle_scaper_s_light",
        R.string.catalog_light_brand_dennerle,
        R.string.catalog_material_light_0429_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0429
    ),
    lightDefinition(
        "light_dooa_paluda_light_ii_300",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0430_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_dooa_paluda_light_ii_600",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0431_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_dooa_magnet_light_g_slim",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0432_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_dooa_magnet_light_g_slim_wood_base_set",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0433_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_dooa_paluda_light_stand",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0434_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_light_stand_z",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0435_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_magnet_light_wire_arm",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0436_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_magnet_light_mounting_arm",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0437_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_magnet_light_stand_15h",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0438_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_magnet_light_stand_20h",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0439_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_magnet_light_stand_20l",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0440_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_magnet_light_stand_maru_95",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0441_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_dooa_magnet_light_stand_maru_130",
        R.string.catalog_light_brand_dooa,
        R.string.catalog_material_light_0442_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_ecotech_radion_xr15_g6_pro",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0443_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ecotech_radion_xr15_g6_blue",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0444_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_ecotech_radion_xr30_g6_pro",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0445_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ecotech_radion_xr30_g6_blue",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0446_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_ecotech_radion_freshwater_pro",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0447_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_ecotech_radion_diffuser_xr15",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0448_name,
        LightHardwareType.DIFFUSER
    ),
    lightDefinition(
        "light_ecotech_radion_diffuser_xr30",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0449_name,
        LightHardwareType.DIFFUSER
    ),
    lightDefinition(
        "light_ecotech_single_light_rms_for_xr15",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0450_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_ecotech_single_light_rms_for_xr30",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0451_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_ecotech_multi_light_rms",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0452_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_ecotech_rms_hanging_kit",
        R.string.catalog_light_brand_ecotech_marine,
        R.string.catalog_material_light_0453_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_eheim_classicled_daylight",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0454_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_daylight
    ),
    lightDefinition(
        "light_eheim_powerled_plus_fresh_daylight",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0455_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0455
    ),
    lightDefinition(
        "light_eheim_powerled_plus_fresh_plants",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0456_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0456
    ),
    lightDefinition(
        "light_eheim_powerled_plus_marine_hybrid",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0457_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_search_alias_0457
    ),
    lightDefinition(
        "light_eheim_powerled_plus_marine_actinic",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0458_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_actinic,
        R.string.catalog_light_search_alias_0458
    ),
    lightDefinition(
        "light_eheim_powerrgb",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0459_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_eheim_powerled_plus_mounting_brackets",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0460_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0460
    ),
    lightDefinition(
        "light_eheim_powerled_plus_suspension_hanging_set",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0461_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0461
    ),
    lightDefinition(
        "light_eheim_classicled_adapter_holder_set",
        R.string.catalog_light_brand_eheim,
        R.string.catalog_material_light_0462_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0462
    ),
    lightDefinition(
        "light_finnex_stingray_12",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0463_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0463
    ),
    lightDefinition(
        "light_finnex_stingray_16",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0464_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0464
    ),
    lightDefinition(
        "light_finnex_stingray_20",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0465_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0465
    ),
    lightDefinition(
        "light_finnex_stingray_24",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0466_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0466
    ),
    lightDefinition(
        "light_finnex_stingray_30",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0467_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0467
    ),
    lightDefinition(
        "light_finnex_stingray_36",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0468_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0468
    ),
    lightDefinition(
        "light_finnex_stingray_48",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0469_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0469
    ),
    lightDefinition(
        "light_finnex_stingray_3_0_12",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0470_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0470
    ),
    lightDefinition(
        "light_finnex_stingray_3_0_18",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0471_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0471
    ),
    lightDefinition(
        "light_finnex_stingray_3_0_24",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0472_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0472
    ),
    lightDefinition(
        "light_finnex_stingray_3_0_36",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0473_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0473
    ),
    lightDefinition(
        "light_finnex_stingray_3_0_48",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0474_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0474
    ),
    lightDefinition(
        "light_finnex_klc_series_20",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0475_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0475
    ),
    lightDefinition(
        "light_finnex_klc_series_24",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0476_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0476
    ),
    lightDefinition(
        "light_finnex_klc_series_30",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0477_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0477
    ),
    lightDefinition(
        "light_finnex_klc_series_36",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0478_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0478
    ),
    lightDefinition(
        "light_finnex_klc_series_48",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0479_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0479
    ),
    lightDefinition(
        "light_finnex_hlc_series_20",
        R.string.catalog_light_brand_finnex,
        R.string.catalog_material_light_0480_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0480
    )
)
