package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard05: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_armaturk_1500l_150_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0241_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0241
    ),
    lightDefinition(
        "light_armaturk_1030h_30_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0242_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0242
    ),
    lightDefinition(
        "light_armaturk_2040h_40_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0243_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0243
    ),
    lightDefinition(
        "light_armaturk_2050h_50_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0244_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0244
    ),
    lightDefinition(
        "light_armaturk_2060h_60_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0245_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0245
    ),
    lightDefinition(
        "light_armaturk_2070h_70_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0246_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0246
    ),
    lightDefinition(
        "light_armaturk_2080h_80_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0247_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0247
    ),
    lightDefinition(
        "light_armaturk_2090h_90_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0248_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0248
    ),
    lightDefinition(
        "light_armaturk_2100h_100_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0249_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0249
    ),
    lightDefinition(
        "light_armaturk_2200h_120_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0250_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0250
    ),
    lightDefinition(
        "light_armaturk_2300h_130_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0251_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0251
    ),
    lightDefinition(
        "light_armaturk_2500h_150_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0252_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0252
    ),
    lightDefinition(
        "light_armaturk_nano_turk",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0253_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano,
        R.string.catalog_light_search_alias_0253
    ),
    lightDefinition(
        "light_armaturk_plant_nano20_led",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0254_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0254
    ),
    lightDefinition(
        "light_armaturk_plant_nano25_led",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0255_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0255
    ),
    lightDefinition(
        "light_armaturk_eko_40_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0256_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0256
    ),
    lightDefinition(
        "light_armaturk_eko_50_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0257_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0257
    ),
    lightDefinition(
        "light_armaturk_eko_60_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0258_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0258
    ),
    lightDefinition(
        "light_armaturk_eko_70_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0259_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0259
    ),
    lightDefinition(
        "light_armaturk_eko_80_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0260_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0260
    )
    lightDefinition(
        "light_ati_straton_x",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0261_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ati_straton_pro_g2_102_white",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0262_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0262
    ),
    lightDefinition(
        "light_ati_straton_pro_g2_102_anthracite",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0263_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0263
    ),
    lightDefinition(
        "light_ati_straton_pro_g2_153_white",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0264_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0264
    ),
    lightDefinition(
        "light_ati_straton_pro_g2_153_anthracite",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0265_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0265
    ),
    lightDefinition(
        "light_ati_straton_pro_g2_204_white",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0266_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0266
    ),
    lightDefinition(
        "light_ati_straton_pro_g2_204_anthracite",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0267_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0267
    ),
    lightDefinition(
        "light_ati_straton_flex_g2_102_white",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0268_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0268
    ),
    lightDefinition(
        "light_ati_straton_flex_g2_102_black",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0269_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0269
    ),
    lightDefinition(
        "light_ati_straton_flex_g2_153_white",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0270_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0270
    ),
    lightDefinition(
        "light_ati_straton_flex_g2_153_black",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0271_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0271
    ),
    lightDefinition(
        "light_ati_aquablue_special_t5",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0272_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t5
    ),
    lightDefinition(
        "light_ati_blue_plus_t5",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0273_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_ati_coral_plus_t5",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0274_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_coral
    ),
    lightDefinition(
        "light_ati_straton_x_mounting_arm",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0275_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_ati_straton_x_hanging_kit",
        R.string.catalog_light_brand_ati_aquaristik,
        R.string.catalog_material_light_0276_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_bioloark_magnet_plant_light_dl_05",
        R.string.catalog_light_brand_bioloark,
        R.string.catalog_material_light_0277_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_bioloark_wabi_kusa_lamp_tf",
        R.string.catalog_light_brand_bioloark,
        R.string.catalog_material_light_0278_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_bioloark_wabi_kusa_lamp_dx_03",
        R.string.catalog_light_brand_bioloark,
        R.string.catalog_material_light_0279_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_bioloark_wabi_kusa_light_dx_5b",
        R.string.catalog_light_brand_bioloark,
        R.string.catalog_material_light_0280_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
    lightDefinition(
        "light_chihiros_wrgb_vivid_3",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0281_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_rgb_vivid_2_mate",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0282_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_rgb_vivid_ii_10th_edition",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0283_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_rgb_vivid_ii_mini",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0284_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_30",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0285_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_45",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0286_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_60",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0287_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_80",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0288_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_90",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0289_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_120",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0290_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_30_10th_edition",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0291_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0291
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_45_10th_edition",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0292_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0292
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_60_10th_edition",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0293_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0293
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_90_10th_edition",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0294_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0294
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_120_10th_edition",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0295_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_light_search_alias_0295
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_slim_30",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0296_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_slim_45",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0297_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_slim_60",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0298_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_slim_90",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0299_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_wrgb_ii_slim_120",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0300_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_wrgb
    )
)
