package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard07: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_chihiros_wrgb_ii_pro_non_adjustable_metal_stand",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0361_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_wrgb
    ),
    lightDefinition(
        "light_chihiros_small_hanging_stand_kit_for_rgb_vivid_wrgb",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0362_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0362
    ),
    lightDefinition(
        "light_chihiros_new_stand_for_rgb_vivid_wrgb_series",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0363_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_wrgb,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0363
    ),
    lightDefinition(
        "light_chihiros_c_ii_base_stand",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0364_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_chihiros_c_ii_rgb_base_stand",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0365_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_chihiros_z_light_tiny_extend_arm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0366_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_chihiros_z_light_tiny_l_clip_12_20_mm",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0367_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0367
    ),
    lightDefinition(
        "light_chihiros_magnetic_light_base",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0368_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_chihiros_magnetic_light_stand_10w",
        R.string.catalog_light_brand_chihiros,
        R.string.catalog_material_light_0369_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_creaqua_alpha_rgb_plus_w_60",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0370_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0370
    ),
    lightDefinition(
        "light_creaqua_alpha_rgb_plus_w_90",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0371_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0371
    ),
    lightDefinition(
        "light_creaqua_alpha_rgb_plus_w_120",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0372_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0372
    ),
    lightDefinition(
        "light_creaqua_alpha_rgb_plus_w_150",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0373_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0373
    ),
    lightDefinition(
        "light_creaqua_alpha_pw_60_85_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0374_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0374
    ),
    lightDefinition(
        "light_creaqua_alpha_pw_90_115_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0375_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0375
    ),
    lightDefinition(
        "light_creaqua_alpha_pw_120_140_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0376_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0376
    ),
    lightDefinition(
        "light_creaqua_alpha_pw_150_175_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0377_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0377
    ),
    lightDefinition(
        "light_creaqua_delta_pw_35_55_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0378_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0378
    ),
    lightDefinition(
        "light_creaqua_delta_pw_60_85_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0379_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0379
    ),
    lightDefinition(
        "light_creaqua_delta_pw_90_115_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0380_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0380
    ),
    lightDefinition(
        "light_creaqua_delta_pw_120_150_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0381_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0381
    ),
    lightDefinition(
        "light_creaqua_delta_marine_35",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0382_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_creaqua_delta_marine_40",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0383_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_creaqua_sigma_pw_35_55_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0384_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0384
    ),
    lightDefinition(
        "light_creaqua_sigma_pw_60_85_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0385_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0385
    ),
    lightDefinition(
        "light_creaqua_sigma_pw_90_115_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0386_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0386
    ),
    lightDefinition(
        "light_creaqua_sigma_pw_120_150_cm",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0387_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0387
    ),
    lightDefinition(
        "light_creaqua_nano_elite_black",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0388_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_creaqua_nano_s_black",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0389_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_creaqua_alpha_pw_hanging_kit",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0390_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_creaqua_alpha_pw_expandable_mounting_feet",
        R.string.catalog_light_brand_creaqua,
        R.string.catalog_material_light_0391_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_current_usa_colorplus_smart_freshwater_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0392_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_keyword_smart
    ),
    lightDefinition(
        "light_current_usa_satellite_led_plus_pro",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0393_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_current_usa_serenesun_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0394_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_current_usa_orbit_marine_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0395_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_current_usa_orbit_marine_ic_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0396_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_current_usa_orbit_marine_ic_pro_dual_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0397_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_current_usa_orbit_r24_reef_led_52w",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0398_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_current_usa_orbit_r24_reef_led_95w",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0399_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_current_usa_add_on_orbit_marine_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0400_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_current_usa_add_on_orbit_marine_ic_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0401_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_current_usa_add_on_r24_reef_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0402_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_current_usa_ecoxotic_cannon_80_led_460_nm_blue",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0403_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0403
    ),
    lightDefinition(
        "light_current_usa_ecoxotic_cannon_80_led_10_000_k_white",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0404_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0404
    ),
    lightDefinition(
        "light_current_usa_ecoxotic_cannon_80_led_5_000_k_sun_white",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0405_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0405
    ),
    lightDefinition(
        "light_current_usa_cannon_pro_led",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0406_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_current_usa_dual_adjustable_led_light_arm_kit",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0407_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_current_usa_single_adjustable_led_light_arm",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0408_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_current_usa_xw_arm_mount",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0409_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_current_usa_flex_arm_tank_mount",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0410_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_current_usa_flex_arm_stand_mount",
        R.string.catalog_light_brand_current_usa,
        R.string.catalog_material_light_0411_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_daytime_matrix",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0412_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_daytime_pendix",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0413_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_daytime_unix",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0414_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_daytime_onex",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0415_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_daytime_onex_black",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0416_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_daytime_cobra",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0417_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_daytime_kingcobra",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0418_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_daytime_acrylic_nano_adapter_set",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0419_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_daytime_t5_t8_adapter_set",
        R.string.catalog_light_brand_daytime,
        R.string.catalog_material_light_0420_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_t8,
        R.string.catalog_light_search_alias_0420
    )
)
