package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard13: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_reefbreeders_edge_bar",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0721_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_reefbreeders_mounting_legs",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0722_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_reefbreeders_hanging_wires",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0723_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_reefbreeders_photon_link_kit",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0724_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_reefbreeders_ohm_optics",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0725_name,
        LightHardwareType.OPTICAL_ACCESSORY
    )
    lightDefinition(
        "light_reef_factory_reef_flare_pro_s",
        R.string.catalog_light_brand_reef_factory,
        R.string.catalog_material_light_0726_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_reef_factory_reef_flare_pro_m",
        R.string.catalog_light_brand_reef_factory,
        R.string.catalog_material_light_0727_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_reef_factory_reef_flare_pro_l",
        R.string.catalog_light_brand_reef_factory,
        R.string.catalog_material_light_0728_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_reef_factory_reef_flare_pro_s_blue",
        R.string.catalog_light_brand_reef_factory,
        R.string.catalog_material_light_0729_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_reef_factory_reef_flare_pro_m_blue",
        R.string.catalog_light_brand_reef_factory,
        R.string.catalog_material_light_0730_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_reef_factory_reef_flare_pro_l_blue",
        R.string.catalog_light_brand_reef_factory,
        R.string.catalog_material_light_0731_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_keyword_blue
    )
    lightDefinition(
        "light_reefi_uno_2_1_pro",
        R.string.catalog_light_brand_reefi,
        R.string.catalog_material_light_0732_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_reefi_led_duo_extreme",
        R.string.catalog_light_brand_reefi,
        R.string.catalog_material_light_0733_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_reefi_tank_mount_kit",
        R.string.catalog_light_brand_reefi,
        R.string.catalog_material_light_0734_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_reefi_wire_hanging_kit",
        R.string.catalog_light_brand_reefi,
        R.string.catalog_material_light_0735_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_sera_led_x_change_tube_daylight_sunrise_360_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0736_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0736
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_daylight_sunrise_520_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0737_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0737
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_daylight_sunrise_660_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0738_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0738
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_daylight_sunrise_820_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0739_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0739
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_daylight_sunrise_965_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0740_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0740
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_daylight_sunrise_1120_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0741_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0741
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_cool_daylight_360_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0742_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0742
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_cool_daylight_520_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0743_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0743
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_cool_daylight_660_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0744_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0744
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_cool_daylight_820_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0745_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0745
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_cool_daylight_965_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0746_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0746
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_cool_daylight_1120_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0747_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_daylight,
        R.string.catalog_light_search_alias_0747
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_neutral_brilliant_white",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0748_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_plantcolor_sunrise_360_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0749_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_search_alias_0749
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_plantcolor_sunrise_520_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0750_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_search_alias_0750
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_plantcolor_sunrise_660_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0751_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_search_alias_0751
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_plantcolor_sunrise_820_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0752_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_search_alias_0752
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_plantcolor_sunrise_965_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0753_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_search_alias_0753
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_plantcolor_sunrise_1120_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0754_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_search_alias_0754
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_marine_blue_sunrise_360_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0755_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0755
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_marine_blue_sunrise_520_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0756_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0756
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_marine_blue_sunrise_660_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0757_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0757
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_marine_blue_sunrise_820_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0758_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0758
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_marine_blue_sunrise_965_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0759_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0759
    ),
    lightDefinition(
        "light_sera_led_x_change_tube_marine_blue_sunrise_1120_mm",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0760_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0760
    ),
    lightDefinition(
        "light_sera_led_light_6w",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0761_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sera_nano_led_light_4w",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0762_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_sera_led_tube_holder_clear",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0763_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube
    ),
    lightDefinition(
        "light_sera_led_fixture_800",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0764_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sera_led_fixture_1000",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0765_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sera_led_fixture_1200",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0766_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sera_led_fixture_clips",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0767_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sera_t5_short_adapter",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0768_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_t5
    ),
    lightDefinition(
        "light_sera_t5_adapter",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0769_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_t5
    ),
    lightDefinition(
        "light_sera_t8_adapter",
        R.string.catalog_light_brand_sera,
        R.string.catalog_material_light_0770_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_t8
    )
    lightDefinition(
        "light_shark_one_series_30_45_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0771_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0771
    ),
    lightDefinition(
        "light_shark_one_series_45_60_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0772_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0772
    ),
    lightDefinition(
        "light_shark_one_series_60_75_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0773_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0773
    ),
    lightDefinition(
        "light_shark_one_series_75_90_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0774_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0774
    ),
    lightDefinition(
        "light_shark_one_series_90_105_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0775_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0775
    ),
    lightDefinition(
        "light_shark_one_series_105_120_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0776_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0776
    ),
    lightDefinition(
        "light_shark_duo_series_30_45_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0777_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0777
    ),
    lightDefinition(
        "light_shark_duo_series_45_60_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0778_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0778
    ),
    lightDefinition(
        "light_shark_duo_series_60_75_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0779_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0779
    ),
    lightDefinition(
        "light_shark_duo_series_75_90_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0780_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0780
    )
)
