package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard12: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_orionled_b_series_controlled",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0661_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orionled_c_series_black",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0662_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orionled_c_series_grey",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0663_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orionled_c_series_rgb_w_controlled",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0664_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_orionled_d_reef_series_marine_aquarium_lighting",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0665_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_orionled_d_rgbw_black_wi_fi_app_controlled",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0666_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw,
        R.string.catalog_light_search_alias_0666
    ),
    lightDefinition(
        "light_orionled_d_rgbw_wi_fi_app_controlled",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0667_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw,
        R.string.catalog_light_search_alias_0667
    ),
    lightDefinition(
        "light_orionled_e_series_5_row_led_lighting",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0668_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orionled_fanus_and_nano_aquarium_led_spiral_gooseneck_5v",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0669_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano,
        R.string.catalog_light_search_alias_0669
    ),
    lightDefinition(
        "light_orionled_grolux_series_a",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0670_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_grolux
    ),
    lightDefinition(
        "light_orionled_grolux_t8_series",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0671_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t8,
        R.string.catalog_light_keyword_grolux
    ),
    lightDefinition(
        "light_orionled_nano_arc_5_5w",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0672_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_orionled_nano_c_reef_series",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0673_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_orionled_nano_grolux_series",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0674_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano,
        R.string.catalog_light_keyword_grolux
    ),
    lightDefinition(
        "light_orionled_nano_m_1_mixed_color_dimmer",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0675_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano,
        R.string.catalog_light_keyword_dimmable,
        R.string.catalog_light_search_alias_0675
    ),
    lightDefinition(
        "light_orionled_nano_m_2",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0676_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_orionled_nano_m_3_series",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0677_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_orionled_nano_spot_led_5v_3w",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0678_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano,
        R.string.catalog_light_search_alias_0678
    ),
    lightDefinition(
        "light_orionled_plant_a_series_4_color",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0679_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_orionled_spot_led_24v_12w_adjustable_lens",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0680_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_20_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0681_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0681
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_30_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0682_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0682
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_40_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0683_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0683
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_50_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0684_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0684
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_60_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0685_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0685
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_70_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0686_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0686
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_80_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0687_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0687
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_90_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0688_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0688
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_100_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0689_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0689
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_110_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0690_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0690
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_120_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0691_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0691
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_130_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0692_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0692
    ),
    lightDefinition(
        "light_orionled_aquaslim_4_color_140_cm",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0693_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0693
    ),
    lightDefinition(
        "light_orionled_d_series_shade_mirror_mirrored_shade",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0694_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_search_alias_0694
    )
    lightDefinition(
        "light_orphek_natura_icon",
        R.string.catalog_light_brand_orphek,
        R.string.catalog_material_light_0695_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orphek_natura_icon_max_290w",
        R.string.catalog_light_brand_orphek,
        R.string.catalog_material_light_0696_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orphek_or4_icon_led_bar",
        R.string.catalog_light_brand_orphek,
        R.string.catalog_material_light_0697_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orphek_atlantik_icon",
        R.string.catalog_light_brand_orphek,
        R.string.catalog_material_light_0698_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_orphek_hanging_kit",
        R.string.catalog_light_brand_orphek,
        R.string.catalog_material_light_0699_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_orphek_mounting_arm_bracket_system",
        R.string.catalog_light_brand_orphek,
        R.string.catalog_material_light_0700_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0700
    )
    lightDefinition(
        "light_philips_coralcare_gen2_led_fixture_white",
        R.string.catalog_light_brand_philips_coralcare,
        R.string.catalog_material_light_0701_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0701
    ),
    lightDefinition(
        "light_philips_coralcare_gen2_led_fixture_black",
        R.string.catalog_light_brand_philips_coralcare,
        R.string.catalog_material_light_0702_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0702
    ),
    lightDefinition(
        "light_philips_coralcare_gen2_hanging_kit",
        R.string.catalog_light_brand_philips_coralcare,
        R.string.catalog_material_light_0703_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_red_sea_reefled_g2_60",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0704_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_red_sea_reefled_g2_115",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0705_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_red_sea_reefled_g2_170",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0706_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_red_sea_reefled_g2_clip_on_visor_60",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0707_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_red_sea_reefled_g2_clip_on_visor_115",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0708_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_red_sea_reefled_g2_clip_on_visor_170",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0709_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_red_sea_reefled_50_60_mounting_arm",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0710_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0710
    ),
    lightDefinition(
        "light_red_sea_reefled_90_115_universal_mounting_arm",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0711_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0711
    ),
    lightDefinition(
        "light_red_sea_reefled_160_170_universal_mounting_arm",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0712_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0712
    ),
    lightDefinition(
        "light_red_sea_reefled_pendant_black",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0713_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_pendant,
        R.string.catalog_light_search_alias_0713
    ),
    lightDefinition(
        "light_red_sea_reefled_pendant_white",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0714_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_pendant,
        R.string.catalog_light_search_alias_0714
    ),
    lightDefinition(
        "light_red_sea_reefled_hanging_kit",
        R.string.catalog_light_brand_red_sea,
        R.string.catalog_material_light_0715_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_reefbreeders_meridian",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0716_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_reefbreeders_meridian_edge",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0717_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_reefbreeders_photon_v2_pro",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0718_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_reefbreeders_reef_nano",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0719_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_reefbreeders_lumenbar_v2",
        R.string.catalog_light_brand_reefbreeders,
        R.string.catalog_material_light_0720_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
)
