package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard04: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_aquareef_s60_w",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0181_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s70_w",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0182_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s90_w",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0183_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s110_w",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0184_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_pro5_mirror_light_shield",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0185_name,
        LightHardwareType.SHADE
    ),
    lightDefinition(
        "light_aquareef_adjustable_hanging_kit",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0186_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_aquareef_telescopic_tank_edge_mounting_legs",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0187_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_aquareef_rms_style_mounting_system",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0188_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_aqueon_betta_light_led",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0189_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqueon_clip_on_led_light",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0190_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_aqueon_planted_aquarium_clip_on_led_light",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0191_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_aqueon_led_deluxe_full_hood",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0192_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqueon_led_optibright_light_fixture",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0193_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqueon_led_optibright_plus_plus_light_fixture",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0194_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0194
    ),
    lightDefinition(
        "light_aqueon_led_strip_light_fixture",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0195_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_strip_light
    ),
    lightDefinition(
        "light_aqueon_optibright_smart_led_light_fixture",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0196_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_smart
    ),
    lightDefinition(
        "light_aqueon_day_white_led_lamp",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0197_name,
        LightHardwareType.REPLACEMENT_LAMP,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqueon_colormax_led_lamp",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0198_name,
        LightHardwareType.REPLACEMENT_LAMP,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqueon_beauty_max_led_lamp",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0199_name,
        LightHardwareType.REPLACEMENT_LAMP,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqueon_max_blue_led_lamp",
        R.string.catalog_light_brand_aqueon,
        R.string.catalog_material_light_0200_name,
        LightHardwareType.REPLACEMENT_LAMP,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue
    )
    lightDefinition(
        "light_aquatlantis_easy_led_universal_rgbw_ultra_600",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0201_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_rgbw_ultra_750",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0202_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_rgbw_ultra_900",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0203_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_rgbw_ultra_1050",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0204_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_rgbw_ultra_1150",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0205_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_rgbw_ultra_1350",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0206_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_rgbw_ultra_1600",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0207_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_rgbw
    ),
    lightDefinition(
        "light_aquatlantis_univ_led_plus",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0208_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquatlantis_univ_led",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0209_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_freshwater_438_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0210_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_freshwater_590_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0211_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_freshwater_742_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0212_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_freshwater_895_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0213_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_freshwater_1047_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0214_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_freshwater_1200_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0215_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_freshwater_1450_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0216_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_and_reef_438_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0217_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_search_alias_0217
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_and_reef_590_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0218_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_search_alias_0218
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_and_reef_742_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0219_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_search_alias_0219
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_and_reef_895_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0220_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_search_alias_0220
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_and_reef_1047_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0221_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_search_alias_0221
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_and_reef_1200_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0222_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_search_alias_0222
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_and_reef_1450_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0223_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_reef,
        R.string.catalog_light_search_alias_0223
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_marine_blue_438_590_742_895_1047_1200_1450_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0224_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0224
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_2_0_deep_blue_438_590_742_895_1047_1200_1450_mm",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0225_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0225
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_tube",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0226_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_model_5_w_black",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0227_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0227
    ),
    lightDefinition(
        "light_aquatlantis_easy_led_universal_model_5_w_white",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0228_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0228
    ),
    lightDefinition(
        "light_aquatlantis_safe_lighting_led",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0229_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquatlantis_stainless_steel_cable_kit",
        R.string.catalog_light_brand_aquatlantis,
        R.string.catalog_material_light_0230_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_armaturk_1030l_30_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0231_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0231
    ),
    lightDefinition(
        "light_armaturk_1040l_40_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0232_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0232
    ),
    lightDefinition(
        "light_armaturk_1050l_50_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0233_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0233
    ),
    lightDefinition(
        "light_armaturk_1060l_60_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0234_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0234
    ),
    lightDefinition(
        "light_armaturk_1070l_70_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0235_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0235
    ),
    lightDefinition(
        "light_armaturk_1080l_80_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0236_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0236
    ),
    lightDefinition(
        "light_armaturk_1090l_90_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0237_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0237
    ),
    lightDefinition(
        "light_armaturk_1100l_100_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0238_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0238
    ),
    lightDefinition(
        "light_armaturk_1200l_120_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0239_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0239
    ),
    lightDefinition(
        "light_armaturk_1300l_130_cm",
        R.string.catalog_light_brand_armaturk,
        R.string.catalog_material_light_0240_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0240
    )
)
