package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard02: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_aqua_one_mariglo_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0061_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_mariglo_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0062_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_reefglow_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0063_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_reefglow_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0064_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_reefglow_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0065_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_tropicglo_led_45_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0066_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_tropicglo_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0067_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_tropicglo_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0068_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_tropicglo_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0069_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_reflex_led_13",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0070_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_reflex_led_35",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0071_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_ecoglo",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0072_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_extendable_led",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0073_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_fluroglow",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0074_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_stripglo_telescopic_tall_bracket",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0075_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_aqua_one_stripglo_telescopic_short_bracket",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0076_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_aqua_one_stripglo_t5_t8_retrofit_mounting_bracket",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0077_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_t8,
        R.string.catalog_light_search_alias_0077
    ),
    lightDefinition(
        "light_aqua_one_stripglo_oakstyle_mounting_bracket",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0078_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_aqua_one_plantglo_light_bracket",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0079_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_aquael_leddy_slim_sunny_day_and_night",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0080_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_day_night,
        R.string.catalog_light_search_alias_0080
    ),
    lightDefinition(
        "light_aquael_leddy_slim_plant_2_0",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0081_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aquael_leddy_slim_marine_day_and_night",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0082_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_day_night,
        R.string.catalog_light_search_alias_0082
    ),
    lightDefinition(
        "light_aquael_leddy_slim_duo_marine_and_actinic",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0083_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_actinic,
        R.string.catalog_light_search_alias_0083
    ),
    lightDefinition(
        "light_aquael_leddy_slim_duo_sunny_and_plant",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0084_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0084
    ),
    lightDefinition(
        "light_aquael_leddy_slim_link_2_0",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0085_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquael_leddy_smart_bt",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0086_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_smart
    ),
    lightDefinition(
        "light_aquael_leddy_smart_day_and_night_plant",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0087_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_smart,
        R.string.catalog_light_keyword_day_night,
        R.string.catalog_light_search_alias_0087
    ),
    lightDefinition(
        "light_aquael_leddy_smart_day_and_night_sunny",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0088_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_smart,
        R.string.catalog_light_keyword_day_night,
        R.string.catalog_light_search_alias_0088
    ),
    lightDefinition(
        "light_aquael_leddy_tube_retrofit_day_and_night_sunny",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0089_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_day_night,
        R.string.catalog_light_search_alias_0089
    ),
    lightDefinition(
        "light_aquael_leddy_tube_retrofit_day_and_night_plant",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0090_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_day_night,
        R.string.catalog_light_search_alias_0090
    ),
    lightDefinition(
        "light_aquael_leddy_tube_retrofit_marine",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0091_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_tube
    ),
    lightDefinition(
        "light_aquael_leddy_tube_retrofit_actinic",
        R.string.catalog_light_brand_aquael,
        R.string.catalog_material_light_0092_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube,
        R.string.catalog_light_keyword_actinic
    )
    lightDefinition(
        "light_ai_hydra_edge_44hd",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0093_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ai_hydra_edge_68hd",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0094_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ai_hydra_32hd",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0095_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ai_hydra_64hd",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0096_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ai_hydra_32_freshwater",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0097_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_ai_prime_16hd_reef",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0098_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_reef
    ),
    lightDefinition(
        "light_ai_prime_16hd_freshwater",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0099_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_ai_prime_fuge",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0100_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_refugium
    ),
    lightDefinition(
        "light_ai_blade_coral_grow_12",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0101_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_keyword_grow,
        R.string.catalog_light_search_alias_0101
    ),
    lightDefinition(
        "light_ai_blade_coral_grow_21",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0102_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_keyword_grow,
        R.string.catalog_light_search_alias_0102
    ),
    lightDefinition(
        "light_ai_blade_coral_grow_30",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0103_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_keyword_grow,
        R.string.catalog_light_search_alias_0103
    ),
    lightDefinition(
        "light_ai_blade_coral_grow_39",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0104_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_keyword_grow,
        R.string.catalog_light_search_alias_0104
    ),
    lightDefinition(
        "light_ai_blade_coral_grow_48",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0105_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_keyword_grow,
        R.string.catalog_light_search_alias_0105
    ),
    lightDefinition(
        "light_ai_blade_coral_grow_57",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0106_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_keyword_grow,
        R.string.catalog_light_search_alias_0106
    ),
    lightDefinition(
        "light_ai_blade_coral_grow_66",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0107_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_keyword_grow,
        R.string.catalog_light_search_alias_0107
    ),
    lightDefinition(
        "light_ai_blade_coral_glow_12",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0108_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_search_alias_0108
    ),
    lightDefinition(
        "light_ai_blade_coral_glow_21",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0109_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_search_alias_0109
    ),
    lightDefinition(
        "light_ai_blade_coral_glow_30",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0110_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_search_alias_0110
    ),
    lightDefinition(
        "light_ai_blade_coral_glow_39",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0111_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_search_alias_0111
    ),
    lightDefinition(
        "light_ai_blade_coral_glow_48",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0112_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_search_alias_0112
    ),
    lightDefinition(
        "light_ai_blade_coral_glow_57",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0113_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_search_alias_0113
    ),
    lightDefinition(
        "light_ai_blade_coral_glow_66",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0114_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_coral,
        R.string.catalog_light_search_alias_0114
    ),
    lightDefinition(
        "light_ai_blade_freshwater_12",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0115_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0115
    ),
    lightDefinition(
        "light_ai_blade_freshwater_21",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0116_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0116
    ),
    lightDefinition(
        "light_ai_blade_freshwater_30",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0117_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0117
    ),
    lightDefinition(
        "light_ai_blade_freshwater_39",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0118_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0118
    ),
    lightDefinition(
        "light_ai_blade_freshwater_48",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0119_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0119
    ),
    lightDefinition(
        "light_ai_blade_freshwater_57",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0120_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0120
    )
)
