package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard14: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_shark_duo_series_90_105_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0781_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0781
    ),
    lightDefinition(
        "light_shark_duo_series_105_120_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0782_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0782
    ),
    lightDefinition(
        "light_shark_3_color_grolux_bar_led_20_cm",
        R.string.catalog_light_brand_shark_akvaryum_aydinlatma_sistemleri,
        R.string.catalog_material_light_0783_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_grolux
    )
    lightDefinition(
        "light_skylight_hyperspot_f_fs",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0784_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0784
    ),
    lightDefinition(
        "light_skylight_hyperspot_f_fm",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0785_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0785
    ),
    lightDefinition(
        "light_skylight_hyperspot_f_fl",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0786_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0786
    ),
    lightDefinition(
        "light_skylight_parmaster_f",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0787_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_skylight_entriq",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0788_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_skylight_foqal_s",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0789_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_skylight_foqal_h",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0790_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_skylight_hyperbar_f_fs_30",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0791_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0791
    ),
    lightDefinition(
        "light_skylight_hyperbar_f_fm_45",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0792_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0792
    ),
    lightDefinition(
        "light_skylight_hyperbar_f_fl_60",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0793_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0793
    ),
    lightDefinition(
        "light_skylight_hyperbar_f_fxl_75",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0794_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0794
    ),
    lightDefinition(
        "light_skylight_hyperspot_r_rs",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0795_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0795
    ),
    lightDefinition(
        "light_skylight_hyperspot_r_rm",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0796_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0796
    ),
    lightDefinition(
        "light_skylight_hyperspot_r_rl",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0797_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0797
    ),
    lightDefinition(
        "light_skylight_parmaster_r",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0798_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_skylight_entriq_r",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0799_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_skylight_hyperbar_r",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0800_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_skylight_hyperbar_stand_holder",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0801_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperbar_edge_holder",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0802_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperbar_edge_holder_adjustable",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0803_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperbar_hanging_kit",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0804_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperbar_aquarium_edge_stand",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0805_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperbar_cabinet_stand",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0806_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperbar_holder_extensions",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0807_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperspot_mounting_bracket",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0808_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperspot_stand",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0809_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_skylight_hyperspot_hanging_kit",
        R.string.catalog_light_brand_skylight,
        R.string.catalog_material_light_0810_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_sobo_l_28c_mini_led_black",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0811_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0811
    ),
    lightDefinition(
        "light_sobo_l_28c_mini_led_white",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0812_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0812
    ),
    lightDefinition(
        "light_sobo_l_28c_mini_led_red",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0813_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0813
    ),
    lightDefinition(
        "light_sobo_sb_cl3w_clip_on_led",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0814_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_sobo_sb_cl6w_clip_on_led",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0815_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_sobo_sb_cl9w_clip_on_led",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0816_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on
    ),
    lightDefinition(
        "light_sobo_sd_4w_clip_on_led_white_plus_pink",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0817_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on,
        R.string.catalog_light_search_alias_0817
    ),
    lightDefinition(
        "light_sobo_sd_6w_clip_on_led_white_plus_pink",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0818_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on,
        R.string.catalog_light_search_alias_0818
    ),
    lightDefinition(
        "light_sobo_sd_9w_clip_on_led_white_plus_pink",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0819_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on,
        R.string.catalog_light_search_alias_0819
    ),
    lightDefinition(
        "light_sobo_s_cl3w_clip_on_led_white",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0820_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on,
        R.string.catalog_light_search_alias_0820
    ),
    lightDefinition(
        "light_sobo_s_cl6w_clip_on_led_white",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0821_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on,
        R.string.catalog_light_search_alias_0821
    ),
    lightDefinition(
        "light_sobo_s_cl9w_clip_on_led_white",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0822_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_clip_on,
        R.string.catalog_light_search_alias_0822
    ),
    lightDefinition(
        "light_sobo_al_300p_plant_led_9_5w_30_40_cm",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0823_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0823
    ),
    lightDefinition(
        "light_sobo_al_400p_plant_led_12w_40_50_cm",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0824_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0824
    ),
    lightDefinition(
        "light_sobo_al_500p_plant_led_16w_50_60_cm",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0825_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0825
    ),
    lightDefinition(
        "light_sobo_al_600p_plant_led_18w_60_70_cm",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0826_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0826
    ),
    lightDefinition(
        "light_sobo_t4_30led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0827_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_40led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0828_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_50led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0829_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_60led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0830_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_70led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0831_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_80led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0832_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_100led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0833_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_120led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0834_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sobo_t4_150led_submersible_light",
        R.string.catalog_light_brand_sobo,
        R.string.catalog_material_light_0835_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
    lightDefinition(
        "light_spectra_neo_super_blue_led",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0836_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_spectra_aqua_knight_m029",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0837_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_spectra_aqua_knight_m029_v",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0838_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_spectra_aqua_knight_v2_led",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0839_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_spectra_aqua_knight_v3_led",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0840_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
)
