package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard10: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_hygger_hg957_planted_aquarium_light_18_24",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0541_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0541
    ),
    lightDefinition(
        "light_hygger_hg957_planted_aquarium_light_24_30",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0542_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0542
    ),
    lightDefinition(
        "light_hygger_hg957_planted_aquarium_light_30_36",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0543_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0543
    ),
    lightDefinition(
        "light_hygger_hg957_planted_aquarium_light_36_42",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0544_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0544
    ),
    lightDefinition(
        "light_hygger_hg957_planted_aquarium_light_48_55",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0545_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0545
    ),
    lightDefinition(
        "light_hygger_aquasense_aquarium_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0546_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_plant_one_aquarium_led_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0547_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_hygger_hg248_naturelite_aquarium_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0548_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_hg075_aquarium_led_plant_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0549_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_hygger_simple_aquarium_led_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0550_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_pro_simple_aquarium_led_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0551_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_slim_led_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0552_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_full_spectrum_clip_on_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0553_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_clip_on,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_hygger_submersible_aquarium_led_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0554_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_dunker_pro_submersible_aquarium_led_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0555_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_sun_aquarium_led_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0556_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_sun_moon_led_aquarium_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0557_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_hg999_aquarium_light",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0558_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_hygger_adjustable_light_holder_extendable_bracket_set",
        R.string.catalog_light_brand_hygger,
        R.string.catalog_material_light_0559_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0559
    )
    lightDefinition(
        "light_jbl_led_solar_natur_gen2_16w_438_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0560_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0560
    ),
    lightDefinition(
        "light_jbl_led_solar_natur_gen2_20w_549_590_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0561_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0561
    ),
    lightDefinition(
        "light_jbl_led_solar_natur_gen2_28w_742_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0562_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0562
    ),
    lightDefinition(
        "light_jbl_led_solar_natur_gen2_31w_849_895_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0563_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0563
    ),
    lightDefinition(
        "light_jbl_led_solar_natur_gen2_47w_1047_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0564_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0564
    ),
    lightDefinition(
        "light_jbl_led_solar_natur_gen2_48w_1149_1200_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0565_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0565
    ),
    lightDefinition(
        "light_jbl_led_solar_natur_gen2_53w_1449_1500_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0566_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0566
    ),
    lightDefinition(
        "light_jbl_led_solar_effect_rgb_gen2",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0567_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_jbl_led_solar_effect_rgb_85_110_cm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0568_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0568
    ),
    lightDefinition(
        "light_jbl_led_solar_hanging",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0569_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_jbl_led_solar_holding_bracket_set",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0570_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_jbl_led_solar_end_cap_set_25_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0571_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_jbl_led_solar_end_cap_set_45_mm",
        R.string.catalog_light_brand_jbl,
        R.string.catalog_material_light_0572_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    )
    lightDefinition(
        "light_juwel_helialux_spectrum_550",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0573_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_helialux_spectrum_600",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0574_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_helialux_spectrum_700",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0575_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_helialux_spectrum_800",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0576_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_helialux_spectrum_920",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0577_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_helialux_spectrum_1000",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0578_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_helialux_spectrum_1200",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0579_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_helialux_spectrum_1500",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0580_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_juwel_multilux_led_55",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0581_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_multilux_led_60",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0582_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_multilux_led_70",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0583_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_multilux_led_80",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0584_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_multilux_led_92",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0585_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_multilux_led_100",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0586_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_multilux_led_120",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0587_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_multilux_led_150",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0588_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_led_day_tube",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0589_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube
    ),
    lightDefinition(
        "light_juwel_led_nature_tube",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0590_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube
    ),
    lightDefinition(
        "light_juwel_led_colour_tube",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0591_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_tube
    ),
    lightDefinition(
        "light_juwel_novolux_led_neo_white",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0592_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_juwel_helialux_universalfit",
        R.string.catalog_light_brand_juwel,
        R.string.catalog_material_light_0593_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_kessil_ap9x",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0594_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_kessil_a500x",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0595_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_kessil_a360xe",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0596_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_kessil_a360x",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0597_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_kessil_a360x_refugium",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0598_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_refugium
    ),
    lightDefinition(
        "light_kessil_a160we",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0599_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_kessil_a80",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0600_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
)
