package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard03: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_ai_blade_freshwater_66",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0121_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_light_search_alias_0121
    ),
    lightDefinition(
        "light_ai_blade_refugium",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0122_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_refugium
    ),
    lightDefinition(
        "light_ai_blade_glofish",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0123_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ai_blade_hanging_kit_3_light",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0124_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_light_search_alias_0124
    ),
    lightDefinition(
        "light_ai_blade_hanging_kit_4_light",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0125_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_light_search_alias_0125
    ),
    lightDefinition(
        "light_ai_blade_hanging_kit_6_light",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0126_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_light_search_alias_0126
    ),
    lightDefinition(
        "light_ai_blade_elevated_tank_mount",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0127_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_blade_hybrid_mount",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0128_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_blade_tank_rest",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0129_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_blade_low_profile_tank_rest",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0130_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_blade_mounting_clips",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0131_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_hms_single_arm_kit",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0132_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_hms_double_arm_kit",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0133_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_hms_hanging_kit",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0134_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_prime_flex_arm_12",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0135_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_light_search_alias_0135
    ),
    lightDefinition(
        "light_ai_prime_flex_arm_18",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0136_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination,
        R.string.catalog_light_search_alias_0136
    ),
    lightDefinition(
        "light_ai_prime_tank_mount",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0137_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_prime_hanging_kit",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0138_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_hydra_flex_arm",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0139_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_ai_hydra_edge_mounting_kit",
        R.string.catalog_light_brand_aquaillumination,
        R.string.catalog_material_light_0140_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_ai,
        R.string.catalog_light_brand_alias_aqua_illumination
    ),
    lightDefinition(
        "light_aqualed_meta_plant_plus_full_spectrum_3_row_led_black_body",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0141_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum,
        R.string.catalog_light_search_alias_0141
    ),
    lightDefinition(
        "light_aqualed_meta_plant_plus_full_spectrum_3_row_led_metallic_body",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0142_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum,
        R.string.catalog_light_search_alias_0142
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_20_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0143_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_30_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0144_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_40_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0145_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_50_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0146_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_60_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0147_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_70_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0148_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_80_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0149_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_90_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0150_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_100_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0151_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_110_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0152_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_120_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0153_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_130_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0154_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_140_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0155_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plant_pro_full_spectrum_150_cm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0156_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_aqualed_meta_plus_plus_full_spectrum_4_row_special_layout",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0157_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum,
        R.string.catalog_light_search_alias_0157
    ),
    lightDefinition(
        "light_aqualed_full_spectrum_planted_aquarium_lighting_4_color_mixed",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0158_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum,
        R.string.catalog_light_search_alias_0158
    ),
    lightDefinition(
        "light_aqualed_grolux_planted_aquarium_lighting_3_color_mixed",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0159_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_grolux,
        R.string.catalog_light_search_alias_0159
    ),
    lightDefinition(
        "light_aqualed_blue_and_white_aquarium_lighting",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0160_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0160
    ),
    lightDefinition(
        "light_aqualed_royal_blue_450_nm",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0161_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_aqualed_lens_led_white_6500_k",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0162_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqualed_led_lighting_fixture_single_leg_pair",
        R.string.catalog_light_brand_aqualed,
        R.string.catalog_material_light_0163_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_f30_f_v2_series",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0164_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0164
    ),
    lightDefinition(
        "light_aquareef_f50_f_v2_series",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0165_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0165
    ),
    lightDefinition(
        "light_aquareef_f80_f_v2_series",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0166_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0166
    ),
    lightDefinition(
        "light_aquareef_f100_f_v2_series",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0167_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0167
    ),
    lightDefinition(
        "light_aquareef_f130_f_v2_series",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0168_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0168
    ),
    lightDefinition(
        "light_aquareef_pro5",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0169_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_pro5_max",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0170_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_a_series",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0171_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_l_series",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0172_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s35",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0173_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s45",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0174_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s60",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0175_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s70",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0176_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s90",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0177_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s110",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0178_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s35_w",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0179_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aquareef_s45_w",
        R.string.catalog_light_brand_aquareef,
        R.string.catalog_material_light_0180_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
)
