package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard16: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_twinstar_b_line_20b",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0901_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_b_line_30b",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0902_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_b_line_45b",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0903_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_b_line_60b",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0904_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_b_line_75b",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0905_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_b_line_90b",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0906_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_b_line_120b",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0907_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_a_line_20a",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0908_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_a_line_30a",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0909_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_a_line_45a",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0910_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_a_line_60a",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0911_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_a_line_80a",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0912_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_a_line_90a",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0913_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_a_line_120a",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0914_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_g_line_ii_60g_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0915_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_g_line_ii_90g_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0916_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_g_line_ii_100g_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0917_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_g_line_ii_120g_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0918_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_g_plus_line_ii_80g_plus_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0919_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0919
    ),
    lightDefinition(
        "light_twinstar_g_plus_line_ii_100g_plus_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0920_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0920
    ),
    lightDefinition(
        "light_twinstar_g_plus_line_ii_120g_plus_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0921_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0921
    ),
    lightDefinition(
        "light_twinstar_g_plus_line_ii_140g_plus_ii",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0922_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0922
    ),
    lightDefinition(
        "light_twinstar_s_line_v_pendant_kit",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0923_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_pendant
    ),
    lightDefinition(
        "light_twinstar_g_g_plus_t5_t8_adapter",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0924_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_t8,
        R.string.catalog_light_search_alias_0924
    ),
    lightDefinition(
        "light_twinstar_g_g_plus_inverted_bracket",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0925_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0925
    )
    lightDefinition(
        "light_uns_titan_1",
        R.string.catalog_light_brand_uns,
        R.string.catalog_material_light_0926_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_ultum_nature_systems,
        R.string.catalog_keyword_led
    )
    lightDefinition(
        "light_week_aqua_mag_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0927_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_s_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0928_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_m_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0929_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_m_series_pendant",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0930_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_pendant
    ),
    lightDefinition(
        "light_week_aqua_v_series_standard",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0931_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_v_series_pendant",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0932_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_pendant
    ),
    lightDefinition(
        "light_week_aqua_v_series_amphibious",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0933_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_l_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0934_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_p_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0935_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_a_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0936_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_t_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0937_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_t95",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0938_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_t95_pro",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0939_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_t140_pro",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0940_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_z_series_freshwater",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0941_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_week_aqua_z_series_marine_seawater",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0942_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_search_alias_0942
    ),
    lightDefinition(
        "light_week_aqua_z400_seawater",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0943_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_y_series_amphibious",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0944_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_np10",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0945_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_mini7pro_f",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0946_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_mini7pro_o",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0947_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_week_aqua_usb_magnetic_plant_grow_light",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0948_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_keyword_grow
    ),
    lightDefinition(
        "light_week_aqua_t8_series",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0949_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t8
    ),
    lightDefinition(
        "light_week_aqua_l_stand",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0950_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_week_aqua_s_stand",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0951_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_week_aqua_longmen_bracket",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0952_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_week_aqua_back_style_bracket",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0953_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_week_aqua_paludarium_lamp_bracket",
        R.string.catalog_light_brand_week_aqua,
        R.string.catalog_material_light_0954_name,
        LightHardwareType.MOUNTING
    )
    lightDefinition(
        "light_zetlight_m1_pro_m",
        R.string.catalog_light_brand_zetlight,
        R.string.catalog_material_light_0955_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0955
    ),
    lightDefinition(
        "light_zetlight_m1_pro_f",
        R.string.catalog_light_brand_zetlight,
        R.string.catalog_material_light_0956_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0956
    ),
    lightDefinition(
        "light_zetlight_ufo_f8_max",
        R.string.catalog_light_brand_zetlight,
        R.string.catalog_material_light_0957_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_zetlight_s1",
        R.string.catalog_light_brand_zetlight,
        R.string.catalog_material_light_0958_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_zetlight_x9",
        R.string.catalog_light_brand_zetlight,
        R.string.catalog_material_light_0959_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_zetlight_ufo_a8",
        R.string.catalog_light_brand_zetlight,
        R.string.catalog_material_light_0960_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
)
