package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard15: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_spectra_sp20_marine",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0841_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_spectra_sp20_freshwater",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0842_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_spectra_sp20_refugium",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0843_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_refugium
    ),
    lightDefinition(
        "light_spectra_aqua_helios_r60",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0844_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_spectra_aqua_helios_r90",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0845_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_spectra_aqua_helios_r120",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0846_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_spectra_ipl_series_freshwater",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0847_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_spectra_spl_series_freshwater",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0848_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_spectra_cpl_series_freshwater",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0849_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_spectra_sjl5_nano_freshwater",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0850_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_spectra_freshwater_led_f001_d_60",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0851_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_spectra_freshwater_led_f001_d_90",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0852_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_spectra_freshwater_led_f001_d_120",
        R.string.catalog_light_brand_spectra_aqua_knight,
        R.string.catalog_material_light_0853_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_freshwater
    ),
    lightDefinition(
        "light_sunsun_adp_080j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0854_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_160j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0855_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_200j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0856_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_250j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0857_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_300j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0858_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_400j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0859_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_500j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0860_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_700j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0861_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_800j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0862_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_900j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0863_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sunsun_adp_1050j",
        R.string.catalog_light_brand_sunsun_sensen,
        R.string.catalog_material_light_0864_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_sylvania_grolux_t5_24w",
        R.string.catalog_light_brand_sylvania,
        R.string.catalog_material_light_0865_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_grolux,
        R.string.catalog_light_search_alias_0865
    ),
    lightDefinition(
        "light_sylvania_grolux_t5_39w",
        R.string.catalog_light_brand_sylvania,
        R.string.catalog_material_light_0866_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_grolux,
        R.string.catalog_light_search_alias_0866
    ),
    lightDefinition(
        "light_sylvania_grolux_t5_54w",
        R.string.catalog_light_brand_sylvania,
        R.string.catalog_material_light_0867_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_grolux,
        R.string.catalog_light_search_alias_0867
    ),
    lightDefinition(
        "light_sylvania_grolux_t5_80w",
        R.string.catalog_light_brand_sylvania,
        R.string.catalog_material_light_0868_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t5,
        R.string.catalog_light_keyword_grolux,
        R.string.catalog_light_search_alias_0868
    ),
    lightDefinition(
        "light_sylvania_t8_36w",
        R.string.catalog_light_brand_sylvania,
        R.string.catalog_material_light_0869_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_keyword_t8,
        R.string.catalog_light_search_alias_0869
    ),
    lightDefinition(
        "light_tetra_lightwave_complete_set",
        R.string.catalog_light_brand_tetra,
        R.string.catalog_material_light_0870_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_tetra_lightwave_single_light",
        R.string.catalog_light_brand_tetra,
        R.string.catalog_material_light_0871_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_tetra_aquaart_led_20_30l_lamp_4_8w",
        R.string.catalog_light_brand_tetra,
        R.string.catalog_material_light_0872_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0872
    ),
    lightDefinition(
        "light_tetra_aquaart_led_60l_lamp_9_6w",
        R.string.catalog_light_brand_tetra,
        R.string.catalog_material_light_0873_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0873
    ),
    lightDefinition(
        "light_tetra_tetronic_led_proline",
        R.string.catalog_light_brand_tetra,
        R.string.catalog_material_light_0874_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_tunze_led_marine_eco_chic_8811",
        R.string.catalog_light_brand_tunze,
        R.string.catalog_material_light_0875_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine
    ),
    lightDefinition(
        "light_tunze_led_white_eco_chic_8821",
        R.string.catalog_light_brand_tunze,
        R.string.catalog_material_light_0876_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_tunze_led_eco_chic_refugium_8831",
        R.string.catalog_light_brand_tunze,
        R.string.catalog_material_light_0877_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_refugium
    ),
    lightDefinition(
        "light_tunze_led_full_spectrum_8850",
        R.string.catalog_light_brand_tunze,
        R.string.catalog_material_light_0878_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_full_spectrum,
        R.string.catalog_light_keyword_spectrum
    ),
    lightDefinition(
        "light_twinstar_s_line_v_200s",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0879_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_s_line_v_300s",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0880_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_s_line_v_450s",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0881_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_s_line_v_600s",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0882_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_s_line_v_900s",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0883_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_s_line_v_1200s",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0884_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_200ea",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0885_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_300ea",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0886_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_450ea",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0887_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_600ea",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0888_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_750ea",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0889_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_900ea",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0890_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_1200ea",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0891_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_450ec",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0892_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_600ec",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0893_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_pro_200e_pro",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0894_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_pro_300e_pro",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0895_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_pro_450e_pro",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0896_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_pro_600e_pro",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0897_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_pro_750e_pro",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0898_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_pro_900e_pro",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0899_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_twinstar_e_line_v_pro_1200e_pro",
        R.string.catalog_light_brand_twinstar,
        R.string.catalog_material_light_0900_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
)
