package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard11: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_kessil_h160_tuna_flora",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0601_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_kessil_h80_tuna_flora",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0602_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_kessil_ap9x_mounting_arm",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0603_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_kessil_mounting_arm",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0604_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_kessil_hanging_kit",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0605_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_kessil_a_series_gooseneck",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0606_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_kessil_mini_a_series_gooseneck",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0607_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_kessil_extension_mount",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0608_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_kessil_extended_slide_bar",
        R.string.catalog_light_brand_kessil,
        R.string.catalog_material_light_0609_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_maxspect_jump_mj_l165",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0610_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_maxspect_jump_mj_l165_blue",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0611_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue
    ),
    lightDefinition(
        "light_maxspect_jump_mj_l130_standard",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0612_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_maxspect_jump_mj_l130_refugium",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0613_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_refugium
    ),
    lightDefinition(
        "light_maxspect_ethereal",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0614_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_maxspect_rsx",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0615_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_maxspect_jump_mounting_stand",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0616_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_maxspect_rsx_hanging_kit",
        R.string.catalog_light_brand_maxspect,
        R.string.catalog_material_light_0617_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_micmol_g3_aqua_mini_g3_am_marine",
        R.string.catalog_light_brand_micmol,
        R.string.catalog_material_light_0618_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_search_alias_0618
    ),
    lightDefinition(
        "light_micmol_g3_aqua_mini_g3_am_planted",
        R.string.catalog_light_brand_micmol,
        R.string.catalog_material_light_0619_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0619
    ),
    lightDefinition(
        "light_micmol_g3_aqua_pro_g3_ap_marine",
        R.string.catalog_light_brand_micmol,
        R.string.catalog_material_light_0620_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_search_alias_0620
    ),
    lightDefinition(
        "light_micmol_g3_aqua_pro_g3_ap_planted",
        R.string.catalog_light_brand_micmol,
        R.string.catalog_material_light_0621_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted,
        R.string.catalog_light_search_alias_0621
    ),
    lightDefinition(
        "light_micmol_adjustable_hanging_kit",
        R.string.catalog_light_brand_micmol,
        R.string.catalog_material_light_0622_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_micmol_super_bracket",
        R.string.catalog_light_brand_micmol,
        R.string.catalog_material_light_0623_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_netlea_nl_545s_at5_z0_4_50w",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0624_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0624
    ),
    lightDefinition(
        "light_netlea_nl_560s_at5_z0_4",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0625_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0625
    ),
    lightDefinition(
        "light_netlea_nl_580s_at5_z0_4_80w",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0626_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0626
    ),
    lightDefinition(
        "light_netlea_nl_590s_at5_z0_4_95w",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0627_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0627
    ),
    lightDefinition(
        "light_netlea_nl_5120s_at5_z0_4_120w",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0628_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0628
    ),
    lightDefinition(
        "light_netlea_nl_580p_at5_d0_3_80w_pendant",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0629_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_pendant,
        R.string.catalog_light_search_alias_0629
    ),
    lightDefinition(
        "light_netlea_nl_6105p_at5_d0_4_105w_pendant",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0630_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_pendant,
        R.string.catalog_light_search_alias_0630
    ),
    lightDefinition(
        "light_netlea_nl_560s_rgb_z0_4_60w",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0631_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0631
    ),
    lightDefinition(
        "light_netlea_at6s_iii",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0632_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_netlea_at7s_ii",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0633_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_netlea_at_5_hanging_kit",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0634_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_netlea_at_5_parallel_hanging_kit",
        R.string.catalog_light_brand_netlea,
        R.string.catalog_material_light_0635_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_oase_highline_premium_led_45",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0636_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_oase_highline_premium_led_65",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0637_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_oase_highline_premium_led_80",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0638_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_oase_highline_premium_led_100",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0639_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_oase_highline_premium_led_120",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0640_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_oase_motioncontrol_led",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0641_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_oase_highline_premium_led_swing_adapter",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0642_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_oase_led_rope_suspension_set",
        R.string.catalog_light_brand_oase,
        R.string.catalog_material_light_0643_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_onf_mist_o_plus",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0644_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0644
    ),
    lightDefinition(
        "light_onf_mist_o",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0645_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_onf_flat_one_plus",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0646_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0646
    ),
    lightDefinition(
        "light_onf_flat_nano_plus",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0647_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano,
        R.string.catalog_light_search_alias_0647
    ),
    lightDefinition(
        "light_onf_flat_nano",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0648_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_onf_square",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0649_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_onf_mist_o_two_in_one_bracket",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0650_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_onf_stand_for_flat_nano",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0651_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_keyword_nano
    ),
    lightDefinition(
        "light_onf_cable_strap",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0652_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_onf_angle_iron_shelf_bracket_for_onf_square",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0653_name,
        LightHardwareType.MOUNTING
    ),
    lightDefinition(
        "light_onf_ana_stainless_light_stand_set_for_mist_o_plus",
        R.string.catalog_light_brand_onf,
        R.string.catalog_material_light_0654_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_search_alias_0654
    ),
    lightDefinition(
        "light_orionled_aquaslim_grolux_fire",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0655_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_grolux,
        R.string.catalog_light_search_alias_0655
    ),
    lightDefinition(
        "light_orionled_aquaslim_grolux_ice",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0656_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_grolux,
        R.string.catalog_light_search_alias_0656
    ),
    lightDefinition(
        "light_orionled_aquaslim_series_4_color_aquarium_led",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0657_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_search_alias_0657
    ),
    lightDefinition(
        "light_orionled_aquaslim_series_royal_blue_aquarium_led",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0658_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0658
    ),
    lightDefinition(
        "light_orionled_bluetooth_phone_controlled_rgb_aquarium_led",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0659_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_orionled_nano_m1_b_white_6500_k",
        R.string.catalog_light_brand_orionled,
        R.string.catalog_material_light_0660_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_nano
    )
)
