package com.aqua.aqualight.ui.tabs.aquarium.catalog.material

import com.aqua.aqualight.R

internal val lightCatalogShard01: List<AquariumMaterialDefinition> = listOf(
    lightDefinition(
        "light_ada_na_light_300",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0001_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ada_na_light_450",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0002_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ada_na_light_pro_600",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0003_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_ada_solar_rgb_ii",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0004_name,
        LightHardwareType.LIGHT,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_ada_shade_for_solar_rgb",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0005_name,
        LightHardwareType.SHADE,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_ada_solar_rgb_stand_w60xd30_cm",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0006_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0006
    ),
    lightDefinition(
        "light_ada_solar_rgb_stand_w60xd45_cm_right_side_mount",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0007_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0007
    ),
    lightDefinition(
        "light_ada_solar_rgb_stand_w60xd45_cm_left_side_mount",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0008_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0008
    ),
    lightDefinition(
        "light_ada_solar_rgb_stand_w90xd45_cm",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0009_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0009
    ),
    lightDefinition(
        "light_ada_solar_rgb_stand_w120_cm",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0010_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0010
    ),
    lightDefinition(
        "light_ada_solar_rgb_stand_w180_cm",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0011_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb,
        R.string.catalog_light_search_alias_0011
    ),
    lightDefinition(
        "light_ada_solar_rgb_stand_for_metal_cabinet_60",
        R.string.catalog_light_brand_ada,
        R.string.catalog_material_light_0012_name,
        LightHardwareType.MOUNTING,
        R.string.catalog_light_brand_alias_aqua_design_amano,
        R.string.catalog_keyword_rgb
    ),
    lightDefinition(
        "light_aqua_medic_aquarius_plant_plus_series",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0013_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aqua_medic_aquarius_plus_series",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0014_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_qube_30_plant",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0015_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aqua_medic_qube_40",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0016_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_qube_60_2",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0017_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_spectrus",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0018_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_spectrus_twin",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0019_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_sunbeam_series",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0020_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_led_fa_100_flex",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0021_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_led_fa_200_flex",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0022_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_ledspot_100_w",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0023_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_ledspot_120_w_flex",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0024_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_ledspot_200_w",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0025_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_ledspot_200_w_flex",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0026_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_ledspot_400_w_flex",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0027_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_medic_ledspot_1000_w_flex",
        R.string.catalog_light_brand_aqua_medic,
        R.string.catalog_material_light_0028_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_stripglo_plant_led_30_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0029_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aqua_one_stripglo_plant_led_45_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0030_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aqua_one_stripglo_plant_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0031_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aqua_one_stripglo_plant_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0032_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aqua_one_stripglo_plant_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0033_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_keyword_plant,
        R.string.catalog_light_keyword_planted
    ),
    lightDefinition(
        "light_aqua_one_stripglo_tropical_led_30_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0034_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_stripglo_tropical_led_45_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0035_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_stripglo_tropical_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0036_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_stripglo_tropical_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0037_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_stripglo_tropical_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0038_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_stripglo_marine_cichlid_blue_led_30_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0039_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0039
    ),
    lightDefinition(
        "light_aqua_one_stripglo_marine_cichlid_blue_led_45_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0040_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0040
    ),
    lightDefinition(
        "light_aqua_one_stripglo_marine_cichlid_blue_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0041_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0041
    ),
    lightDefinition(
        "light_aqua_one_stripglo_marine_cichlid_blue_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0042_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0042
    ),
    lightDefinition(
        "light_aqua_one_stripglo_marine_cichlid_blue_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0043_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_marine,
        R.string.catalog_light_keyword_blue,
        R.string.catalog_light_search_alias_0043
    ),
    lightDefinition(
        "light_aqua_one_stripglo_sunlight_led_45_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0044_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_sunlight
    ),
    lightDefinition(
        "light_aqua_one_stripglo_sunlight_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0045_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_sunlight
    ),
    lightDefinition(
        "light_aqua_one_stripglo_sunlight_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0046_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_sunlight
    ),
    lightDefinition(
        "light_aqua_one_stripglo_sunlight_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0047_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_sunlight
    ),
    lightDefinition(
        "light_aqua_one_dynamic_58_pendant_light",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0048_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_pendant
    ),
    lightDefinition(
        "light_aqua_one_aqualume_led_strip_light",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0049_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led,
        R.string.catalog_light_keyword_strip_light
    ),
    lightDefinition(
        "light_aqua_one_arcglo_led",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0050_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_j_bar_led",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0051_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_aquanano_led_25",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0052_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_aquanano_led_30",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0053_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_aquanano_led_40",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0054_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_plantglo_led_45_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0055_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_plantglo_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0056_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_plantglo_led_90_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0057_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_plantglo_led_120_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0058_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_mariglo_led_45_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0059_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    ),
    lightDefinition(
        "light_aqua_one_mariglo_led_60_cm",
        R.string.catalog_light_brand_aqua_one,
        R.string.catalog_material_light_0060_name,
        LightHardwareType.LIGHT,
        R.string.catalog_keyword_led
    )
)
