package com.aqua.aqualight.ui.tabs.devices.detail.light.presentation

data class DeviceLightUiState(
    val isLoading: Boolean = false,
    val programTitle: String = "",
    val programSubtitle: String = "",
    val modeLabel: String = "",
    val currentOutputLabel: String = "",
    val redLabel: String = "",
    val greenLabel: String = "",
    val blueLabel: String = "",
    val whiteLabel: String = "",
    val nowLabel: String = "",
    val nextLabel: String = "",
    val curveNowLabel: String = "",
    val timelineStartLabel: String = "",
    val timelineMidLabel: String = "",
    val timelineEndLabel: String = "",
    val curveStartLabel: String = "",
    val curvePeakLabel: String = "",
    val curveSunsetLabel: String = "",
    val curveRampLabel: String = "",
    val activeProgramId: String? = null,
    val activeProgramName: String = "",
    val activeProgramSchedule: String = "",
    val activeProgramChannels: String = "",
    val activeProgramStatusLabel: String = "",
    val isProgramEnabled: Boolean = false,
    val isTimelineActive: Boolean = false,
    val healthLabel: String = "",
    val temperatureLabel: String = "",
    val fanLabel: String = "",
    val deviceTimeLabel: String = "",
    val firmwareLabel: String = ""
)